apiVersion: elasticache.services.k8s.aws/v1alpha1
kind: ServerlessCache
metadata:
  name: test-serverless-cache-2
spec:
  serverlessCacheName: test-serverless-cache-2
  description: "Updated serverless cache description"
  engine: "redis"
  majorEngineVersion: "7"
  cacheUsageLimits:
    eCPUPerSecond:
      minimum: 10000
      maximum: 100000
  securityGroupIDs:
    - sg-01d8a3abb41a87f69
  subnetIDs:
    - subnet-0c5b988253e3feeb2
    - subnet-0e65c56d65d46c170
  tags:
    - key: "Environment"
      value: "test"
    - key: "Project"
      value: "serverless-cache"
    - key: "Owner"
      value: "ack-controller"
