// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package snapshot

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	kmsapitypes "github.com/aws-controllers-k8s/kms-controller/apis/v1alpha1"
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrt "github.com/aws-controllers-k8s/runtime/pkg/runtime"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"

	svcapitypes "github.com/aws-controllers-k8s/elasticache-controller/apis/v1alpha1"
)

// +kubebuilder:rbac:groups=kms.services.k8s.aws,resources=keys,verbs=get;list
// +kubebuilder:rbac:groups=kms.services.k8s.aws,resources=keys/status,verbs=get;list

// ClearResolvedReferences removes any reference values that were made
// concrete in the spec. It returns a copy of the input AWSResource which
// contains the original *Ref values, but none of their respective concrete
// values.
func (rm *resourceManager) ClearResolvedReferences(res acktypes.AWSResource) acktypes.AWSResource {
	ko := rm.concreteResource(res).ko.DeepCopy()

	if ko.Spec.CacheClusterRef != nil {
		ko.Spec.CacheClusterID = nil
	}

	if ko.Spec.KMSKeyRef != nil {
		ko.Spec.KMSKeyID = nil
	}

	if ko.Spec.ReplicationGroupRef != nil {
		ko.Spec.ReplicationGroupID = nil
	}

	if ko.Spec.SourceSnapshotRef != nil {
		ko.Spec.SourceSnapshotName = nil
	}

	return &resource{ko}
}

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve those
// reference field(s) into their respective target field(s). It returns a
// copy of the input AWSResource with resolved reference(s), a boolean which
// is set to true if the resource contains any references (regardless of if
// they are resolved successfully) and an error if the passed AWSResource's
// reference field(s) could not be resolved.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, bool, error) {
	ko := rm.concreteResource(res).ko

	resourceHasReferences := false
	err := validateReferenceFields(ko)
	if fieldHasReferences, err := rm.resolveReferenceForCacheClusterID(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForKMSKeyID(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForReplicationGroupID(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForSourceSnapshotName(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	return &resource{ko}, resourceHasReferences, err
}

// validateReferenceFields validates the reference field and corresponding
// identifier field.
func validateReferenceFields(ko *svcapitypes.Snapshot) error {

	if ko.Spec.CacheClusterRef != nil && ko.Spec.CacheClusterID != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("CacheClusterID", "CacheClusterRef")
	}

	if ko.Spec.KMSKeyRef != nil && ko.Spec.KMSKeyID != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("KMSKeyID", "KMSKeyRef")
	}

	if ko.Spec.ReplicationGroupRef != nil && ko.Spec.ReplicationGroupID != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("ReplicationGroupID", "ReplicationGroupRef")
	}

	if ko.Spec.SourceSnapshotRef != nil && ko.Spec.SourceSnapshotName != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("SourceSnapshotName", "SourceSnapshotRef")
	}
	return nil
}

// resolveReferenceForCacheClusterID reads the resource referenced
// from CacheClusterRef field and sets the CacheClusterID
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForCacheClusterID(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.Snapshot,
) (hasReferences bool, err error) {
	if ko.Spec.CacheClusterRef != nil && ko.Spec.CacheClusterRef.From != nil {
		hasReferences = true
		arr := ko.Spec.CacheClusterRef.From
		if arr.Name == nil || *arr.Name == "" {
			return hasReferences, fmt.Errorf("provided resource reference is nil or empty: CacheClusterRef")
		}
		namespace, err := ackrt.ResolveCrossNamespaceReference(
			ctx,
			rm.cfg.EnableCrossNamespace,
			&ko.Status.Conditions,
			ackrt.CrossNamespaceRefKindResource,
			ko.ObjectMeta.GetNamespace(),
			arr.Namespace,
			*arr.Name,
		)
		if err != nil {
			return hasReferences, err
		}
		obj := &svcapitypes.CacheCluster{}
		if err := getReferencedResourceState_CacheCluster(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return hasReferences, err
		}
		ko.Spec.CacheClusterID = (*string)(obj.Spec.CacheClusterID)
	}

	return hasReferences, nil
}

// getReferencedResourceState_CacheCluster looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_CacheCluster(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.CacheCluster,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"CacheCluster",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"CacheCluster",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"CacheCluster",
			namespace, name)
	}
	if obj.Spec.CacheClusterID == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"CacheCluster",
			namespace, name,
			"Spec.CacheClusterID")
	}
	return nil
}

// resolveReferenceForKMSKeyID reads the resource referenced
// from KMSKeyRef field and sets the KMSKeyID
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForKMSKeyID(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.Snapshot,
) (hasReferences bool, err error) {
	if ko.Spec.KMSKeyRef != nil && ko.Spec.KMSKeyRef.From != nil {
		hasReferences = true
		arr := ko.Spec.KMSKeyRef.From
		if arr.Name == nil || *arr.Name == "" {
			return hasReferences, fmt.Errorf("provided resource reference is nil or empty: KMSKeyRef")
		}
		namespace, err := ackrt.ResolveCrossNamespaceReference(
			ctx,
			rm.cfg.EnableCrossNamespace,
			&ko.Status.Conditions,
			ackrt.CrossNamespaceRefKindResource,
			ko.ObjectMeta.GetNamespace(),
			arr.Namespace,
			*arr.Name,
		)
		if err != nil {
			return hasReferences, err
		}
		obj := &kmsapitypes.Key{}
		if err := getReferencedResourceState_Key(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return hasReferences, err
		}
		ko.Spec.KMSKeyID = (*string)(obj.Status.ACKResourceMetadata.ARN)
	}

	return hasReferences, nil
}

// getReferencedResourceState_Key looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Key(
	ctx context.Context,
	apiReader client.Reader,
	obj *kmsapitypes.Key,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Key",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Key",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Key",
			namespace, name)
	}
	if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Key",
			namespace, name,
			"Status.ACKResourceMetadata.ARN")
	}
	return nil
}

// resolveReferenceForReplicationGroupID reads the resource referenced
// from ReplicationGroupRef field and sets the ReplicationGroupID
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForReplicationGroupID(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.Snapshot,
) (hasReferences bool, err error) {
	if ko.Spec.ReplicationGroupRef != nil && ko.Spec.ReplicationGroupRef.From != nil {
		hasReferences = true
		arr := ko.Spec.ReplicationGroupRef.From
		if arr.Name == nil || *arr.Name == "" {
			return hasReferences, fmt.Errorf("provided resource reference is nil or empty: ReplicationGroupRef")
		}
		namespace, err := ackrt.ResolveCrossNamespaceReference(
			ctx,
			rm.cfg.EnableCrossNamespace,
			&ko.Status.Conditions,
			ackrt.CrossNamespaceRefKindResource,
			ko.ObjectMeta.GetNamespace(),
			arr.Namespace,
			*arr.Name,
		)
		if err != nil {
			return hasReferences, err
		}
		obj := &svcapitypes.ReplicationGroup{}
		if err := getReferencedResourceState_ReplicationGroup(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return hasReferences, err
		}
		ko.Spec.ReplicationGroupID = (*string)(obj.Spec.ReplicationGroupID)
	}

	return hasReferences, nil
}

// getReferencedResourceState_ReplicationGroup looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_ReplicationGroup(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.ReplicationGroup,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"ReplicationGroup",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"ReplicationGroup",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"ReplicationGroup",
			namespace, name)
	}
	if obj.Spec.ReplicationGroupID == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"ReplicationGroup",
			namespace, name,
			"Spec.ReplicationGroupID")
	}
	return nil
}

// resolveReferenceForSourceSnapshotName reads the resource referenced
// from SourceSnapshotRef field and sets the SourceSnapshotName
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForSourceSnapshotName(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.Snapshot,
) (hasReferences bool, err error) {
	if ko.Spec.SourceSnapshotRef != nil && ko.Spec.SourceSnapshotRef.From != nil {
		hasReferences = true
		arr := ko.Spec.SourceSnapshotRef.From
		if arr.Name == nil || *arr.Name == "" {
			return hasReferences, fmt.Errorf("provided resource reference is nil or empty: SourceSnapshotRef")
		}
		namespace, err := ackrt.ResolveCrossNamespaceReference(
			ctx,
			rm.cfg.EnableCrossNamespace,
			&ko.Status.Conditions,
			ackrt.CrossNamespaceRefKindResource,
			ko.ObjectMeta.GetNamespace(),
			arr.Namespace,
			*arr.Name,
		)
		if err != nil {
			return hasReferences, err
		}
		obj := &svcapitypes.Snapshot{}
		if err := getReferencedResourceState_Snapshot(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return hasReferences, err
		}
		ko.Spec.SourceSnapshotName = (*string)(obj.Spec.SnapshotName)
	}

	return hasReferences, nil
}

// getReferencedResourceState_Snapshot looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Snapshot(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.Snapshot,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Snapshot",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Snapshot",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Snapshot",
			namespace, name)
	}
	if obj.Spec.SnapshotName == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Snapshot",
			namespace, name,
			"Spec.SnapshotName")
	}
	return nil
}
