// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package global_replication_group

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/elasticache"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/elasticache-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.GlobalReplicationGroup{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeGlobalReplicationGroupsOutput
	resp, err = rm.sdkapi.DescribeGlobalReplicationGroups(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeGlobalReplicationGroups", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "GlobalReplicationGroupNotFoundFault" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.GlobalReplicationGroups {
		if elem.ARN != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ARN)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.AtRestEncryptionEnabled != nil {
			ko.Status.AtRestEncryptionEnabled = elem.AtRestEncryptionEnabled
		} else {
			ko.Status.AtRestEncryptionEnabled = nil
		}
		if elem.AuthTokenEnabled != nil {
			ko.Status.AuthTokenEnabled = elem.AuthTokenEnabled
		} else {
			ko.Status.AuthTokenEnabled = nil
		}
		if elem.CacheNodeType != nil {
			ko.Spec.CacheNodeType = elem.CacheNodeType
		} else {
			ko.Spec.CacheNodeType = nil
		}
		if elem.ClusterEnabled != nil {
			ko.Status.ClusterEnabled = elem.ClusterEnabled
		} else {
			ko.Status.ClusterEnabled = nil
		}
		if elem.Engine != nil {
			ko.Spec.Engine = elem.Engine
		} else {
			ko.Spec.Engine = nil
		}
		if elem.EngineVersion != nil {
			ko.Spec.EngineVersion = elem.EngineVersion
		} else {
			ko.Spec.EngineVersion = nil
		}
		if elem.GlobalNodeGroups != nil {
			f7 := []*svcapitypes.GlobalNodeGroup{}
			for _, f7iter := range elem.GlobalNodeGroups {
				f7elem := &svcapitypes.GlobalNodeGroup{}
				if f7iter.GlobalNodeGroupId != nil {
					f7elem.GlobalNodeGroupID = f7iter.GlobalNodeGroupId
				}
				if f7iter.Slots != nil {
					f7elem.Slots = f7iter.Slots
				}
				f7 = append(f7, f7elem)
			}
			ko.Status.GlobalNodeGroups = f7
		} else {
			ko.Status.GlobalNodeGroups = nil
		}
		if elem.GlobalReplicationGroupDescription != nil {
			ko.Spec.Description = elem.GlobalReplicationGroupDescription
		} else {
			ko.Spec.Description = nil
		}
		if elem.GlobalReplicationGroupId != nil {
			ko.Status.GlobalReplicationGroupID = elem.GlobalReplicationGroupId
		} else {
			ko.Status.GlobalReplicationGroupID = nil
		}
		if elem.Members != nil {
			f10 := []*svcapitypes.GlobalReplicationGroupMember{}
			for _, f10iter := range elem.Members {
				f10elem := &svcapitypes.GlobalReplicationGroupMember{}
				if f10iter.AutomaticFailover != "" {
					f10elem.AutomaticFailover = aws.String(string(f10iter.AutomaticFailover))
				}
				if f10iter.ReplicationGroupId != nil {
					f10elem.ReplicationGroupID = f10iter.ReplicationGroupId
				}
				if f10iter.ReplicationGroupRegion != nil {
					f10elem.ReplicationGroupRegion = f10iter.ReplicationGroupRegion
				}
				if f10iter.Role != nil {
					f10elem.Role = f10iter.Role
				}
				if f10iter.Status != nil {
					f10elem.Status = f10iter.Status
				}
				f10 = append(f10, f10elem)
			}
			ko.Status.Members = f10
		} else {
			ko.Status.Members = nil
		}
		if elem.Status != nil {
			ko.Status.Status = elem.Status
		} else {
			ko.Status.Status = nil
		}
		if elem.TransitEncryptionEnabled != nil {
			ko.Status.TransitEncryptionEnabled = elem.TransitEncryptionEnabled
		} else {
			ko.Status.TransitEncryptionEnabled = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	// custom set output from response
	ko, err = rm.CustomDescribeGlobalReplicationGroupsSetOutput(ctx, r, resp, ko)
	if err != nil {
		return nil, err
	}
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Status.GlobalReplicationGroupID == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeGlobalReplicationGroupsInput, error) {
	res := &svcsdk.DescribeGlobalReplicationGroupsInput{}

	if r.ko.Status.GlobalReplicationGroupID != nil {
		res.GlobalReplicationGroupId = r.ko.Status.GlobalReplicationGroupID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateGlobalReplicationGroupOutput
	_ = resp
	resp, err = rm.sdkapi.CreateGlobalReplicationGroup(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateGlobalReplicationGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.GlobalReplicationGroup.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.GlobalReplicationGroup.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.GlobalReplicationGroup.AtRestEncryptionEnabled != nil {
		ko.Status.AtRestEncryptionEnabled = resp.GlobalReplicationGroup.AtRestEncryptionEnabled
	} else {
		ko.Status.AtRestEncryptionEnabled = nil
	}
	if resp.GlobalReplicationGroup.AuthTokenEnabled != nil {
		ko.Status.AuthTokenEnabled = resp.GlobalReplicationGroup.AuthTokenEnabled
	} else {
		ko.Status.AuthTokenEnabled = nil
	}
	if resp.GlobalReplicationGroup.CacheNodeType != nil {
		ko.Spec.CacheNodeType = resp.GlobalReplicationGroup.CacheNodeType
	} else {
		ko.Spec.CacheNodeType = nil
	}
	if resp.GlobalReplicationGroup.ClusterEnabled != nil {
		ko.Status.ClusterEnabled = resp.GlobalReplicationGroup.ClusterEnabled
	} else {
		ko.Status.ClusterEnabled = nil
	}
	if resp.GlobalReplicationGroup.Engine != nil {
		ko.Spec.Engine = resp.GlobalReplicationGroup.Engine
	} else {
		ko.Spec.Engine = nil
	}
	if resp.GlobalReplicationGroup.EngineVersion != nil {
		ko.Spec.EngineVersion = resp.GlobalReplicationGroup.EngineVersion
	} else {
		ko.Spec.EngineVersion = nil
	}
	if resp.GlobalReplicationGroup.GlobalNodeGroups != nil {
		f7 := []*svcapitypes.GlobalNodeGroup{}
		for _, f7iter := range resp.GlobalReplicationGroup.GlobalNodeGroups {
			f7elem := &svcapitypes.GlobalNodeGroup{}
			if f7iter.GlobalNodeGroupId != nil {
				f7elem.GlobalNodeGroupID = f7iter.GlobalNodeGroupId
			}
			if f7iter.Slots != nil {
				f7elem.Slots = f7iter.Slots
			}
			f7 = append(f7, f7elem)
		}
		ko.Status.GlobalNodeGroups = f7
	} else {
		ko.Status.GlobalNodeGroups = nil
	}
	if resp.GlobalReplicationGroup.GlobalReplicationGroupDescription != nil {
		ko.Spec.Description = resp.GlobalReplicationGroup.GlobalReplicationGroupDescription
	} else {
		ko.Spec.Description = nil
	}
	if resp.GlobalReplicationGroup.GlobalReplicationGroupId != nil {
		ko.Status.GlobalReplicationGroupID = resp.GlobalReplicationGroup.GlobalReplicationGroupId
	} else {
		ko.Status.GlobalReplicationGroupID = nil
	}
	if resp.GlobalReplicationGroup.Members != nil {
		f10 := []*svcapitypes.GlobalReplicationGroupMember{}
		for _, f10iter := range resp.GlobalReplicationGroup.Members {
			f10elem := &svcapitypes.GlobalReplicationGroupMember{}
			if f10iter.AutomaticFailover != "" {
				f10elem.AutomaticFailover = aws.String(string(f10iter.AutomaticFailover))
			}
			if f10iter.ReplicationGroupId != nil {
				f10elem.ReplicationGroupID = f10iter.ReplicationGroupId
			}
			if f10iter.ReplicationGroupRegion != nil {
				f10elem.ReplicationGroupRegion = f10iter.ReplicationGroupRegion
			}
			if f10iter.Role != nil {
				f10elem.Role = f10iter.Role
			}
			if f10iter.Status != nil {
				f10elem.Status = f10iter.Status
			}
			f10 = append(f10, f10elem)
		}
		ko.Status.Members = f10
	} else {
		ko.Status.Members = nil
	}
	if resp.GlobalReplicationGroup.Status != nil {
		ko.Status.Status = resp.GlobalReplicationGroup.Status
	} else {
		ko.Status.Status = nil
	}
	if resp.GlobalReplicationGroup.TransitEncryptionEnabled != nil {
		ko.Status.TransitEncryptionEnabled = resp.GlobalReplicationGroup.TransitEncryptionEnabled
	} else {
		ko.Status.TransitEncryptionEnabled = nil
	}

	rm.setStatusDefaults(ko)
	// After a successful Create call, capture the full GlobalReplicationGroupId
	// (which includes the auto-generated region prefix) into status.
	// The user only provides the suffix in spec; this is the canonical ID for all
	// subsequent API calls.
	if resp.GlobalReplicationGroup != nil && resp.GlobalReplicationGroup.GlobalReplicationGroupId != nil {
		ko.Status.GlobalReplicationGroupID = resp.GlobalReplicationGroup.GlobalReplicationGroupId
	}
	if resp.GlobalReplicationGroup != nil && resp.GlobalReplicationGroup.Status != nil {
		ko.Status.Status = resp.GlobalReplicationGroup.Status
	}
	// Record the values of fields the Describe API does not return, so future
	// reconciles can detect when the user actually changes them.
	rm.setLastRequestedUnreadableFields(desired, ko)

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateGlobalReplicationGroupInput, error) {
	res := &svcsdk.CreateGlobalReplicationGroupInput{}

	if r.ko.Spec.Description != nil {
		res.GlobalReplicationGroupDescription = r.ko.Spec.Description
	}
	if r.ko.Spec.GlobalReplicationGroupIDSuffix != nil {
		res.GlobalReplicationGroupIdSuffix = r.ko.Spec.GlobalReplicationGroupIDSuffix
	}
	if r.ko.Spec.PrimaryReplicationGroupID != nil {
		res.PrimaryReplicationGroupId = r.ko.Spec.PrimaryReplicationGroupID
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateGlobalReplicationGroup(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	return rm.customDeleteGlobalReplicationGroup(ctx, r)
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteGlobalReplicationGroupInput, error) {
	res := &svcsdk.DeleteGlobalReplicationGroupInput{}

	if r.ko.Status.GlobalReplicationGroupID != nil {
		res.GlobalReplicationGroupId = r.ko.Status.GlobalReplicationGroupID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.GlobalReplicationGroup,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "GlobalReplicationGroupAlreadyExistsFault",
		"InvalidParameterValue",
		"InvalidParameterCombination",
		"ServiceLinkedRoleNotFoundFault",
		"ReplicationGroupNotFoundFault",
		"InvalidReplicationGroupState":
		return true
	default:
		return false
	}
}
