---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ack-elasticache-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - securitygroups
  verbs:
  - get
  - list
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - securitygroups/status
  verbs:
  - get
  - list
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - subnets
  verbs:
  - get
  - list
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - subnets/status
  verbs:
  - get
  - list
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cacheclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cacheclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cacheparametergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cacheparametergroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cachesubnetgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cachesubnetgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - replicationgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - replicationgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - snapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - usergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - usergroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sns.services.k8s.aws
  resources:
  - topics
  verbs:
  - get
  - list
- apiGroups:
  - sns.services.k8s.aws
  resources:
  - topics/status
  verbs:
  - get
  - list
