// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package replication_group

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/elasticache"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/elasticache/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/elasticache-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.ReplicationGroup{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeReplicationGroupsOutput
	resp, err = rm.sdkapi.DescribeReplicationGroups(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeReplicationGroups", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ReplicationGroupNotFoundFault" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.ReplicationGroups {
		if elem.ARN != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ARN)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.AtRestEncryptionEnabled != nil {
			ko.Spec.AtRestEncryptionEnabled = elem.AtRestEncryptionEnabled
		} else {
			ko.Spec.AtRestEncryptionEnabled = nil
		}
		if elem.AuthTokenEnabled != nil {
			ko.Status.AuthTokenEnabled = elem.AuthTokenEnabled
		} else {
			ko.Status.AuthTokenEnabled = nil
		}
		if elem.AuthTokenLastModifiedDate != nil {
			ko.Status.AuthTokenLastModifiedDate = &metav1.Time{*elem.AuthTokenLastModifiedDate}
		} else {
			ko.Status.AuthTokenLastModifiedDate = nil
		}
		if elem.AutoMinorVersionUpgrade != nil {
			ko.Status.AutoMinorVersionUpgrade = elem.AutoMinorVersionUpgrade
		} else {
			ko.Status.AutoMinorVersionUpgrade = nil
		}
		if elem.AutomaticFailover != "" {
			ko.Status.AutomaticFailover = aws.String(string(elem.AutomaticFailover))
		} else {
			ko.Status.AutomaticFailover = nil
		}
		if elem.CacheNodeType != nil {
			ko.Spec.CacheNodeType = elem.CacheNodeType
		} else {
			ko.Spec.CacheNodeType = nil
		}
		if elem.ClusterEnabled != nil {
			ko.Status.ClusterEnabled = elem.ClusterEnabled
		} else {
			ko.Status.ClusterEnabled = nil
		}
		if elem.ClusterMode != "" {
			ko.Spec.ClusterMode = aws.String(string(elem.ClusterMode))
		} else {
			ko.Spec.ClusterMode = nil
		}
		if elem.ConfigurationEndpoint != nil {
			f9 := &svcapitypes.Endpoint{}
			if elem.ConfigurationEndpoint.Address != nil {
				f9.Address = elem.ConfigurationEndpoint.Address
			}
			if elem.ConfigurationEndpoint.Port != nil {
				portCopy := int64(*elem.ConfigurationEndpoint.Port)
				f9.Port = &portCopy
			}
			ko.Status.ConfigurationEndpoint = f9
		} else {
			ko.Status.ConfigurationEndpoint = nil
		}
		if elem.DataTiering != "" {
			ko.Status.DataTiering = aws.String(string(elem.DataTiering))
		} else {
			ko.Status.DataTiering = nil
		}
		if elem.Description != nil {
			ko.Spec.Description = elem.Description
		} else {
			ko.Spec.Description = nil
		}
		if elem.Engine != nil {
			ko.Spec.Engine = elem.Engine
		} else {
			ko.Spec.Engine = nil
		}
		if elem.GlobalReplicationGroupInfo != nil {
			f13 := &svcapitypes.GlobalReplicationGroupInfo{}
			if elem.GlobalReplicationGroupInfo.GlobalReplicationGroupId != nil {
				f13.GlobalReplicationGroupID = elem.GlobalReplicationGroupInfo.GlobalReplicationGroupId
			}
			if elem.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole != nil {
				f13.GlobalReplicationGroupMemberRole = elem.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole
			}
			ko.Status.GlobalReplicationGroupInfo = f13
		} else {
			ko.Status.GlobalReplicationGroupInfo = nil
		}
		if elem.IpDiscovery != "" {
			ko.Spec.IPDiscovery = aws.String(string(elem.IpDiscovery))
		} else {
			ko.Spec.IPDiscovery = nil
		}
		if elem.KmsKeyId != nil {
			ko.Spec.KMSKeyID = elem.KmsKeyId
		} else {
			ko.Spec.KMSKeyID = nil
		}
		if elem.LogDeliveryConfigurations != nil {
			f16 := []*svcapitypes.LogDeliveryConfigurationRequest{}
			for _, f16iter := range elem.LogDeliveryConfigurations {
				f16elem := &svcapitypes.LogDeliveryConfigurationRequest{}
				if f16iter.DestinationDetails != nil {
					f16elemf0 := &svcapitypes.DestinationDetails{}
					if f16iter.DestinationDetails.CloudWatchLogsDetails != nil {
						f16elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
						if f16iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
							f16elemf0f0.LogGroup = f16iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
						}
						f16elemf0.CloudWatchLogsDetails = f16elemf0f0
					}
					if f16iter.DestinationDetails.KinesisFirehoseDetails != nil {
						f16elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
						if f16iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
							f16elemf0f1.DeliveryStream = f16iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
						}
						f16elemf0.KinesisFirehoseDetails = f16elemf0f1
					}
					f16elem.DestinationDetails = f16elemf0
				}
				if f16iter.DestinationType != "" {
					f16elem.DestinationType = aws.String(string(f16iter.DestinationType))
				}
				if f16iter.LogFormat != "" {
					f16elem.LogFormat = aws.String(string(f16iter.LogFormat))
				}
				if f16iter.LogType != "" {
					f16elem.LogType = aws.String(string(f16iter.LogType))
				}
				f16 = append(f16, f16elem)
			}
			ko.Spec.LogDeliveryConfigurations = f16
		} else {
			ko.Spec.LogDeliveryConfigurations = nil
		}
		if elem.MemberClusters != nil {
			ko.Status.MemberClusters = aws.StringSlice(elem.MemberClusters)
		} else {
			ko.Status.MemberClusters = nil
		}
		if elem.MemberClustersOutpostArns != nil {
			ko.Status.MemberClustersOutpostARNs = aws.StringSlice(elem.MemberClustersOutpostArns)
		} else {
			ko.Status.MemberClustersOutpostARNs = nil
		}
		if elem.MultiAZ != "" {
			ko.Status.MultiAZ = aws.String(string(elem.MultiAZ))
		} else {
			ko.Status.MultiAZ = nil
		}
		if elem.NetworkType != "" {
			ko.Spec.NetworkType = aws.String(string(elem.NetworkType))
		} else {
			ko.Spec.NetworkType = nil
		}
		if elem.NodeGroups != nil {
			f21 := []*svcapitypes.NodeGroup{}
			for _, f21iter := range elem.NodeGroups {
				f21elem := &svcapitypes.NodeGroup{}
				if f21iter.NodeGroupId != nil {
					f21elem.NodeGroupID = f21iter.NodeGroupId
				}
				if f21iter.NodeGroupMembers != nil {
					f21elemf1 := []*svcapitypes.NodeGroupMember{}
					for _, f21elemf1iter := range f21iter.NodeGroupMembers {
						f21elemf1elem := &svcapitypes.NodeGroupMember{}
						if f21elemf1iter.CacheClusterId != nil {
							f21elemf1elem.CacheClusterID = f21elemf1iter.CacheClusterId
						}
						if f21elemf1iter.CacheNodeId != nil {
							f21elemf1elem.CacheNodeID = f21elemf1iter.CacheNodeId
						}
						if f21elemf1iter.CurrentRole != nil {
							f21elemf1elem.CurrentRole = f21elemf1iter.CurrentRole
						}
						if f21elemf1iter.PreferredAvailabilityZone != nil {
							f21elemf1elem.PreferredAvailabilityZone = f21elemf1iter.PreferredAvailabilityZone
						}
						if f21elemf1iter.PreferredOutpostArn != nil {
							f21elemf1elem.PreferredOutpostARN = f21elemf1iter.PreferredOutpostArn
						}
						if f21elemf1iter.ReadEndpoint != nil {
							f21elemf1elemf5 := &svcapitypes.Endpoint{}
							if f21elemf1iter.ReadEndpoint.Address != nil {
								f21elemf1elemf5.Address = f21elemf1iter.ReadEndpoint.Address
							}
							if f21elemf1iter.ReadEndpoint.Port != nil {
								portCopy := int64(*f21elemf1iter.ReadEndpoint.Port)
								f21elemf1elemf5.Port = &portCopy
							}
							f21elemf1elem.ReadEndpoint = f21elemf1elemf5
						}
						f21elemf1 = append(f21elemf1, f21elemf1elem)
					}
					f21elem.NodeGroupMembers = f21elemf1
				}
				if f21iter.PrimaryEndpoint != nil {
					f21elemf2 := &svcapitypes.Endpoint{}
					if f21iter.PrimaryEndpoint.Address != nil {
						f21elemf2.Address = f21iter.PrimaryEndpoint.Address
					}
					if f21iter.PrimaryEndpoint.Port != nil {
						portCopy := int64(*f21iter.PrimaryEndpoint.Port)
						f21elemf2.Port = &portCopy
					}
					f21elem.PrimaryEndpoint = f21elemf2
				}
				if f21iter.ReaderEndpoint != nil {
					f21elemf3 := &svcapitypes.Endpoint{}
					if f21iter.ReaderEndpoint.Address != nil {
						f21elemf3.Address = f21iter.ReaderEndpoint.Address
					}
					if f21iter.ReaderEndpoint.Port != nil {
						portCopy := int64(*f21iter.ReaderEndpoint.Port)
						f21elemf3.Port = &portCopy
					}
					f21elem.ReaderEndpoint = f21elemf3
				}
				if f21iter.Slots != nil {
					f21elem.Slots = f21iter.Slots
				}
				if f21iter.Status != nil {
					f21elem.Status = f21iter.Status
				}
				f21 = append(f21, f21elem)
			}
			ko.Status.NodeGroups = f21
		} else {
			ko.Status.NodeGroups = nil
		}
		if elem.PendingModifiedValues != nil {
			f22 := &svcapitypes.ReplicationGroupPendingModifiedValues{}
			if elem.PendingModifiedValues.AuthTokenStatus != "" {
				f22.AuthTokenStatus = aws.String(string(elem.PendingModifiedValues.AuthTokenStatus))
			}
			if elem.PendingModifiedValues.AutomaticFailoverStatus != "" {
				f22.AutomaticFailoverStatus = aws.String(string(elem.PendingModifiedValues.AutomaticFailoverStatus))
			}
			if elem.PendingModifiedValues.ClusterMode != "" {
				f22.ClusterMode = aws.String(string(elem.PendingModifiedValues.ClusterMode))
			}
			if elem.PendingModifiedValues.LogDeliveryConfigurations != nil {
				f22f3 := []*svcapitypes.PendingLogDeliveryConfiguration{}
				for _, f22f3iter := range elem.PendingModifiedValues.LogDeliveryConfigurations {
					f22f3elem := &svcapitypes.PendingLogDeliveryConfiguration{}
					if f22f3iter.DestinationDetails != nil {
						f22f3elemf0 := &svcapitypes.DestinationDetails{}
						if f22f3iter.DestinationDetails.CloudWatchLogsDetails != nil {
							f22f3elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
							if f22f3iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
								f22f3elemf0f0.LogGroup = f22f3iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
							}
							f22f3elemf0.CloudWatchLogsDetails = f22f3elemf0f0
						}
						if f22f3iter.DestinationDetails.KinesisFirehoseDetails != nil {
							f22f3elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
							if f22f3iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
								f22f3elemf0f1.DeliveryStream = f22f3iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
							}
							f22f3elemf0.KinesisFirehoseDetails = f22f3elemf0f1
						}
						f22f3elem.DestinationDetails = f22f3elemf0
					}
					if f22f3iter.DestinationType != "" {
						f22f3elem.DestinationType = aws.String(string(f22f3iter.DestinationType))
					}
					if f22f3iter.LogFormat != "" {
						f22f3elem.LogFormat = aws.String(string(f22f3iter.LogFormat))
					}
					if f22f3iter.LogType != "" {
						f22f3elem.LogType = aws.String(string(f22f3iter.LogType))
					}
					f22f3 = append(f22f3, f22f3elem)
				}
				f22.LogDeliveryConfigurations = f22f3
			}
			if elem.PendingModifiedValues.PrimaryClusterId != nil {
				f22.PrimaryClusterID = elem.PendingModifiedValues.PrimaryClusterId
			}
			if elem.PendingModifiedValues.Resharding != nil {
				f22f5 := &svcapitypes.ReshardingStatus{}
				if elem.PendingModifiedValues.Resharding.SlotMigration != nil {
					f22f5f0 := &svcapitypes.SlotMigration{}
					if elem.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage != nil {
						f22f5f0.ProgressPercentage = elem.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage
					}
					f22f5.SlotMigration = f22f5f0
				}
				f22.Resharding = f22f5
			}
			if elem.PendingModifiedValues.TransitEncryptionEnabled != nil {
				f22.TransitEncryptionEnabled = elem.PendingModifiedValues.TransitEncryptionEnabled
			}
			if elem.PendingModifiedValues.TransitEncryptionMode != "" {
				f22.TransitEncryptionMode = aws.String(string(elem.PendingModifiedValues.TransitEncryptionMode))
			}
			if elem.PendingModifiedValues.UserGroups != nil {
				f22f8 := &svcapitypes.UserGroupsUpdateStatus{}
				if elem.PendingModifiedValues.UserGroups.UserGroupIdsToAdd != nil {
					f22f8.UserGroupIDsToAdd = aws.StringSlice(elem.PendingModifiedValues.UserGroups.UserGroupIdsToAdd)
				}
				if elem.PendingModifiedValues.UserGroups.UserGroupIdsToRemove != nil {
					f22f8.UserGroupIDsToRemove = aws.StringSlice(elem.PendingModifiedValues.UserGroups.UserGroupIdsToRemove)
				}
				f22.UserGroups = f22f8
			}
			ko.Status.PendingModifiedValues = f22
		} else {
			ko.Status.PendingModifiedValues = nil
		}
		if elem.ReplicationGroupCreateTime != nil {
			ko.Status.ReplicationGroupCreateTime = &metav1.Time{*elem.ReplicationGroupCreateTime}
		} else {
			ko.Status.ReplicationGroupCreateTime = nil
		}
		if elem.ReplicationGroupId != nil {
			ko.Spec.ReplicationGroupID = elem.ReplicationGroupId
		} else {
			ko.Spec.ReplicationGroupID = nil
		}
		if elem.SnapshotRetentionLimit != nil {
			snapshotRetentionLimitCopy := int64(*elem.SnapshotRetentionLimit)
			ko.Spec.SnapshotRetentionLimit = &snapshotRetentionLimitCopy
		} else {
			ko.Spec.SnapshotRetentionLimit = nil
		}
		if elem.SnapshotWindow != nil {
			ko.Spec.SnapshotWindow = elem.SnapshotWindow
		} else {
			ko.Spec.SnapshotWindow = nil
		}
		if elem.SnapshottingClusterId != nil {
			ko.Status.SnapshottingClusterID = elem.SnapshottingClusterId
		} else {
			ko.Status.SnapshottingClusterID = nil
		}
		if elem.Status != nil {
			ko.Status.Status = elem.Status
		} else {
			ko.Status.Status = nil
		}
		if elem.TransitEncryptionEnabled != nil {
			ko.Spec.TransitEncryptionEnabled = elem.TransitEncryptionEnabled
		} else {
			ko.Spec.TransitEncryptionEnabled = nil
		}
		if elem.TransitEncryptionMode != "" {
			ko.Spec.TransitEncryptionMode = aws.String(string(elem.TransitEncryptionMode))
		} else {
			ko.Spec.TransitEncryptionMode = nil
		}
		if elem.UserGroupIds != nil {
			ko.Spec.UserGroupIDs = aws.StringSlice(elem.UserGroupIds)
		} else {
			ko.Spec.UserGroupIDs = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	// custom set output from response
	ko, err = rm.CustomDescribeReplicationGroupsSetOutput(ctx, r, resp, ko)
	if err != nil {
		return nil, err
	}

	rm.updateSpecFields(ctx, resp.ReplicationGroups[0], &resource{ko})
	if isDeleting(r) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(
			&resource{ko},
			corev1.ConditionFalse,
			&condMsgCurrentlyDeleting,
			nil,
		)
		return &resource{ko}, nil
	}
	if isModifying(r) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(
			&resource{ko},
			corev1.ConditionFalse,
			&condMsgNoDeleteWhileModifying,
			nil,
		)
		return &resource{ko}, nil
	}

	if isCreating(r) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(
			&resource{ko},
			corev1.ConditionFalse,
			&condMsgCurrentlyCreating,
			nil,
		)
		return &resource{ko}, nil
	}

	if isCreateFailed(r) {
		// This is a terminal state and by setting a Terminal condition on the
		// resource, we will prevent it from being requeued.
		ackcondition.SetTerminal(
			&resource{ko},
			corev1.ConditionTrue,
			&condMsgTerminalCreateFailed,
			nil,
		)
		return &resource{ko}, nil
	}

	if ko.Status.ACKResourceMetadata != nil && ko.Status.ACKResourceMetadata.ARN != nil {
		resourceARN := (*string)(ko.Status.ACKResourceMetadata.ARN)
		tags, err := rm.getTags(ctx, *resourceARN)
		if err != nil {
			return nil, err
		}
		ko.Spec.Tags = tags
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Spec.ReplicationGroupID == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeReplicationGroupsInput, error) {
	res := &svcsdk.DescribeReplicationGroupsInput{}

	if r.ko.Spec.ReplicationGroupID != nil {
		res.ReplicationGroupId = r.ko.Spec.ReplicationGroupID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateReplicationGroupOutput
	_ = resp
	resp, err = rm.sdkapi.CreateReplicationGroup(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateReplicationGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ReplicationGroup.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ReplicationGroup.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ReplicationGroup.AtRestEncryptionEnabled != nil {
		ko.Spec.AtRestEncryptionEnabled = resp.ReplicationGroup.AtRestEncryptionEnabled
	} else {
		ko.Spec.AtRestEncryptionEnabled = nil
	}
	if resp.ReplicationGroup.AuthTokenEnabled != nil {
		ko.Status.AuthTokenEnabled = resp.ReplicationGroup.AuthTokenEnabled
	} else {
		ko.Status.AuthTokenEnabled = nil
	}
	if resp.ReplicationGroup.AuthTokenLastModifiedDate != nil {
		ko.Status.AuthTokenLastModifiedDate = &metav1.Time{*resp.ReplicationGroup.AuthTokenLastModifiedDate}
	} else {
		ko.Status.AuthTokenLastModifiedDate = nil
	}
	if resp.ReplicationGroup.AutoMinorVersionUpgrade != nil {
		ko.Status.AutoMinorVersionUpgrade = resp.ReplicationGroup.AutoMinorVersionUpgrade
	} else {
		ko.Status.AutoMinorVersionUpgrade = nil
	}
	if resp.ReplicationGroup.AutomaticFailover != "" {
		ko.Status.AutomaticFailover = aws.String(string(resp.ReplicationGroup.AutomaticFailover))
	} else {
		ko.Status.AutomaticFailover = nil
	}
	if resp.ReplicationGroup.CacheNodeType != nil {
		ko.Spec.CacheNodeType = resp.ReplicationGroup.CacheNodeType
	} else {
		ko.Spec.CacheNodeType = nil
	}
	if resp.ReplicationGroup.ClusterEnabled != nil {
		ko.Status.ClusterEnabled = resp.ReplicationGroup.ClusterEnabled
	} else {
		ko.Status.ClusterEnabled = nil
	}
	if resp.ReplicationGroup.ClusterMode != "" {
		ko.Spec.ClusterMode = aws.String(string(resp.ReplicationGroup.ClusterMode))
	} else {
		ko.Spec.ClusterMode = nil
	}
	if resp.ReplicationGroup.ConfigurationEndpoint != nil {
		f9 := &svcapitypes.Endpoint{}
		if resp.ReplicationGroup.ConfigurationEndpoint.Address != nil {
			f9.Address = resp.ReplicationGroup.ConfigurationEndpoint.Address
		}
		if resp.ReplicationGroup.ConfigurationEndpoint.Port != nil {
			portCopy := int64(*resp.ReplicationGroup.ConfigurationEndpoint.Port)
			f9.Port = &portCopy
		}
		ko.Status.ConfigurationEndpoint = f9
	} else {
		ko.Status.ConfigurationEndpoint = nil
	}
	if resp.ReplicationGroup.DataTiering != "" {
		ko.Status.DataTiering = aws.String(string(resp.ReplicationGroup.DataTiering))
	} else {
		ko.Status.DataTiering = nil
	}
	if resp.ReplicationGroup.Description != nil {
		ko.Spec.Description = resp.ReplicationGroup.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.ReplicationGroup.Engine != nil {
		ko.Spec.Engine = resp.ReplicationGroup.Engine
	} else {
		ko.Spec.Engine = nil
	}
	if resp.ReplicationGroup.GlobalReplicationGroupInfo != nil {
		f13 := &svcapitypes.GlobalReplicationGroupInfo{}
		if resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupId != nil {
			f13.GlobalReplicationGroupID = resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupId
		}
		if resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole != nil {
			f13.GlobalReplicationGroupMemberRole = resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole
		}
		ko.Status.GlobalReplicationGroupInfo = f13
	} else {
		ko.Status.GlobalReplicationGroupInfo = nil
	}
	if resp.ReplicationGroup.IpDiscovery != "" {
		ko.Spec.IPDiscovery = aws.String(string(resp.ReplicationGroup.IpDiscovery))
	} else {
		ko.Spec.IPDiscovery = nil
	}
	if resp.ReplicationGroup.KmsKeyId != nil {
		ko.Spec.KMSKeyID = resp.ReplicationGroup.KmsKeyId
	} else {
		ko.Spec.KMSKeyID = nil
	}
	if resp.ReplicationGroup.LogDeliveryConfigurations != nil {
		f16 := []*svcapitypes.LogDeliveryConfigurationRequest{}
		for _, f16iter := range resp.ReplicationGroup.LogDeliveryConfigurations {
			f16elem := &svcapitypes.LogDeliveryConfigurationRequest{}
			if f16iter.DestinationDetails != nil {
				f16elemf0 := &svcapitypes.DestinationDetails{}
				if f16iter.DestinationDetails.CloudWatchLogsDetails != nil {
					f16elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
					if f16iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
						f16elemf0f0.LogGroup = f16iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
					}
					f16elemf0.CloudWatchLogsDetails = f16elemf0f0
				}
				if f16iter.DestinationDetails.KinesisFirehoseDetails != nil {
					f16elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
					if f16iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
						f16elemf0f1.DeliveryStream = f16iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
					}
					f16elemf0.KinesisFirehoseDetails = f16elemf0f1
				}
				f16elem.DestinationDetails = f16elemf0
			}
			if f16iter.DestinationType != "" {
				f16elem.DestinationType = aws.String(string(f16iter.DestinationType))
			}
			if f16iter.LogFormat != "" {
				f16elem.LogFormat = aws.String(string(f16iter.LogFormat))
			}
			if f16iter.LogType != "" {
				f16elem.LogType = aws.String(string(f16iter.LogType))
			}
			f16 = append(f16, f16elem)
		}
		ko.Spec.LogDeliveryConfigurations = f16
	} else {
		ko.Spec.LogDeliveryConfigurations = nil
	}
	if resp.ReplicationGroup.MemberClusters != nil {
		ko.Status.MemberClusters = aws.StringSlice(resp.ReplicationGroup.MemberClusters)
	} else {
		ko.Status.MemberClusters = nil
	}
	if resp.ReplicationGroup.MemberClustersOutpostArns != nil {
		ko.Status.MemberClustersOutpostARNs = aws.StringSlice(resp.ReplicationGroup.MemberClustersOutpostArns)
	} else {
		ko.Status.MemberClustersOutpostARNs = nil
	}
	if resp.ReplicationGroup.MultiAZ != "" {
		ko.Status.MultiAZ = aws.String(string(resp.ReplicationGroup.MultiAZ))
	} else {
		ko.Status.MultiAZ = nil
	}
	if resp.ReplicationGroup.NetworkType != "" {
		ko.Spec.NetworkType = aws.String(string(resp.ReplicationGroup.NetworkType))
	} else {
		ko.Spec.NetworkType = nil
	}
	if resp.ReplicationGroup.NodeGroups != nil {
		f21 := []*svcapitypes.NodeGroup{}
		for _, f21iter := range resp.ReplicationGroup.NodeGroups {
			f21elem := &svcapitypes.NodeGroup{}
			if f21iter.NodeGroupId != nil {
				f21elem.NodeGroupID = f21iter.NodeGroupId
			}
			if f21iter.NodeGroupMembers != nil {
				f21elemf1 := []*svcapitypes.NodeGroupMember{}
				for _, f21elemf1iter := range f21iter.NodeGroupMembers {
					f21elemf1elem := &svcapitypes.NodeGroupMember{}
					if f21elemf1iter.CacheClusterId != nil {
						f21elemf1elem.CacheClusterID = f21elemf1iter.CacheClusterId
					}
					if f21elemf1iter.CacheNodeId != nil {
						f21elemf1elem.CacheNodeID = f21elemf1iter.CacheNodeId
					}
					if f21elemf1iter.CurrentRole != nil {
						f21elemf1elem.CurrentRole = f21elemf1iter.CurrentRole
					}
					if f21elemf1iter.PreferredAvailabilityZone != nil {
						f21elemf1elem.PreferredAvailabilityZone = f21elemf1iter.PreferredAvailabilityZone
					}
					if f21elemf1iter.PreferredOutpostArn != nil {
						f21elemf1elem.PreferredOutpostARN = f21elemf1iter.PreferredOutpostArn
					}
					if f21elemf1iter.ReadEndpoint != nil {
						f21elemf1elemf5 := &svcapitypes.Endpoint{}
						if f21elemf1iter.ReadEndpoint.Address != nil {
							f21elemf1elemf5.Address = f21elemf1iter.ReadEndpoint.Address
						}
						if f21elemf1iter.ReadEndpoint.Port != nil {
							portCopy := int64(*f21elemf1iter.ReadEndpoint.Port)
							f21elemf1elemf5.Port = &portCopy
						}
						f21elemf1elem.ReadEndpoint = f21elemf1elemf5
					}
					f21elemf1 = append(f21elemf1, f21elemf1elem)
				}
				f21elem.NodeGroupMembers = f21elemf1
			}
			if f21iter.PrimaryEndpoint != nil {
				f21elemf2 := &svcapitypes.Endpoint{}
				if f21iter.PrimaryEndpoint.Address != nil {
					f21elemf2.Address = f21iter.PrimaryEndpoint.Address
				}
				if f21iter.PrimaryEndpoint.Port != nil {
					portCopy := int64(*f21iter.PrimaryEndpoint.Port)
					f21elemf2.Port = &portCopy
				}
				f21elem.PrimaryEndpoint = f21elemf2
			}
			if f21iter.ReaderEndpoint != nil {
				f21elemf3 := &svcapitypes.Endpoint{}
				if f21iter.ReaderEndpoint.Address != nil {
					f21elemf3.Address = f21iter.ReaderEndpoint.Address
				}
				if f21iter.ReaderEndpoint.Port != nil {
					portCopy := int64(*f21iter.ReaderEndpoint.Port)
					f21elemf3.Port = &portCopy
				}
				f21elem.ReaderEndpoint = f21elemf3
			}
			if f21iter.Slots != nil {
				f21elem.Slots = f21iter.Slots
			}
			if f21iter.Status != nil {
				f21elem.Status = f21iter.Status
			}
			f21 = append(f21, f21elem)
		}
		ko.Status.NodeGroups = f21
	} else {
		ko.Status.NodeGroups = nil
	}
	if resp.ReplicationGroup.PendingModifiedValues != nil {
		f22 := &svcapitypes.ReplicationGroupPendingModifiedValues{}
		if resp.ReplicationGroup.PendingModifiedValues.AuthTokenStatus != "" {
			f22.AuthTokenStatus = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.AuthTokenStatus))
		}
		if resp.ReplicationGroup.PendingModifiedValues.AutomaticFailoverStatus != "" {
			f22.AutomaticFailoverStatus = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.AutomaticFailoverStatus))
		}
		if resp.ReplicationGroup.PendingModifiedValues.ClusterMode != "" {
			f22.ClusterMode = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.ClusterMode))
		}
		if resp.ReplicationGroup.PendingModifiedValues.LogDeliveryConfigurations != nil {
			f22f3 := []*svcapitypes.PendingLogDeliveryConfiguration{}
			for _, f22f3iter := range resp.ReplicationGroup.PendingModifiedValues.LogDeliveryConfigurations {
				f22f3elem := &svcapitypes.PendingLogDeliveryConfiguration{}
				if f22f3iter.DestinationDetails != nil {
					f22f3elemf0 := &svcapitypes.DestinationDetails{}
					if f22f3iter.DestinationDetails.CloudWatchLogsDetails != nil {
						f22f3elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
						if f22f3iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
							f22f3elemf0f0.LogGroup = f22f3iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
						}
						f22f3elemf0.CloudWatchLogsDetails = f22f3elemf0f0
					}
					if f22f3iter.DestinationDetails.KinesisFirehoseDetails != nil {
						f22f3elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
						if f22f3iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
							f22f3elemf0f1.DeliveryStream = f22f3iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
						}
						f22f3elemf0.KinesisFirehoseDetails = f22f3elemf0f1
					}
					f22f3elem.DestinationDetails = f22f3elemf0
				}
				if f22f3iter.DestinationType != "" {
					f22f3elem.DestinationType = aws.String(string(f22f3iter.DestinationType))
				}
				if f22f3iter.LogFormat != "" {
					f22f3elem.LogFormat = aws.String(string(f22f3iter.LogFormat))
				}
				if f22f3iter.LogType != "" {
					f22f3elem.LogType = aws.String(string(f22f3iter.LogType))
				}
				f22f3 = append(f22f3, f22f3elem)
			}
			f22.LogDeliveryConfigurations = f22f3
		}
		if resp.ReplicationGroup.PendingModifiedValues.PrimaryClusterId != nil {
			f22.PrimaryClusterID = resp.ReplicationGroup.PendingModifiedValues.PrimaryClusterId
		}
		if resp.ReplicationGroup.PendingModifiedValues.Resharding != nil {
			f22f5 := &svcapitypes.ReshardingStatus{}
			if resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration != nil {
				f22f5f0 := &svcapitypes.SlotMigration{}
				if resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage != nil {
					f22f5f0.ProgressPercentage = resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage
				}
				f22f5.SlotMigration = f22f5f0
			}
			f22.Resharding = f22f5
		}
		if resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionEnabled != nil {
			f22.TransitEncryptionEnabled = resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionEnabled
		}
		if resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionMode != "" {
			f22.TransitEncryptionMode = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionMode))
		}
		if resp.ReplicationGroup.PendingModifiedValues.UserGroups != nil {
			f22f8 := &svcapitypes.UserGroupsUpdateStatus{}
			if resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToAdd != nil {
				f22f8.UserGroupIDsToAdd = aws.StringSlice(resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToAdd)
			}
			if resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToRemove != nil {
				f22f8.UserGroupIDsToRemove = aws.StringSlice(resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToRemove)
			}
			f22.UserGroups = f22f8
		}
		ko.Status.PendingModifiedValues = f22
	} else {
		ko.Status.PendingModifiedValues = nil
	}
	if resp.ReplicationGroup.ReplicationGroupCreateTime != nil {
		ko.Status.ReplicationGroupCreateTime = &metav1.Time{*resp.ReplicationGroup.ReplicationGroupCreateTime}
	} else {
		ko.Status.ReplicationGroupCreateTime = nil
	}
	if resp.ReplicationGroup.ReplicationGroupId != nil {
		ko.Spec.ReplicationGroupID = resp.ReplicationGroup.ReplicationGroupId
	} else {
		ko.Spec.ReplicationGroupID = nil
	}
	if resp.ReplicationGroup.SnapshotRetentionLimit != nil {
		snapshotRetentionLimitCopy := int64(*resp.ReplicationGroup.SnapshotRetentionLimit)
		ko.Spec.SnapshotRetentionLimit = &snapshotRetentionLimitCopy
	} else {
		ko.Spec.SnapshotRetentionLimit = nil
	}
	if resp.ReplicationGroup.SnapshotWindow != nil {
		ko.Spec.SnapshotWindow = resp.ReplicationGroup.SnapshotWindow
	} else {
		ko.Spec.SnapshotWindow = nil
	}
	if resp.ReplicationGroup.SnapshottingClusterId != nil {
		ko.Status.SnapshottingClusterID = resp.ReplicationGroup.SnapshottingClusterId
	} else {
		ko.Status.SnapshottingClusterID = nil
	}
	if resp.ReplicationGroup.Status != nil {
		ko.Status.Status = resp.ReplicationGroup.Status
	} else {
		ko.Status.Status = nil
	}
	if resp.ReplicationGroup.TransitEncryptionEnabled != nil {
		ko.Spec.TransitEncryptionEnabled = resp.ReplicationGroup.TransitEncryptionEnabled
	} else {
		ko.Spec.TransitEncryptionEnabled = nil
	}
	if resp.ReplicationGroup.TransitEncryptionMode != "" {
		ko.Spec.TransitEncryptionMode = aws.String(string(resp.ReplicationGroup.TransitEncryptionMode))
	} else {
		ko.Spec.TransitEncryptionMode = nil
	}
	if resp.ReplicationGroup.UserGroupIds != nil {
		ko.Spec.UserGroupIDs = aws.StringSlice(resp.ReplicationGroup.UserGroupIds)
	} else {
		ko.Spec.UserGroupIDs = nil
	}

	rm.setStatusDefaults(ko)
	// custom set output from response
	ko, err = rm.CustomCreateReplicationGroupSetOutput(ctx, desired, resp, ko)
	if err != nil {
		return nil, err
	}
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateReplicationGroupInput, error) {
	res := &svcsdk.CreateReplicationGroupInput{}

	if r.ko.Spec.AtRestEncryptionEnabled != nil {
		res.AtRestEncryptionEnabled = r.ko.Spec.AtRestEncryptionEnabled
	}
	if r.ko.Spec.AuthToken != nil {
		tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.AuthToken)
		if err != nil {
			return nil, ackrequeue.Needed(err)
		}
		if tmpSecret != "" {
			res.AuthToken = aws.String(tmpSecret)
		}
	}
	if r.ko.Spec.AutomaticFailoverEnabled != nil {
		res.AutomaticFailoverEnabled = r.ko.Spec.AutomaticFailoverEnabled
	}
	if r.ko.Spec.CacheNodeType != nil {
		res.CacheNodeType = r.ko.Spec.CacheNodeType
	}
	if r.ko.Spec.CacheParameterGroupName != nil {
		res.CacheParameterGroupName = r.ko.Spec.CacheParameterGroupName
	}
	if r.ko.Spec.CacheSecurityGroupNames != nil {
		res.CacheSecurityGroupNames = aws.ToStringSlice(r.ko.Spec.CacheSecurityGroupNames)
	}
	if r.ko.Spec.CacheSubnetGroupName != nil {
		res.CacheSubnetGroupName = r.ko.Spec.CacheSubnetGroupName
	}
	if r.ko.Spec.ClusterMode != nil {
		res.ClusterMode = svcsdktypes.ClusterMode(*r.ko.Spec.ClusterMode)
	}
	if r.ko.Spec.DataTieringEnabled != nil {
		res.DataTieringEnabled = r.ko.Spec.DataTieringEnabled
	}
	if r.ko.Spec.Engine != nil {
		res.Engine = r.ko.Spec.Engine
	}
	if r.ko.Spec.EngineVersion != nil {
		res.EngineVersion = r.ko.Spec.EngineVersion
	}
	if r.ko.Spec.IPDiscovery != nil {
		res.IpDiscovery = svcsdktypes.IpDiscovery(*r.ko.Spec.IPDiscovery)
	}
	if r.ko.Spec.KMSKeyID != nil {
		res.KmsKeyId = r.ko.Spec.KMSKeyID
	}
	if r.ko.Spec.LogDeliveryConfigurations != nil {
		f13 := []svcsdktypes.LogDeliveryConfigurationRequest{}
		for _, f13iter := range r.ko.Spec.LogDeliveryConfigurations {
			f13elem := &svcsdktypes.LogDeliveryConfigurationRequest{}
			if f13iter.DestinationDetails != nil {
				f13elemf0 := &svcsdktypes.DestinationDetails{}
				if f13iter.DestinationDetails.CloudWatchLogsDetails != nil {
					f13elemf0f0 := &svcsdktypes.CloudWatchLogsDestinationDetails{}
					if f13iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
						f13elemf0f0.LogGroup = f13iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
					}
					f13elemf0.CloudWatchLogsDetails = f13elemf0f0
				}
				if f13iter.DestinationDetails.KinesisFirehoseDetails != nil {
					f13elemf0f1 := &svcsdktypes.KinesisFirehoseDestinationDetails{}
					if f13iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
						f13elemf0f1.DeliveryStream = f13iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
					}
					f13elemf0.KinesisFirehoseDetails = f13elemf0f1
				}
				f13elem.DestinationDetails = f13elemf0
			}
			if f13iter.DestinationType != nil {
				f13elem.DestinationType = svcsdktypes.DestinationType(*f13iter.DestinationType)
			}
			if f13iter.Enabled != nil {
				f13elem.Enabled = f13iter.Enabled
			}
			if f13iter.LogFormat != nil {
				f13elem.LogFormat = svcsdktypes.LogFormat(*f13iter.LogFormat)
			}
			if f13iter.LogType != nil {
				f13elem.LogType = svcsdktypes.LogType(*f13iter.LogType)
			}
			f13 = append(f13, *f13elem)
		}
		res.LogDeliveryConfigurations = f13
	}
	if r.ko.Spec.MultiAZEnabled != nil {
		res.MultiAZEnabled = r.ko.Spec.MultiAZEnabled
	}
	if r.ko.Spec.NetworkType != nil {
		res.NetworkType = svcsdktypes.NetworkType(*r.ko.Spec.NetworkType)
	}
	if r.ko.Spec.NodeGroupConfiguration != nil {
		f16 := []svcsdktypes.NodeGroupConfiguration{}
		for _, f16iter := range r.ko.Spec.NodeGroupConfiguration {
			f16elem := &svcsdktypes.NodeGroupConfiguration{}
			if f16iter.NodeGroupID != nil {
				f16elem.NodeGroupId = f16iter.NodeGroupID
			}
			if f16iter.PrimaryAvailabilityZone != nil {
				f16elem.PrimaryAvailabilityZone = f16iter.PrimaryAvailabilityZone
			}
			if f16iter.PrimaryOutpostARN != nil {
				f16elem.PrimaryOutpostArn = f16iter.PrimaryOutpostARN
			}
			if f16iter.ReplicaAvailabilityZones != nil {
				f16elem.ReplicaAvailabilityZones = aws.ToStringSlice(f16iter.ReplicaAvailabilityZones)
			}
			if f16iter.ReplicaCount != nil {
				replicaCountCopy0 := *f16iter.ReplicaCount
				if replicaCountCopy0 > math.MaxInt32 || replicaCountCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field ReplicaCount is of type int32")
				}
				replicaCountCopy := int32(replicaCountCopy0)
				f16elem.ReplicaCount = &replicaCountCopy
			}
			if f16iter.ReplicaOutpostARNs != nil {
				f16elem.ReplicaOutpostArns = aws.ToStringSlice(f16iter.ReplicaOutpostARNs)
			}
			if f16iter.Slots != nil {
				f16elem.Slots = f16iter.Slots
			}
			f16 = append(f16, *f16elem)
		}
		res.NodeGroupConfiguration = f16
	}
	if r.ko.Spec.NotificationTopicARN != nil {
		res.NotificationTopicArn = r.ko.Spec.NotificationTopicARN
	}
	if r.ko.Spec.NumNodeGroups != nil {
		numNodeGroupsCopy0 := *r.ko.Spec.NumNodeGroups
		if numNodeGroupsCopy0 > math.MaxInt32 || numNodeGroupsCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field NumNodeGroups is of type int32")
		}
		numNodeGroupsCopy := int32(numNodeGroupsCopy0)
		res.NumNodeGroups = &numNodeGroupsCopy
	}
	if r.ko.Spec.Port != nil {
		portCopy0 := *r.ko.Spec.Port
		if portCopy0 > math.MaxInt32 || portCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Port is of type int32")
		}
		portCopy := int32(portCopy0)
		res.Port = &portCopy
	}
	if r.ko.Spec.PreferredCacheClusterAZs != nil {
		res.PreferredCacheClusterAZs = aws.ToStringSlice(r.ko.Spec.PreferredCacheClusterAZs)
	}
	if r.ko.Spec.PreferredMaintenanceWindow != nil {
		res.PreferredMaintenanceWindow = r.ko.Spec.PreferredMaintenanceWindow
	}
	if r.ko.Spec.PrimaryClusterID != nil {
		res.PrimaryClusterId = r.ko.Spec.PrimaryClusterID
	}
	if r.ko.Spec.ReplicasPerNodeGroup != nil {
		replicasPerNodeGroupCopy0 := *r.ko.Spec.ReplicasPerNodeGroup
		if replicasPerNodeGroupCopy0 > math.MaxInt32 || replicasPerNodeGroupCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field ReplicasPerNodeGroup is of type int32")
		}
		replicasPerNodeGroupCopy := int32(replicasPerNodeGroupCopy0)
		res.ReplicasPerNodeGroup = &replicasPerNodeGroupCopy
	}
	if r.ko.Spec.Description != nil {
		res.ReplicationGroupDescription = r.ko.Spec.Description
	}
	if r.ko.Spec.ReplicationGroupID != nil {
		res.ReplicationGroupId = r.ko.Spec.ReplicationGroupID
	}
	if r.ko.Spec.SecurityGroupIDs != nil {
		res.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.SecurityGroupIDs)
	}
	if r.ko.Spec.ServerlessCacheSnapshotName != nil {
		res.ServerlessCacheSnapshotName = r.ko.Spec.ServerlessCacheSnapshotName
	}
	if r.ko.Spec.SnapshotARNs != nil {
		res.SnapshotArns = aws.ToStringSlice(r.ko.Spec.SnapshotARNs)
	}
	if r.ko.Spec.SnapshotName != nil {
		res.SnapshotName = r.ko.Spec.SnapshotName
	}
	if r.ko.Spec.SnapshotRetentionLimit != nil {
		snapshotRetentionLimitCopy0 := *r.ko.Spec.SnapshotRetentionLimit
		if snapshotRetentionLimitCopy0 > math.MaxInt32 || snapshotRetentionLimitCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field SnapshotRetentionLimit is of type int32")
		}
		snapshotRetentionLimitCopy := int32(snapshotRetentionLimitCopy0)
		res.SnapshotRetentionLimit = &snapshotRetentionLimitCopy
	}
	if r.ko.Spec.SnapshotWindow != nil {
		res.SnapshotWindow = r.ko.Spec.SnapshotWindow
	}
	if r.ko.Spec.Tags != nil {
		f32 := []svcsdktypes.Tag{}
		for _, f32iter := range r.ko.Spec.Tags {
			f32elem := &svcsdktypes.Tag{}
			if f32iter.Key != nil {
				f32elem.Key = f32iter.Key
			}
			if f32iter.Value != nil {
				f32elem.Value = f32iter.Value
			}
			f32 = append(f32, *f32elem)
		}
		res.Tags = f32
	}
	if r.ko.Spec.TransitEncryptionEnabled != nil {
		res.TransitEncryptionEnabled = r.ko.Spec.TransitEncryptionEnabled
	}
	if r.ko.Spec.TransitEncryptionMode != nil {
		res.TransitEncryptionMode = svcsdktypes.TransitEncryptionMode(*r.ko.Spec.TransitEncryptionMode)
	}
	if r.ko.Spec.UserGroupIDs != nil {
		res.UserGroupIds = aws.ToStringSlice(r.ko.Spec.UserGroupIDs)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		if err = rm.syncTags(ctx, desired, latest); err != nil {
			return nil, err
		}
	}

	updated, err = rm.CustomModifyReplicationGroup(ctx, desired, latest, delta)
	if updated != nil || err != nil {
		return updated, err
	}
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	if !delta.DifferentAt("Spec.LogDeliveryConfigurations") {
		input.SetLogDeliveryConfigurations(nil)
	}
	if delta.DifferentAt("UserGroupIDs") {
		for _, diff := range delta.Differences {
			if diff.Path.Contains("UserGroupIDs") {
				existingUserGroups := diff.B.([]*string)
				requiredUserGroups := diff.A.([]*string)

				// User groups to add
				{
					var userGroupsToAdd []*string

					for _, requiredUserGroup := range requiredUserGroups {
						found := false
						for _, existingUserGroup := range existingUserGroups {
							if requiredUserGroup == existingUserGroup {
								found = true
								break
							}
						}

						if !found {
							userGroupsToAdd = append(userGroupsToAdd, requiredUserGroup)
						}
					}

					input.SetUserGroupIdsToAdd(userGroupsToAdd)
				}

				// User groups to remove
				{
					var userGroupsToRemove []*string

					for _, existingUserGroup := range existingUserGroups {
						found := false
						for _, requiredUserGroup := range requiredUserGroups {
							if requiredUserGroup == existingUserGroup {
								found = true
								break
							}
						}

						if !found {
							userGroupsToRemove = append(userGroupsToRemove, existingUserGroup)
						}
					}

					input.SetUserGroupIdsToRemove(userGroupsToRemove)
				}
			}
		}
	}

	var resp *svcsdk.ModifyReplicationGroupOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyReplicationGroup(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyReplicationGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ReplicationGroup.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ReplicationGroup.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ReplicationGroup.AtRestEncryptionEnabled != nil {
		ko.Spec.AtRestEncryptionEnabled = resp.ReplicationGroup.AtRestEncryptionEnabled
	} else {
		ko.Spec.AtRestEncryptionEnabled = nil
	}
	if resp.ReplicationGroup.AuthTokenEnabled != nil {
		ko.Status.AuthTokenEnabled = resp.ReplicationGroup.AuthTokenEnabled
	} else {
		ko.Status.AuthTokenEnabled = nil
	}
	if resp.ReplicationGroup.AuthTokenLastModifiedDate != nil {
		ko.Status.AuthTokenLastModifiedDate = &metav1.Time{*resp.ReplicationGroup.AuthTokenLastModifiedDate}
	} else {
		ko.Status.AuthTokenLastModifiedDate = nil
	}
	if resp.ReplicationGroup.AutoMinorVersionUpgrade != nil {
		ko.Status.AutoMinorVersionUpgrade = resp.ReplicationGroup.AutoMinorVersionUpgrade
	} else {
		ko.Status.AutoMinorVersionUpgrade = nil
	}
	if resp.ReplicationGroup.AutomaticFailover != "" {
		ko.Status.AutomaticFailover = aws.String(string(resp.ReplicationGroup.AutomaticFailover))
	} else {
		ko.Status.AutomaticFailover = nil
	}
	if resp.ReplicationGroup.CacheNodeType != nil {
		ko.Spec.CacheNodeType = resp.ReplicationGroup.CacheNodeType
	} else {
		ko.Spec.CacheNodeType = nil
	}
	if resp.ReplicationGroup.ClusterEnabled != nil {
		ko.Status.ClusterEnabled = resp.ReplicationGroup.ClusterEnabled
	} else {
		ko.Status.ClusterEnabled = nil
	}
	if resp.ReplicationGroup.ClusterMode != "" {
		ko.Spec.ClusterMode = aws.String(string(resp.ReplicationGroup.ClusterMode))
	} else {
		ko.Spec.ClusterMode = nil
	}
	if resp.ReplicationGroup.ConfigurationEndpoint != nil {
		f9 := &svcapitypes.Endpoint{}
		if resp.ReplicationGroup.ConfigurationEndpoint.Address != nil {
			f9.Address = resp.ReplicationGroup.ConfigurationEndpoint.Address
		}
		if resp.ReplicationGroup.ConfigurationEndpoint.Port != nil {
			portCopy := int64(*resp.ReplicationGroup.ConfigurationEndpoint.Port)
			f9.Port = &portCopy
		}
		ko.Status.ConfigurationEndpoint = f9
	} else {
		ko.Status.ConfigurationEndpoint = nil
	}
	if resp.ReplicationGroup.DataTiering != "" {
		ko.Status.DataTiering = aws.String(string(resp.ReplicationGroup.DataTiering))
	} else {
		ko.Status.DataTiering = nil
	}
	if resp.ReplicationGroup.Description != nil {
		ko.Spec.Description = resp.ReplicationGroup.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.ReplicationGroup.Engine != nil {
		ko.Spec.Engine = resp.ReplicationGroup.Engine
	} else {
		ko.Spec.Engine = nil
	}
	if resp.ReplicationGroup.GlobalReplicationGroupInfo != nil {
		f13 := &svcapitypes.GlobalReplicationGroupInfo{}
		if resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupId != nil {
			f13.GlobalReplicationGroupID = resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupId
		}
		if resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole != nil {
			f13.GlobalReplicationGroupMemberRole = resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole
		}
		ko.Status.GlobalReplicationGroupInfo = f13
	} else {
		ko.Status.GlobalReplicationGroupInfo = nil
	}
	if resp.ReplicationGroup.IpDiscovery != "" {
		ko.Spec.IPDiscovery = aws.String(string(resp.ReplicationGroup.IpDiscovery))
	} else {
		ko.Spec.IPDiscovery = nil
	}
	if resp.ReplicationGroup.KmsKeyId != nil {
		ko.Spec.KMSKeyID = resp.ReplicationGroup.KmsKeyId
	} else {
		ko.Spec.KMSKeyID = nil
	}
	if resp.ReplicationGroup.LogDeliveryConfigurations != nil {
		f16 := []*svcapitypes.LogDeliveryConfigurationRequest{}
		for _, f16iter := range resp.ReplicationGroup.LogDeliveryConfigurations {
			f16elem := &svcapitypes.LogDeliveryConfigurationRequest{}
			if f16iter.DestinationDetails != nil {
				f16elemf0 := &svcapitypes.DestinationDetails{}
				if f16iter.DestinationDetails.CloudWatchLogsDetails != nil {
					f16elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
					if f16iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
						f16elemf0f0.LogGroup = f16iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
					}
					f16elemf0.CloudWatchLogsDetails = f16elemf0f0
				}
				if f16iter.DestinationDetails.KinesisFirehoseDetails != nil {
					f16elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
					if f16iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
						f16elemf0f1.DeliveryStream = f16iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
					}
					f16elemf0.KinesisFirehoseDetails = f16elemf0f1
				}
				f16elem.DestinationDetails = f16elemf0
			}
			if f16iter.DestinationType != "" {
				f16elem.DestinationType = aws.String(string(f16iter.DestinationType))
			}
			if f16iter.LogFormat != "" {
				f16elem.LogFormat = aws.String(string(f16iter.LogFormat))
			}
			if f16iter.LogType != "" {
				f16elem.LogType = aws.String(string(f16iter.LogType))
			}
			f16 = append(f16, f16elem)
		}
		ko.Spec.LogDeliveryConfigurations = f16
	} else {
		ko.Spec.LogDeliveryConfigurations = nil
	}
	if resp.ReplicationGroup.MemberClusters != nil {
		ko.Status.MemberClusters = aws.StringSlice(resp.ReplicationGroup.MemberClusters)
	} else {
		ko.Status.MemberClusters = nil
	}
	if resp.ReplicationGroup.MemberClustersOutpostArns != nil {
		ko.Status.MemberClustersOutpostARNs = aws.StringSlice(resp.ReplicationGroup.MemberClustersOutpostArns)
	} else {
		ko.Status.MemberClustersOutpostARNs = nil
	}
	if resp.ReplicationGroup.MultiAZ != "" {
		ko.Status.MultiAZ = aws.String(string(resp.ReplicationGroup.MultiAZ))
	} else {
		ko.Status.MultiAZ = nil
	}
	if resp.ReplicationGroup.NetworkType != "" {
		ko.Spec.NetworkType = aws.String(string(resp.ReplicationGroup.NetworkType))
	} else {
		ko.Spec.NetworkType = nil
	}
	if resp.ReplicationGroup.NodeGroups != nil {
		f21 := []*svcapitypes.NodeGroup{}
		for _, f21iter := range resp.ReplicationGroup.NodeGroups {
			f21elem := &svcapitypes.NodeGroup{}
			if f21iter.NodeGroupId != nil {
				f21elem.NodeGroupID = f21iter.NodeGroupId
			}
			if f21iter.NodeGroupMembers != nil {
				f21elemf1 := []*svcapitypes.NodeGroupMember{}
				for _, f21elemf1iter := range f21iter.NodeGroupMembers {
					f21elemf1elem := &svcapitypes.NodeGroupMember{}
					if f21elemf1iter.CacheClusterId != nil {
						f21elemf1elem.CacheClusterID = f21elemf1iter.CacheClusterId
					}
					if f21elemf1iter.CacheNodeId != nil {
						f21elemf1elem.CacheNodeID = f21elemf1iter.CacheNodeId
					}
					if f21elemf1iter.CurrentRole != nil {
						f21elemf1elem.CurrentRole = f21elemf1iter.CurrentRole
					}
					if f21elemf1iter.PreferredAvailabilityZone != nil {
						f21elemf1elem.PreferredAvailabilityZone = f21elemf1iter.PreferredAvailabilityZone
					}
					if f21elemf1iter.PreferredOutpostArn != nil {
						f21elemf1elem.PreferredOutpostARN = f21elemf1iter.PreferredOutpostArn
					}
					if f21elemf1iter.ReadEndpoint != nil {
						f21elemf1elemf5 := &svcapitypes.Endpoint{}
						if f21elemf1iter.ReadEndpoint.Address != nil {
							f21elemf1elemf5.Address = f21elemf1iter.ReadEndpoint.Address
						}
						if f21elemf1iter.ReadEndpoint.Port != nil {
							portCopy := int64(*f21elemf1iter.ReadEndpoint.Port)
							f21elemf1elemf5.Port = &portCopy
						}
						f21elemf1elem.ReadEndpoint = f21elemf1elemf5
					}
					f21elemf1 = append(f21elemf1, f21elemf1elem)
				}
				f21elem.NodeGroupMembers = f21elemf1
			}
			if f21iter.PrimaryEndpoint != nil {
				f21elemf2 := &svcapitypes.Endpoint{}
				if f21iter.PrimaryEndpoint.Address != nil {
					f21elemf2.Address = f21iter.PrimaryEndpoint.Address
				}
				if f21iter.PrimaryEndpoint.Port != nil {
					portCopy := int64(*f21iter.PrimaryEndpoint.Port)
					f21elemf2.Port = &portCopy
				}
				f21elem.PrimaryEndpoint = f21elemf2
			}
			if f21iter.ReaderEndpoint != nil {
				f21elemf3 := &svcapitypes.Endpoint{}
				if f21iter.ReaderEndpoint.Address != nil {
					f21elemf3.Address = f21iter.ReaderEndpoint.Address
				}
				if f21iter.ReaderEndpoint.Port != nil {
					portCopy := int64(*f21iter.ReaderEndpoint.Port)
					f21elemf3.Port = &portCopy
				}
				f21elem.ReaderEndpoint = f21elemf3
			}
			if f21iter.Slots != nil {
				f21elem.Slots = f21iter.Slots
			}
			if f21iter.Status != nil {
				f21elem.Status = f21iter.Status
			}
			f21 = append(f21, f21elem)
		}
		ko.Status.NodeGroups = f21
	} else {
		ko.Status.NodeGroups = nil
	}
	if resp.ReplicationGroup.PendingModifiedValues != nil {
		f22 := &svcapitypes.ReplicationGroupPendingModifiedValues{}
		if resp.ReplicationGroup.PendingModifiedValues.AuthTokenStatus != "" {
			f22.AuthTokenStatus = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.AuthTokenStatus))
		}
		if resp.ReplicationGroup.PendingModifiedValues.AutomaticFailoverStatus != "" {
			f22.AutomaticFailoverStatus = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.AutomaticFailoverStatus))
		}
		if resp.ReplicationGroup.PendingModifiedValues.ClusterMode != "" {
			f22.ClusterMode = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.ClusterMode))
		}
		if resp.ReplicationGroup.PendingModifiedValues.LogDeliveryConfigurations != nil {
			f22f3 := []*svcapitypes.PendingLogDeliveryConfiguration{}
			for _, f22f3iter := range resp.ReplicationGroup.PendingModifiedValues.LogDeliveryConfigurations {
				f22f3elem := &svcapitypes.PendingLogDeliveryConfiguration{}
				if f22f3iter.DestinationDetails != nil {
					f22f3elemf0 := &svcapitypes.DestinationDetails{}
					if f22f3iter.DestinationDetails.CloudWatchLogsDetails != nil {
						f22f3elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
						if f22f3iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
							f22f3elemf0f0.LogGroup = f22f3iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
						}
						f22f3elemf0.CloudWatchLogsDetails = f22f3elemf0f0
					}
					if f22f3iter.DestinationDetails.KinesisFirehoseDetails != nil {
						f22f3elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
						if f22f3iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
							f22f3elemf0f1.DeliveryStream = f22f3iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
						}
						f22f3elemf0.KinesisFirehoseDetails = f22f3elemf0f1
					}
					f22f3elem.DestinationDetails = f22f3elemf0
				}
				if f22f3iter.DestinationType != "" {
					f22f3elem.DestinationType = aws.String(string(f22f3iter.DestinationType))
				}
				if f22f3iter.LogFormat != "" {
					f22f3elem.LogFormat = aws.String(string(f22f3iter.LogFormat))
				}
				if f22f3iter.LogType != "" {
					f22f3elem.LogType = aws.String(string(f22f3iter.LogType))
				}
				f22f3 = append(f22f3, f22f3elem)
			}
			f22.LogDeliveryConfigurations = f22f3
		}
		if resp.ReplicationGroup.PendingModifiedValues.PrimaryClusterId != nil {
			f22.PrimaryClusterID = resp.ReplicationGroup.PendingModifiedValues.PrimaryClusterId
		}
		if resp.ReplicationGroup.PendingModifiedValues.Resharding != nil {
			f22f5 := &svcapitypes.ReshardingStatus{}
			if resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration != nil {
				f22f5f0 := &svcapitypes.SlotMigration{}
				if resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage != nil {
					f22f5f0.ProgressPercentage = resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage
				}
				f22f5.SlotMigration = f22f5f0
			}
			f22.Resharding = f22f5
		}
		if resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionEnabled != nil {
			f22.TransitEncryptionEnabled = resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionEnabled
		}
		if resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionMode != "" {
			f22.TransitEncryptionMode = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionMode))
		}
		if resp.ReplicationGroup.PendingModifiedValues.UserGroups != nil {
			f22f8 := &svcapitypes.UserGroupsUpdateStatus{}
			if resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToAdd != nil {
				f22f8.UserGroupIDsToAdd = aws.StringSlice(resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToAdd)
			}
			if resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToRemove != nil {
				f22f8.UserGroupIDsToRemove = aws.StringSlice(resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToRemove)
			}
			f22.UserGroups = f22f8
		}
		ko.Status.PendingModifiedValues = f22
	} else {
		ko.Status.PendingModifiedValues = nil
	}
	if resp.ReplicationGroup.ReplicationGroupCreateTime != nil {
		ko.Status.ReplicationGroupCreateTime = &metav1.Time{*resp.ReplicationGroup.ReplicationGroupCreateTime}
	} else {
		ko.Status.ReplicationGroupCreateTime = nil
	}
	if resp.ReplicationGroup.ReplicationGroupId != nil {
		ko.Spec.ReplicationGroupID = resp.ReplicationGroup.ReplicationGroupId
	} else {
		ko.Spec.ReplicationGroupID = nil
	}
	if resp.ReplicationGroup.SnapshotRetentionLimit != nil {
		snapshotRetentionLimitCopy := int64(*resp.ReplicationGroup.SnapshotRetentionLimit)
		ko.Spec.SnapshotRetentionLimit = &snapshotRetentionLimitCopy
	} else {
		ko.Spec.SnapshotRetentionLimit = nil
	}
	if resp.ReplicationGroup.SnapshotWindow != nil {
		ko.Spec.SnapshotWindow = resp.ReplicationGroup.SnapshotWindow
	} else {
		ko.Spec.SnapshotWindow = nil
	}
	if resp.ReplicationGroup.SnapshottingClusterId != nil {
		ko.Status.SnapshottingClusterID = resp.ReplicationGroup.SnapshottingClusterId
	} else {
		ko.Status.SnapshottingClusterID = nil
	}
	if resp.ReplicationGroup.Status != nil {
		ko.Status.Status = resp.ReplicationGroup.Status
	} else {
		ko.Status.Status = nil
	}
	if resp.ReplicationGroup.TransitEncryptionEnabled != nil {
		ko.Spec.TransitEncryptionEnabled = resp.ReplicationGroup.TransitEncryptionEnabled
	} else {
		ko.Spec.TransitEncryptionEnabled = nil
	}
	if resp.ReplicationGroup.TransitEncryptionMode != "" {
		ko.Spec.TransitEncryptionMode = aws.String(string(resp.ReplicationGroup.TransitEncryptionMode))
	} else {
		ko.Spec.TransitEncryptionMode = nil
	}
	if resp.ReplicationGroup.UserGroupIds != nil {
		ko.Spec.UserGroupIDs = aws.StringSlice(resp.ReplicationGroup.UserGroupIds)
	} else {
		ko.Spec.UserGroupIDs = nil
	}

	rm.setStatusDefaults(ko)
	// custom set output from response
	ko, err = rm.CustomModifyReplicationGroupSetOutput(ctx, desired, resp, ko)
	if err != nil {
		return nil, err
	}
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.ModifyReplicationGroupInput, error) {
	res := &svcsdk.ModifyReplicationGroupInput{}

	res.ApplyImmediately = true
	if r.ko.Spec.AuthToken != nil {
		tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.AuthToken)
		if err != nil {
			return nil, ackrequeue.Needed(err)
		}
		if tmpSecret != "" {
			res.AuthToken = aws.String(tmpSecret)
		}
	}
	if r.ko.Status.AutoMinorVersionUpgrade != nil {
		res.AutoMinorVersionUpgrade = r.ko.Status.AutoMinorVersionUpgrade
	}
	if r.ko.Spec.AutomaticFailoverEnabled != nil {
		res.AutomaticFailoverEnabled = r.ko.Spec.AutomaticFailoverEnabled
	}
	if r.ko.Spec.CacheNodeType != nil {
		res.CacheNodeType = r.ko.Spec.CacheNodeType
	}
	if r.ko.Spec.CacheParameterGroupName != nil {
		res.CacheParameterGroupName = r.ko.Spec.CacheParameterGroupName
	}
	if r.ko.Spec.CacheSecurityGroupNames != nil {
		res.CacheSecurityGroupNames = aws.ToStringSlice(r.ko.Spec.CacheSecurityGroupNames)
	}
	if r.ko.Spec.ClusterMode != nil {
		res.ClusterMode = svcsdktypes.ClusterMode(*r.ko.Spec.ClusterMode)
	}
	if r.ko.Spec.Engine != nil {
		res.Engine = r.ko.Spec.Engine
	}
	if r.ko.Spec.IPDiscovery != nil {
		res.IpDiscovery = svcsdktypes.IpDiscovery(*r.ko.Spec.IPDiscovery)
	}
	if r.ko.Spec.LogDeliveryConfigurations != nil {
		f11 := []svcsdktypes.LogDeliveryConfigurationRequest{}
		for _, f11iter := range r.ko.Spec.LogDeliveryConfigurations {
			f11elem := &svcsdktypes.LogDeliveryConfigurationRequest{}
			if f11iter.DestinationDetails != nil {
				f11elemf0 := &svcsdktypes.DestinationDetails{}
				if f11iter.DestinationDetails.CloudWatchLogsDetails != nil {
					f11elemf0f0 := &svcsdktypes.CloudWatchLogsDestinationDetails{}
					if f11iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
						f11elemf0f0.LogGroup = f11iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
					}
					f11elemf0.CloudWatchLogsDetails = f11elemf0f0
				}
				if f11iter.DestinationDetails.KinesisFirehoseDetails != nil {
					f11elemf0f1 := &svcsdktypes.KinesisFirehoseDestinationDetails{}
					if f11iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
						f11elemf0f1.DeliveryStream = f11iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
					}
					f11elemf0.KinesisFirehoseDetails = f11elemf0f1
				}
				f11elem.DestinationDetails = f11elemf0
			}
			if f11iter.DestinationType != nil {
				f11elem.DestinationType = svcsdktypes.DestinationType(*f11iter.DestinationType)
			}
			if f11iter.Enabled != nil {
				f11elem.Enabled = f11iter.Enabled
			}
			if f11iter.LogFormat != nil {
				f11elem.LogFormat = svcsdktypes.LogFormat(*f11iter.LogFormat)
			}
			if f11iter.LogType != nil {
				f11elem.LogType = svcsdktypes.LogType(*f11iter.LogType)
			}
			f11 = append(f11, *f11elem)
		}
		res.LogDeliveryConfigurations = f11
	}
	if r.ko.Spec.MultiAZEnabled != nil {
		res.MultiAZEnabled = r.ko.Spec.MultiAZEnabled
	}
	if r.ko.Spec.NotificationTopicARN != nil {
		res.NotificationTopicArn = r.ko.Spec.NotificationTopicARN
	}
	if r.ko.Spec.PreferredMaintenanceWindow != nil {
		res.PreferredMaintenanceWindow = r.ko.Spec.PreferredMaintenanceWindow
	}
	if r.ko.Spec.PrimaryClusterID != nil {
		res.PrimaryClusterId = r.ko.Spec.PrimaryClusterID
	}
	if r.ko.Spec.Description != nil {
		res.ReplicationGroupDescription = r.ko.Spec.Description
	}
	if r.ko.Spec.ReplicationGroupID != nil {
		res.ReplicationGroupId = r.ko.Spec.ReplicationGroupID
	}
	if r.ko.Spec.SnapshotRetentionLimit != nil {
		snapshotRetentionLimitCopy0 := *r.ko.Spec.SnapshotRetentionLimit
		if snapshotRetentionLimitCopy0 > math.MaxInt32 || snapshotRetentionLimitCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field SnapshotRetentionLimit is of type int32")
		}
		snapshotRetentionLimitCopy := int32(snapshotRetentionLimitCopy0)
		res.SnapshotRetentionLimit = &snapshotRetentionLimitCopy
	}
	if r.ko.Spec.SnapshotWindow != nil {
		res.SnapshotWindow = r.ko.Spec.SnapshotWindow
	}
	if r.ko.Status.SnapshottingClusterID != nil {
		res.SnapshottingClusterId = r.ko.Status.SnapshottingClusterID
	}
	if r.ko.Spec.TransitEncryptionEnabled != nil {
		res.TransitEncryptionEnabled = r.ko.Spec.TransitEncryptionEnabled
	}
	if r.ko.Spec.TransitEncryptionMode != nil {
		res.TransitEncryptionMode = svcsdktypes.TransitEncryptionMode(*r.ko.Spec.TransitEncryptionMode)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	if isDeleting(r) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource.
		ackcondition.SetSynced(
			r,
			corev1.ConditionFalse,
			&condMsgCurrentlyDeleting,
			nil,
		)
		// Need to return a requeue error here, otherwise:
		// - reconciler.deleteResource() marks the resource unmanaged
		// - reconciler.HandleReconcileError() does not update status for unmanaged resource
		// - reconciler.handleRequeues() is not invoked for delete code path.
		// TODO: return err as nil when reconciler is updated.
		return r, requeueWaitWhileDeleting
	}
	if isModifying(r) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource.
		ackcondition.SetSynced(
			r,
			corev1.ConditionFalse,
			&condMsgNoDeleteWhileModifying,
			nil,
		)
		// Need to return a requeue error here, otherwise:
		// - reconciler.deleteResource() marks the resource unmanaged
		// - reconciler.HandleReconcileError() does not update status for unmanaged resource
		// - reconciler.handleRequeues() is not invoked for delete code path.
		// TODO: return err as nil when reconciler is updated.
		return r, requeueWaitWhileModifying
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteReplicationGroupOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteReplicationGroup(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteReplicationGroup", err)
	// delete call successful
	if err == nil {
		rp, _ := rm.setReplicationGroupOutput(r, resp.ReplicationGroup)
		// Setting resource synced condition to false will trigger a requeue of
		// the resource.
		ackcondition.SetSynced(
			rp,
			corev1.ConditionFalse,
			&condMsgCurrentlyDeleting,
			nil,
		)
		// Need to return a requeue error here, otherwise:
		// - reconciler.deleteResource() marks the resource unmanaged
		// - reconciler.HandleReconcileError() does not update status for unmanaged resource
		// - reconciler.handleRequeues() is not invoked for delete code path.
		// TODO: return err as nil when reconciler is updated.
		return rp, requeueWaitWhileDeleting
	}

	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteReplicationGroupInput, error) {
	res := &svcsdk.DeleteReplicationGroupInput{}

	if r.ko.Spec.ReplicationGroupID != nil {
		res.ReplicationGroupId = r.ko.Spec.ReplicationGroupID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ReplicationGroup,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameter",
		"InvalidParameterValue",
		"InvalidParameterCombination",
		"InsufficientCacheClusterCapacity",
		"ClusterQuotaForCustomerExceeded",
		"NodeQuotaForClusterExceeded",
		"NodeQuotaForCustomerExceeded",
		"InvalidVPCNetworkStateFault",
		"TagQuotaPerResourceExceeded",
		"NodeGroupsPerReplicationGroupQuotaExceeded",
		"InvalidCacheSecurityGroupState",
		"InvalidKMSKeyFault":
		return true
	default:
		return false
	}
}

// This method copies the data from given ReplicationGroup by populating it
// into copy of supplied resource and returns that.
func (rm *resourceManager) setReplicationGroupOutput(
	r *resource,
	obj *svcsdk.ReplicationGroup,
) (*resource, error) {
	if obj == nil ||
		r == nil ||
		r.ko == nil {
		return nil, nil
	}
	resp := &svcsdk.CreateReplicationGroupOutput{ReplicationGroup: obj}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ReplicationGroup.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ReplicationGroup.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ReplicationGroup.AtRestEncryptionEnabled != nil {
		ko.Spec.AtRestEncryptionEnabled = resp.ReplicationGroup.AtRestEncryptionEnabled
	} else {
		ko.Spec.AtRestEncryptionEnabled = nil
	}
	if resp.ReplicationGroup.AuthTokenEnabled != nil {
		ko.Status.AuthTokenEnabled = resp.ReplicationGroup.AuthTokenEnabled
	} else {
		ko.Status.AuthTokenEnabled = nil
	}
	if resp.ReplicationGroup.AuthTokenLastModifiedDate != nil {
		ko.Status.AuthTokenLastModifiedDate = &metav1.Time{*resp.ReplicationGroup.AuthTokenLastModifiedDate}
	} else {
		ko.Status.AuthTokenLastModifiedDate = nil
	}
	if resp.ReplicationGroup.AutoMinorVersionUpgrade != nil {
		ko.Status.AutoMinorVersionUpgrade = resp.ReplicationGroup.AutoMinorVersionUpgrade
	} else {
		ko.Status.AutoMinorVersionUpgrade = nil
	}
	if resp.ReplicationGroup.AutomaticFailover != "" {
		ko.Status.AutomaticFailover = aws.String(string(resp.ReplicationGroup.AutomaticFailover))
	} else {
		ko.Status.AutomaticFailover = nil
	}
	if resp.ReplicationGroup.CacheNodeType != nil {
		ko.Spec.CacheNodeType = resp.ReplicationGroup.CacheNodeType
	} else {
		ko.Spec.CacheNodeType = nil
	}
	if resp.ReplicationGroup.ClusterEnabled != nil {
		ko.Status.ClusterEnabled = resp.ReplicationGroup.ClusterEnabled
	} else {
		ko.Status.ClusterEnabled = nil
	}
	if resp.ReplicationGroup.ClusterMode != "" {
		ko.Spec.ClusterMode = aws.String(string(resp.ReplicationGroup.ClusterMode))
	} else {
		ko.Spec.ClusterMode = nil
	}
	if resp.ReplicationGroup.ConfigurationEndpoint != nil {
		f9 := &svcapitypes.Endpoint{}
		if resp.ReplicationGroup.ConfigurationEndpoint.Address != nil {
			f9.Address = resp.ReplicationGroup.ConfigurationEndpoint.Address
		}
		if resp.ReplicationGroup.ConfigurationEndpoint.Port != nil {
			portCopy := int64(*resp.ReplicationGroup.ConfigurationEndpoint.Port)
			f9.Port = &portCopy
		}
		ko.Status.ConfigurationEndpoint = f9
	} else {
		ko.Status.ConfigurationEndpoint = nil
	}
	if resp.ReplicationGroup.DataTiering != "" {
		ko.Status.DataTiering = aws.String(string(resp.ReplicationGroup.DataTiering))
	} else {
		ko.Status.DataTiering = nil
	}
	if resp.ReplicationGroup.Description != nil {
		ko.Spec.Description = resp.ReplicationGroup.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.ReplicationGroup.Engine != nil {
		ko.Spec.Engine = resp.ReplicationGroup.Engine
	} else {
		ko.Spec.Engine = nil
	}
	if resp.ReplicationGroup.GlobalReplicationGroupInfo != nil {
		f13 := &svcapitypes.GlobalReplicationGroupInfo{}
		if resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupId != nil {
			f13.GlobalReplicationGroupID = resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupId
		}
		if resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole != nil {
			f13.GlobalReplicationGroupMemberRole = resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole
		}
		ko.Status.GlobalReplicationGroupInfo = f13
	} else {
		ko.Status.GlobalReplicationGroupInfo = nil
	}
	if resp.ReplicationGroup.IpDiscovery != "" {
		ko.Spec.IPDiscovery = aws.String(string(resp.ReplicationGroup.IpDiscovery))
	} else {
		ko.Spec.IPDiscovery = nil
	}
	if resp.ReplicationGroup.KmsKeyId != nil {
		ko.Spec.KMSKeyID = resp.ReplicationGroup.KmsKeyId
	} else {
		ko.Spec.KMSKeyID = nil
	}
	if resp.ReplicationGroup.LogDeliveryConfigurations != nil {
		f16 := []*svcapitypes.LogDeliveryConfigurationRequest{}
		for _, f16iter := range resp.ReplicationGroup.LogDeliveryConfigurations {
			f16elem := &svcapitypes.LogDeliveryConfigurationRequest{}
			if f16iter.DestinationDetails != nil {
				f16elemf0 := &svcapitypes.DestinationDetails{}
				if f16iter.DestinationDetails.CloudWatchLogsDetails != nil {
					f16elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
					if f16iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
						f16elemf0f0.LogGroup = f16iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
					}
					f16elemf0.CloudWatchLogsDetails = f16elemf0f0
				}
				if f16iter.DestinationDetails.KinesisFirehoseDetails != nil {
					f16elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
					if f16iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
						f16elemf0f1.DeliveryStream = f16iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
					}
					f16elemf0.KinesisFirehoseDetails = f16elemf0f1
				}
				f16elem.DestinationDetails = f16elemf0
			}
			if f16iter.DestinationType != "" {
				f16elem.DestinationType = aws.String(string(f16iter.DestinationType))
			}
			if f16iter.LogFormat != "" {
				f16elem.LogFormat = aws.String(string(f16iter.LogFormat))
			}
			if f16iter.LogType != "" {
				f16elem.LogType = aws.String(string(f16iter.LogType))
			}
			f16 = append(f16, f16elem)
		}
		ko.Spec.LogDeliveryConfigurations = f16
	} else {
		ko.Spec.LogDeliveryConfigurations = nil
	}
	if resp.ReplicationGroup.MemberClusters != nil {
		ko.Status.MemberClusters = aws.StringSlice(resp.ReplicationGroup.MemberClusters)
	} else {
		ko.Status.MemberClusters = nil
	}
	if resp.ReplicationGroup.MemberClustersOutpostArns != nil {
		ko.Status.MemberClustersOutpostARNs = aws.StringSlice(resp.ReplicationGroup.MemberClustersOutpostArns)
	} else {
		ko.Status.MemberClustersOutpostARNs = nil
	}
	if resp.ReplicationGroup.MultiAZ != "" {
		ko.Status.MultiAZ = aws.String(string(resp.ReplicationGroup.MultiAZ))
	} else {
		ko.Status.MultiAZ = nil
	}
	if resp.ReplicationGroup.NetworkType != "" {
		ko.Spec.NetworkType = aws.String(string(resp.ReplicationGroup.NetworkType))
	} else {
		ko.Spec.NetworkType = nil
	}
	if resp.ReplicationGroup.NodeGroups != nil {
		f21 := []*svcapitypes.NodeGroup{}
		for _, f21iter := range resp.ReplicationGroup.NodeGroups {
			f21elem := &svcapitypes.NodeGroup{}
			if f21iter.NodeGroupId != nil {
				f21elem.NodeGroupID = f21iter.NodeGroupId
			}
			if f21iter.NodeGroupMembers != nil {
				f21elemf1 := []*svcapitypes.NodeGroupMember{}
				for _, f21elemf1iter := range f21iter.NodeGroupMembers {
					f21elemf1elem := &svcapitypes.NodeGroupMember{}
					if f21elemf1iter.CacheClusterId != nil {
						f21elemf1elem.CacheClusterID = f21elemf1iter.CacheClusterId
					}
					if f21elemf1iter.CacheNodeId != nil {
						f21elemf1elem.CacheNodeID = f21elemf1iter.CacheNodeId
					}
					if f21elemf1iter.CurrentRole != nil {
						f21elemf1elem.CurrentRole = f21elemf1iter.CurrentRole
					}
					if f21elemf1iter.PreferredAvailabilityZone != nil {
						f21elemf1elem.PreferredAvailabilityZone = f21elemf1iter.PreferredAvailabilityZone
					}
					if f21elemf1iter.PreferredOutpostArn != nil {
						f21elemf1elem.PreferredOutpostARN = f21elemf1iter.PreferredOutpostArn
					}
					if f21elemf1iter.ReadEndpoint != nil {
						f21elemf1elemf5 := &svcapitypes.Endpoint{}
						if f21elemf1iter.ReadEndpoint.Address != nil {
							f21elemf1elemf5.Address = f21elemf1iter.ReadEndpoint.Address
						}
						if f21elemf1iter.ReadEndpoint.Port != nil {
							portCopy := int64(*f21elemf1iter.ReadEndpoint.Port)
							f21elemf1elemf5.Port = &portCopy
						}
						f21elemf1elem.ReadEndpoint = f21elemf1elemf5
					}
					f21elemf1 = append(f21elemf1, f21elemf1elem)
				}
				f21elem.NodeGroupMembers = f21elemf1
			}
			if f21iter.PrimaryEndpoint != nil {
				f21elemf2 := &svcapitypes.Endpoint{}
				if f21iter.PrimaryEndpoint.Address != nil {
					f21elemf2.Address = f21iter.PrimaryEndpoint.Address
				}
				if f21iter.PrimaryEndpoint.Port != nil {
					portCopy := int64(*f21iter.PrimaryEndpoint.Port)
					f21elemf2.Port = &portCopy
				}
				f21elem.PrimaryEndpoint = f21elemf2
			}
			if f21iter.ReaderEndpoint != nil {
				f21elemf3 := &svcapitypes.Endpoint{}
				if f21iter.ReaderEndpoint.Address != nil {
					f21elemf3.Address = f21iter.ReaderEndpoint.Address
				}
				if f21iter.ReaderEndpoint.Port != nil {
					portCopy := int64(*f21iter.ReaderEndpoint.Port)
					f21elemf3.Port = &portCopy
				}
				f21elem.ReaderEndpoint = f21elemf3
			}
			if f21iter.Slots != nil {
				f21elem.Slots = f21iter.Slots
			}
			if f21iter.Status != nil {
				f21elem.Status = f21iter.Status
			}
			f21 = append(f21, f21elem)
		}
		ko.Status.NodeGroups = f21
	} else {
		ko.Status.NodeGroups = nil
	}
	if resp.ReplicationGroup.PendingModifiedValues != nil {
		f22 := &svcapitypes.ReplicationGroupPendingModifiedValues{}
		if resp.ReplicationGroup.PendingModifiedValues.AuthTokenStatus != "" {
			f22.AuthTokenStatus = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.AuthTokenStatus))
		}
		if resp.ReplicationGroup.PendingModifiedValues.AutomaticFailoverStatus != "" {
			f22.AutomaticFailoverStatus = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.AutomaticFailoverStatus))
		}
		if resp.ReplicationGroup.PendingModifiedValues.ClusterMode != "" {
			f22.ClusterMode = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.ClusterMode))
		}
		if resp.ReplicationGroup.PendingModifiedValues.LogDeliveryConfigurations != nil {
			f22f3 := []*svcapitypes.PendingLogDeliveryConfiguration{}
			for _, f22f3iter := range resp.ReplicationGroup.PendingModifiedValues.LogDeliveryConfigurations {
				f22f3elem := &svcapitypes.PendingLogDeliveryConfiguration{}
				if f22f3iter.DestinationDetails != nil {
					f22f3elemf0 := &svcapitypes.DestinationDetails{}
					if f22f3iter.DestinationDetails.CloudWatchLogsDetails != nil {
						f22f3elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
						if f22f3iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
							f22f3elemf0f0.LogGroup = f22f3iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
						}
						f22f3elemf0.CloudWatchLogsDetails = f22f3elemf0f0
					}
					if f22f3iter.DestinationDetails.KinesisFirehoseDetails != nil {
						f22f3elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
						if f22f3iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
							f22f3elemf0f1.DeliveryStream = f22f3iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
						}
						f22f3elemf0.KinesisFirehoseDetails = f22f3elemf0f1
					}
					f22f3elem.DestinationDetails = f22f3elemf0
				}
				if f22f3iter.DestinationType != "" {
					f22f3elem.DestinationType = aws.String(string(f22f3iter.DestinationType))
				}
				if f22f3iter.LogFormat != "" {
					f22f3elem.LogFormat = aws.String(string(f22f3iter.LogFormat))
				}
				if f22f3iter.LogType != "" {
					f22f3elem.LogType = aws.String(string(f22f3iter.LogType))
				}
				f22f3 = append(f22f3, f22f3elem)
			}
			f22.LogDeliveryConfigurations = f22f3
		}
		if resp.ReplicationGroup.PendingModifiedValues.PrimaryClusterId != nil {
			f22.PrimaryClusterID = resp.ReplicationGroup.PendingModifiedValues.PrimaryClusterId
		}
		if resp.ReplicationGroup.PendingModifiedValues.Resharding != nil {
			f22f5 := &svcapitypes.ReshardingStatus{}
			if resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration != nil {
				f22f5f0 := &svcapitypes.SlotMigration{}
				if resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage != nil {
					f22f5f0.ProgressPercentage = resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage
				}
				f22f5.SlotMigration = f22f5f0
			}
			f22.Resharding = f22f5
		}
		if resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionEnabled != nil {
			f22.TransitEncryptionEnabled = resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionEnabled
		}
		if resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionMode != "" {
			f22.TransitEncryptionMode = aws.String(string(resp.ReplicationGroup.PendingModifiedValues.TransitEncryptionMode))
		}
		if resp.ReplicationGroup.PendingModifiedValues.UserGroups != nil {
			f22f8 := &svcapitypes.UserGroupsUpdateStatus{}
			if resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToAdd != nil {
				f22f8.UserGroupIDsToAdd = aws.StringSlice(resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToAdd)
			}
			if resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToRemove != nil {
				f22f8.UserGroupIDsToRemove = aws.StringSlice(resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToRemove)
			}
			f22.UserGroups = f22f8
		}
		ko.Status.PendingModifiedValues = f22
	} else {
		ko.Status.PendingModifiedValues = nil
	}
	if resp.ReplicationGroup.ReplicationGroupCreateTime != nil {
		ko.Status.ReplicationGroupCreateTime = &metav1.Time{*resp.ReplicationGroup.ReplicationGroupCreateTime}
	} else {
		ko.Status.ReplicationGroupCreateTime = nil
	}
	if resp.ReplicationGroup.ReplicationGroupId != nil {
		ko.Spec.ReplicationGroupID = resp.ReplicationGroup.ReplicationGroupId
	} else {
		ko.Spec.ReplicationGroupID = nil
	}
	if resp.ReplicationGroup.SnapshotRetentionLimit != nil {
		snapshotRetentionLimitCopy := int64(*resp.ReplicationGroup.SnapshotRetentionLimit)
		ko.Spec.SnapshotRetentionLimit = &snapshotRetentionLimitCopy
	} else {
		ko.Spec.SnapshotRetentionLimit = nil
	}
	if resp.ReplicationGroup.SnapshotWindow != nil {
		ko.Spec.SnapshotWindow = resp.ReplicationGroup.SnapshotWindow
	} else {
		ko.Spec.SnapshotWindow = nil
	}
	if resp.ReplicationGroup.SnapshottingClusterId != nil {
		ko.Status.SnapshottingClusterID = resp.ReplicationGroup.SnapshottingClusterId
	} else {
		ko.Status.SnapshottingClusterID = nil
	}
	if resp.ReplicationGroup.Status != nil {
		ko.Status.Status = resp.ReplicationGroup.Status
	} else {
		ko.Status.Status = nil
	}
	if resp.ReplicationGroup.TransitEncryptionEnabled != nil {
		ko.Spec.TransitEncryptionEnabled = resp.ReplicationGroup.TransitEncryptionEnabled
	} else {
		ko.Spec.TransitEncryptionEnabled = nil
	}
	if resp.ReplicationGroup.TransitEncryptionMode != "" {
		ko.Spec.TransitEncryptionMode = aws.String(string(resp.ReplicationGroup.TransitEncryptionMode))
	} else {
		ko.Spec.TransitEncryptionMode = nil
	}
	if resp.ReplicationGroup.UserGroupIds != nil {
		ko.Spec.UserGroupIDs = aws.StringSlice(resp.ReplicationGroup.UserGroupIds)
	} else {
		ko.Spec.UserGroupIDs = nil
	}

	rm.setStatusDefaults(ko)
	rm.customSetOutput(obj, ko) // custom set output from obj
	return &resource{ko}, nil
}
