// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package replication_group

import (
	"context"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/elasticache"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/elasticache-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.ElastiCache{}
	_ = &svcapitypes.ReplicationGroup{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer exit(err)
	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeReplicationGroupsOutput
	resp, err = rm.sdkapi.DescribeReplicationGroupsWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeReplicationGroups", err)
	if err != nil {
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "ReplicationGroupNotFoundFault" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.ReplicationGroups {
		if elem.ARN != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ARN)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.AtRestEncryptionEnabled != nil {
			ko.Spec.AtRestEncryptionEnabled = elem.AtRestEncryptionEnabled
		} else {
			ko.Spec.AtRestEncryptionEnabled = nil
		}
		if elem.AuthTokenEnabled != nil {
			ko.Status.AuthTokenEnabled = elem.AuthTokenEnabled
		} else {
			ko.Status.AuthTokenEnabled = nil
		}
		if elem.AuthTokenLastModifiedDate != nil {
			ko.Status.AuthTokenLastModifiedDate = &metav1.Time{*elem.AuthTokenLastModifiedDate}
		} else {
			ko.Status.AuthTokenLastModifiedDate = nil
		}
		if elem.AutomaticFailover != nil {
			ko.Status.AutomaticFailover = elem.AutomaticFailover
		} else {
			ko.Status.AutomaticFailover = nil
		}
		if elem.CacheNodeType != nil {
			ko.Spec.CacheNodeType = elem.CacheNodeType
		} else {
			ko.Spec.CacheNodeType = nil
		}
		if elem.ClusterEnabled != nil {
			ko.Status.ClusterEnabled = elem.ClusterEnabled
		} else {
			ko.Status.ClusterEnabled = nil
		}
		if elem.ConfigurationEndpoint != nil {
			f7 := &svcapitypes.Endpoint{}
			if elem.ConfigurationEndpoint.Address != nil {
				f7.Address = elem.ConfigurationEndpoint.Address
			}
			if elem.ConfigurationEndpoint.Port != nil {
				f7.Port = elem.ConfigurationEndpoint.Port
			}
			ko.Status.ConfigurationEndpoint = f7
		} else {
			ko.Status.ConfigurationEndpoint = nil
		}
		if elem.Description != nil {
			ko.Status.Description = elem.Description
		} else {
			ko.Status.Description = nil
		}
		if elem.GlobalReplicationGroupInfo != nil {
			f9 := &svcapitypes.GlobalReplicationGroupInfo{}
			if elem.GlobalReplicationGroupInfo.GlobalReplicationGroupId != nil {
				f9.GlobalReplicationGroupID = elem.GlobalReplicationGroupInfo.GlobalReplicationGroupId
			}
			if elem.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole != nil {
				f9.GlobalReplicationGroupMemberRole = elem.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole
			}
			ko.Status.GlobalReplicationGroupInfo = f9
		} else {
			ko.Status.GlobalReplicationGroupInfo = nil
		}
		if elem.KmsKeyId != nil {
			ko.Spec.KMSKeyID = elem.KmsKeyId
		} else {
			ko.Spec.KMSKeyID = nil
		}
		if elem.LogDeliveryConfigurations != nil {
			f11 := []*svcapitypes.LogDeliveryConfigurationRequest{}
			for _, f11iter := range elem.LogDeliveryConfigurations {
				f11elem := &svcapitypes.LogDeliveryConfigurationRequest{}
				if f11iter.DestinationDetails != nil {
					f11elemf0 := &svcapitypes.DestinationDetails{}
					if f11iter.DestinationDetails.CloudWatchLogsDetails != nil {
						f11elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
						if f11iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
							f11elemf0f0.LogGroup = f11iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
						}
						f11elemf0.CloudWatchLogsDetails = f11elemf0f0
					}
					if f11iter.DestinationDetails.KinesisFirehoseDetails != nil {
						f11elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
						if f11iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
							f11elemf0f1.DeliveryStream = f11iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
						}
						f11elemf0.KinesisFirehoseDetails = f11elemf0f1
					}
					f11elem.DestinationDetails = f11elemf0
				}
				if f11iter.DestinationType != nil {
					f11elem.DestinationType = f11iter.DestinationType
				}
				if f11iter.LogFormat != nil {
					f11elem.LogFormat = f11iter.LogFormat
				}
				if f11iter.LogType != nil {
					f11elem.LogType = f11iter.LogType
				}
				f11 = append(f11, f11elem)
			}
			ko.Spec.LogDeliveryConfigurations = f11
		} else {
			ko.Spec.LogDeliveryConfigurations = nil
		}
		if elem.MemberClusters != nil {
			f12 := []*string{}
			for _, f12iter := range elem.MemberClusters {
				var f12elem string
				f12elem = *f12iter
				f12 = append(f12, &f12elem)
			}
			ko.Status.MemberClusters = f12
		} else {
			ko.Status.MemberClusters = nil
		}
		if elem.MemberClustersOutpostArns != nil {
			f13 := []*string{}
			for _, f13iter := range elem.MemberClustersOutpostArns {
				var f13elem string
				f13elem = *f13iter
				f13 = append(f13, &f13elem)
			}
			ko.Status.MemberClustersOutpostARNs = f13
		} else {
			ko.Status.MemberClustersOutpostARNs = nil
		}
		if elem.MultiAZ != nil {
			ko.Status.MultiAZ = elem.MultiAZ
		} else {
			ko.Status.MultiAZ = nil
		}
		if elem.NodeGroups != nil {
			f15 := []*svcapitypes.NodeGroup{}
			for _, f15iter := range elem.NodeGroups {
				f15elem := &svcapitypes.NodeGroup{}
				if f15iter.NodeGroupId != nil {
					f15elem.NodeGroupID = f15iter.NodeGroupId
				}
				if f15iter.NodeGroupMembers != nil {
					f15elemf1 := []*svcapitypes.NodeGroupMember{}
					for _, f15elemf1iter := range f15iter.NodeGroupMembers {
						f15elemf1elem := &svcapitypes.NodeGroupMember{}
						if f15elemf1iter.CacheClusterId != nil {
							f15elemf1elem.CacheClusterID = f15elemf1iter.CacheClusterId
						}
						if f15elemf1iter.CacheNodeId != nil {
							f15elemf1elem.CacheNodeID = f15elemf1iter.CacheNodeId
						}
						if f15elemf1iter.CurrentRole != nil {
							f15elemf1elem.CurrentRole = f15elemf1iter.CurrentRole
						}
						if f15elemf1iter.PreferredAvailabilityZone != nil {
							f15elemf1elem.PreferredAvailabilityZone = f15elemf1iter.PreferredAvailabilityZone
						}
						if f15elemf1iter.PreferredOutpostArn != nil {
							f15elemf1elem.PreferredOutpostARN = f15elemf1iter.PreferredOutpostArn
						}
						if f15elemf1iter.ReadEndpoint != nil {
							f15elemf1elemf5 := &svcapitypes.Endpoint{}
							if f15elemf1iter.ReadEndpoint.Address != nil {
								f15elemf1elemf5.Address = f15elemf1iter.ReadEndpoint.Address
							}
							if f15elemf1iter.ReadEndpoint.Port != nil {
								f15elemf1elemf5.Port = f15elemf1iter.ReadEndpoint.Port
							}
							f15elemf1elem.ReadEndpoint = f15elemf1elemf5
						}
						f15elemf1 = append(f15elemf1, f15elemf1elem)
					}
					f15elem.NodeGroupMembers = f15elemf1
				}
				if f15iter.PrimaryEndpoint != nil {
					f15elemf2 := &svcapitypes.Endpoint{}
					if f15iter.PrimaryEndpoint.Address != nil {
						f15elemf2.Address = f15iter.PrimaryEndpoint.Address
					}
					if f15iter.PrimaryEndpoint.Port != nil {
						f15elemf2.Port = f15iter.PrimaryEndpoint.Port
					}
					f15elem.PrimaryEndpoint = f15elemf2
				}
				if f15iter.ReaderEndpoint != nil {
					f15elemf3 := &svcapitypes.Endpoint{}
					if f15iter.ReaderEndpoint.Address != nil {
						f15elemf3.Address = f15iter.ReaderEndpoint.Address
					}
					if f15iter.ReaderEndpoint.Port != nil {
						f15elemf3.Port = f15iter.ReaderEndpoint.Port
					}
					f15elem.ReaderEndpoint = f15elemf3
				}
				if f15iter.Slots != nil {
					f15elem.Slots = f15iter.Slots
				}
				if f15iter.Status != nil {
					f15elem.Status = f15iter.Status
				}
				f15 = append(f15, f15elem)
			}
			ko.Status.NodeGroups = f15
		} else {
			ko.Status.NodeGroups = nil
		}
		if elem.PendingModifiedValues != nil {
			f16 := &svcapitypes.ReplicationGroupPendingModifiedValues{}
			if elem.PendingModifiedValues.AuthTokenStatus != nil {
				f16.AuthTokenStatus = elem.PendingModifiedValues.AuthTokenStatus
			}
			if elem.PendingModifiedValues.AutomaticFailoverStatus != nil {
				f16.AutomaticFailoverStatus = elem.PendingModifiedValues.AutomaticFailoverStatus
			}
			if elem.PendingModifiedValues.LogDeliveryConfigurations != nil {
				f16f2 := []*svcapitypes.PendingLogDeliveryConfiguration{}
				for _, f16f2iter := range elem.PendingModifiedValues.LogDeliveryConfigurations {
					f16f2elem := &svcapitypes.PendingLogDeliveryConfiguration{}
					if f16f2iter.DestinationDetails != nil {
						f16f2elemf0 := &svcapitypes.DestinationDetails{}
						if f16f2iter.DestinationDetails.CloudWatchLogsDetails != nil {
							f16f2elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
							if f16f2iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
								f16f2elemf0f0.LogGroup = f16f2iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
							}
							f16f2elemf0.CloudWatchLogsDetails = f16f2elemf0f0
						}
						if f16f2iter.DestinationDetails.KinesisFirehoseDetails != nil {
							f16f2elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
							if f16f2iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
								f16f2elemf0f1.DeliveryStream = f16f2iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
							}
							f16f2elemf0.KinesisFirehoseDetails = f16f2elemf0f1
						}
						f16f2elem.DestinationDetails = f16f2elemf0
					}
					if f16f2iter.DestinationType != nil {
						f16f2elem.DestinationType = f16f2iter.DestinationType
					}
					if f16f2iter.LogFormat != nil {
						f16f2elem.LogFormat = f16f2iter.LogFormat
					}
					if f16f2iter.LogType != nil {
						f16f2elem.LogType = f16f2iter.LogType
					}
					f16f2 = append(f16f2, f16f2elem)
				}
				f16.LogDeliveryConfigurations = f16f2
			}
			if elem.PendingModifiedValues.PrimaryClusterId != nil {
				f16.PrimaryClusterID = elem.PendingModifiedValues.PrimaryClusterId
			}
			if elem.PendingModifiedValues.Resharding != nil {
				f16f4 := &svcapitypes.ReshardingStatus{}
				if elem.PendingModifiedValues.Resharding.SlotMigration != nil {
					f16f4f0 := &svcapitypes.SlotMigration{}
					if elem.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage != nil {
						f16f4f0.ProgressPercentage = elem.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage
					}
					f16f4.SlotMigration = f16f4f0
				}
				f16.Resharding = f16f4
			}
			if elem.PendingModifiedValues.UserGroups != nil {
				f16f5 := &svcapitypes.UserGroupsUpdateStatus{}
				if elem.PendingModifiedValues.UserGroups.UserGroupIdsToAdd != nil {
					f16f5f0 := []*string{}
					for _, f16f5f0iter := range elem.PendingModifiedValues.UserGroups.UserGroupIdsToAdd {
						var f16f5f0elem string
						f16f5f0elem = *f16f5f0iter
						f16f5f0 = append(f16f5f0, &f16f5f0elem)
					}
					f16f5.UserGroupIDsToAdd = f16f5f0
				}
				if elem.PendingModifiedValues.UserGroups.UserGroupIdsToRemove != nil {
					f16f5f1 := []*string{}
					for _, f16f5f1iter := range elem.PendingModifiedValues.UserGroups.UserGroupIdsToRemove {
						var f16f5f1elem string
						f16f5f1elem = *f16f5f1iter
						f16f5f1 = append(f16f5f1, &f16f5f1elem)
					}
					f16f5.UserGroupIDsToRemove = f16f5f1
				}
				f16.UserGroups = f16f5
			}
			ko.Status.PendingModifiedValues = f16
		} else {
			ko.Status.PendingModifiedValues = nil
		}
		if elem.ReplicationGroupId != nil {
			ko.Spec.ReplicationGroupID = elem.ReplicationGroupId
		} else {
			ko.Spec.ReplicationGroupID = nil
		}
		if elem.SnapshotRetentionLimit != nil {
			ko.Spec.SnapshotRetentionLimit = elem.SnapshotRetentionLimit
		} else {
			ko.Spec.SnapshotRetentionLimit = nil
		}
		if elem.SnapshotWindow != nil {
			ko.Spec.SnapshotWindow = elem.SnapshotWindow
		} else {
			ko.Spec.SnapshotWindow = nil
		}
		if elem.SnapshottingClusterId != nil {
			ko.Status.SnapshottingClusterID = elem.SnapshottingClusterId
		} else {
			ko.Status.SnapshottingClusterID = nil
		}
		if elem.Status != nil {
			ko.Status.Status = elem.Status
		} else {
			ko.Status.Status = nil
		}
		if elem.TransitEncryptionEnabled != nil {
			ko.Spec.TransitEncryptionEnabled = elem.TransitEncryptionEnabled
		} else {
			ko.Spec.TransitEncryptionEnabled = nil
		}
		if elem.UserGroupIds != nil {
			f23 := []*string{}
			for _, f23iter := range elem.UserGroupIds {
				var f23elem string
				f23elem = *f23iter
				f23 = append(f23, &f23elem)
			}
			ko.Spec.UserGroupIDs = f23
		} else {
			ko.Spec.UserGroupIDs = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	// custom set output from response
	ko, err = rm.CustomDescribeReplicationGroupsSetOutput(ctx, r, resp, ko)
	if err != nil {
		return nil, err
	}
	rm.updateSpecFields(ctx, resp.ReplicationGroups[0], &resource{ko})
	return &resource{ko}, nil
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeReplicationGroupsInput, error) {
	res := &svcsdk.DescribeReplicationGroupsInput{}

	if r.ko.Spec.ReplicationGroupID != nil {
		res.SetReplicationGroupId(*r.ko.Spec.ReplicationGroupID)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer exit(err)
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateReplicationGroupOutput
	_ = resp
	resp, err = rm.sdkapi.CreateReplicationGroupWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateReplicationGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ReplicationGroup.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ReplicationGroup.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ReplicationGroup.AuthTokenEnabled != nil {
		ko.Status.AuthTokenEnabled = resp.ReplicationGroup.AuthTokenEnabled
	} else {
		ko.Status.AuthTokenEnabled = nil
	}
	if resp.ReplicationGroup.AuthTokenLastModifiedDate != nil {
		ko.Status.AuthTokenLastModifiedDate = &metav1.Time{*resp.ReplicationGroup.AuthTokenLastModifiedDate}
	} else {
		ko.Status.AuthTokenLastModifiedDate = nil
	}
	if resp.ReplicationGroup.AutomaticFailover != nil {
		ko.Status.AutomaticFailover = resp.ReplicationGroup.AutomaticFailover
	} else {
		ko.Status.AutomaticFailover = nil
	}
	if resp.ReplicationGroup.ClusterEnabled != nil {
		ko.Status.ClusterEnabled = resp.ReplicationGroup.ClusterEnabled
	} else {
		ko.Status.ClusterEnabled = nil
	}
	if resp.ReplicationGroup.ConfigurationEndpoint != nil {
		f7 := &svcapitypes.Endpoint{}
		if resp.ReplicationGroup.ConfigurationEndpoint.Address != nil {
			f7.Address = resp.ReplicationGroup.ConfigurationEndpoint.Address
		}
		if resp.ReplicationGroup.ConfigurationEndpoint.Port != nil {
			f7.Port = resp.ReplicationGroup.ConfigurationEndpoint.Port
		}
		ko.Status.ConfigurationEndpoint = f7
	} else {
		ko.Status.ConfigurationEndpoint = nil
	}
	if resp.ReplicationGroup.Description != nil {
		ko.Status.Description = resp.ReplicationGroup.Description
	} else {
		ko.Status.Description = nil
	}
	if resp.ReplicationGroup.GlobalReplicationGroupInfo != nil {
		f9 := &svcapitypes.GlobalReplicationGroupInfo{}
		if resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupId != nil {
			f9.GlobalReplicationGroupID = resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupId
		}
		if resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole != nil {
			f9.GlobalReplicationGroupMemberRole = resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole
		}
		ko.Status.GlobalReplicationGroupInfo = f9
	} else {
		ko.Status.GlobalReplicationGroupInfo = nil
	}
	if resp.ReplicationGroup.MemberClusters != nil {
		f12 := []*string{}
		for _, f12iter := range resp.ReplicationGroup.MemberClusters {
			var f12elem string
			f12elem = *f12iter
			f12 = append(f12, &f12elem)
		}
		ko.Status.MemberClusters = f12
	} else {
		ko.Status.MemberClusters = nil
	}
	if resp.ReplicationGroup.MemberClustersOutpostArns != nil {
		f13 := []*string{}
		for _, f13iter := range resp.ReplicationGroup.MemberClustersOutpostArns {
			var f13elem string
			f13elem = *f13iter
			f13 = append(f13, &f13elem)
		}
		ko.Status.MemberClustersOutpostARNs = f13
	} else {
		ko.Status.MemberClustersOutpostARNs = nil
	}
	if resp.ReplicationGroup.MultiAZ != nil {
		ko.Status.MultiAZ = resp.ReplicationGroup.MultiAZ
	} else {
		ko.Status.MultiAZ = nil
	}
	if resp.ReplicationGroup.NodeGroups != nil {
		f15 := []*svcapitypes.NodeGroup{}
		for _, f15iter := range resp.ReplicationGroup.NodeGroups {
			f15elem := &svcapitypes.NodeGroup{}
			if f15iter.NodeGroupId != nil {
				f15elem.NodeGroupID = f15iter.NodeGroupId
			}
			if f15iter.NodeGroupMembers != nil {
				f15elemf1 := []*svcapitypes.NodeGroupMember{}
				for _, f15elemf1iter := range f15iter.NodeGroupMembers {
					f15elemf1elem := &svcapitypes.NodeGroupMember{}
					if f15elemf1iter.CacheClusterId != nil {
						f15elemf1elem.CacheClusterID = f15elemf1iter.CacheClusterId
					}
					if f15elemf1iter.CacheNodeId != nil {
						f15elemf1elem.CacheNodeID = f15elemf1iter.CacheNodeId
					}
					if f15elemf1iter.CurrentRole != nil {
						f15elemf1elem.CurrentRole = f15elemf1iter.CurrentRole
					}
					if f15elemf1iter.PreferredAvailabilityZone != nil {
						f15elemf1elem.PreferredAvailabilityZone = f15elemf1iter.PreferredAvailabilityZone
					}
					if f15elemf1iter.PreferredOutpostArn != nil {
						f15elemf1elem.PreferredOutpostARN = f15elemf1iter.PreferredOutpostArn
					}
					if f15elemf1iter.ReadEndpoint != nil {
						f15elemf1elemf5 := &svcapitypes.Endpoint{}
						if f15elemf1iter.ReadEndpoint.Address != nil {
							f15elemf1elemf5.Address = f15elemf1iter.ReadEndpoint.Address
						}
						if f15elemf1iter.ReadEndpoint.Port != nil {
							f15elemf1elemf5.Port = f15elemf1iter.ReadEndpoint.Port
						}
						f15elemf1elem.ReadEndpoint = f15elemf1elemf5
					}
					f15elemf1 = append(f15elemf1, f15elemf1elem)
				}
				f15elem.NodeGroupMembers = f15elemf1
			}
			if f15iter.PrimaryEndpoint != nil {
				f15elemf2 := &svcapitypes.Endpoint{}
				if f15iter.PrimaryEndpoint.Address != nil {
					f15elemf2.Address = f15iter.PrimaryEndpoint.Address
				}
				if f15iter.PrimaryEndpoint.Port != nil {
					f15elemf2.Port = f15iter.PrimaryEndpoint.Port
				}
				f15elem.PrimaryEndpoint = f15elemf2
			}
			if f15iter.ReaderEndpoint != nil {
				f15elemf3 := &svcapitypes.Endpoint{}
				if f15iter.ReaderEndpoint.Address != nil {
					f15elemf3.Address = f15iter.ReaderEndpoint.Address
				}
				if f15iter.ReaderEndpoint.Port != nil {
					f15elemf3.Port = f15iter.ReaderEndpoint.Port
				}
				f15elem.ReaderEndpoint = f15elemf3
			}
			if f15iter.Slots != nil {
				f15elem.Slots = f15iter.Slots
			}
			if f15iter.Status != nil {
				f15elem.Status = f15iter.Status
			}
			f15 = append(f15, f15elem)
		}
		ko.Status.NodeGroups = f15
	} else {
		ko.Status.NodeGroups = nil
	}
	if resp.ReplicationGroup.PendingModifiedValues != nil {
		f16 := &svcapitypes.ReplicationGroupPendingModifiedValues{}
		if resp.ReplicationGroup.PendingModifiedValues.AuthTokenStatus != nil {
			f16.AuthTokenStatus = resp.ReplicationGroup.PendingModifiedValues.AuthTokenStatus
		}
		if resp.ReplicationGroup.PendingModifiedValues.AutomaticFailoverStatus != nil {
			f16.AutomaticFailoverStatus = resp.ReplicationGroup.PendingModifiedValues.AutomaticFailoverStatus
		}
		if resp.ReplicationGroup.PendingModifiedValues.LogDeliveryConfigurations != nil {
			f16f2 := []*svcapitypes.PendingLogDeliveryConfiguration{}
			for _, f16f2iter := range resp.ReplicationGroup.PendingModifiedValues.LogDeliveryConfigurations {
				f16f2elem := &svcapitypes.PendingLogDeliveryConfiguration{}
				if f16f2iter.DestinationDetails != nil {
					f16f2elemf0 := &svcapitypes.DestinationDetails{}
					if f16f2iter.DestinationDetails.CloudWatchLogsDetails != nil {
						f16f2elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
						if f16f2iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
							f16f2elemf0f0.LogGroup = f16f2iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
						}
						f16f2elemf0.CloudWatchLogsDetails = f16f2elemf0f0
					}
					if f16f2iter.DestinationDetails.KinesisFirehoseDetails != nil {
						f16f2elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
						if f16f2iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
							f16f2elemf0f1.DeliveryStream = f16f2iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
						}
						f16f2elemf0.KinesisFirehoseDetails = f16f2elemf0f1
					}
					f16f2elem.DestinationDetails = f16f2elemf0
				}
				if f16f2iter.DestinationType != nil {
					f16f2elem.DestinationType = f16f2iter.DestinationType
				}
				if f16f2iter.LogFormat != nil {
					f16f2elem.LogFormat = f16f2iter.LogFormat
				}
				if f16f2iter.LogType != nil {
					f16f2elem.LogType = f16f2iter.LogType
				}
				f16f2 = append(f16f2, f16f2elem)
			}
			f16.LogDeliveryConfigurations = f16f2
		}
		if resp.ReplicationGroup.PendingModifiedValues.PrimaryClusterId != nil {
			f16.PrimaryClusterID = resp.ReplicationGroup.PendingModifiedValues.PrimaryClusterId
		}
		if resp.ReplicationGroup.PendingModifiedValues.Resharding != nil {
			f16f4 := &svcapitypes.ReshardingStatus{}
			if resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration != nil {
				f16f4f0 := &svcapitypes.SlotMigration{}
				if resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage != nil {
					f16f4f0.ProgressPercentage = resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage
				}
				f16f4.SlotMigration = f16f4f0
			}
			f16.Resharding = f16f4
		}
		if resp.ReplicationGroup.PendingModifiedValues.UserGroups != nil {
			f16f5 := &svcapitypes.UserGroupsUpdateStatus{}
			if resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToAdd != nil {
				f16f5f0 := []*string{}
				for _, f16f5f0iter := range resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToAdd {
					var f16f5f0elem string
					f16f5f0elem = *f16f5f0iter
					f16f5f0 = append(f16f5f0, &f16f5f0elem)
				}
				f16f5.UserGroupIDsToAdd = f16f5f0
			}
			if resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToRemove != nil {
				f16f5f1 := []*string{}
				for _, f16f5f1iter := range resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToRemove {
					var f16f5f1elem string
					f16f5f1elem = *f16f5f1iter
					f16f5f1 = append(f16f5f1, &f16f5f1elem)
				}
				f16f5.UserGroupIDsToRemove = f16f5f1
			}
			f16.UserGroups = f16f5
		}
		ko.Status.PendingModifiedValues = f16
	} else {
		ko.Status.PendingModifiedValues = nil
	}
	if resp.ReplicationGroup.SnapshottingClusterId != nil {
		ko.Status.SnapshottingClusterID = resp.ReplicationGroup.SnapshottingClusterId
	} else {
		ko.Status.SnapshottingClusterID = nil
	}
	if resp.ReplicationGroup.Status != nil {
		ko.Status.Status = resp.ReplicationGroup.Status
	} else {
		ko.Status.Status = nil
	}

	rm.setStatusDefaults(ko)
	// custom set output from response
	ko, err = rm.CustomCreateReplicationGroupSetOutput(ctx, desired, resp, ko)
	if err != nil {
		return nil, err
	}
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateReplicationGroupInput, error) {
	res := &svcsdk.CreateReplicationGroupInput{}

	if r.ko.Spec.AtRestEncryptionEnabled != nil {
		res.SetAtRestEncryptionEnabled(*r.ko.Spec.AtRestEncryptionEnabled)
	}
	if r.ko.Spec.AuthToken != nil {
		tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.AuthToken)
		if err != nil {
			return nil, err
		}
		if tmpSecret != "" {
			res.SetAuthToken(tmpSecret)
		}
	}
	if r.ko.Spec.AutoMinorVersionUpgrade != nil {
		res.SetAutoMinorVersionUpgrade(*r.ko.Spec.AutoMinorVersionUpgrade)
	}
	if r.ko.Spec.AutomaticFailoverEnabled != nil {
		res.SetAutomaticFailoverEnabled(*r.ko.Spec.AutomaticFailoverEnabled)
	}
	if r.ko.Spec.CacheNodeType != nil {
		res.SetCacheNodeType(*r.ko.Spec.CacheNodeType)
	}
	if r.ko.Spec.CacheParameterGroupName != nil {
		res.SetCacheParameterGroupName(*r.ko.Spec.CacheParameterGroupName)
	}
	if r.ko.Spec.CacheSecurityGroupNames != nil {
		f6 := []*string{}
		for _, f6iter := range r.ko.Spec.CacheSecurityGroupNames {
			var f6elem string
			f6elem = *f6iter
			f6 = append(f6, &f6elem)
		}
		res.SetCacheSecurityGroupNames(f6)
	}
	if r.ko.Spec.CacheSubnetGroupName != nil {
		res.SetCacheSubnetGroupName(*r.ko.Spec.CacheSubnetGroupName)
	}
	if r.ko.Spec.Engine != nil {
		res.SetEngine(*r.ko.Spec.Engine)
	}
	if r.ko.Spec.EngineVersion != nil {
		res.SetEngineVersion(*r.ko.Spec.EngineVersion)
	}
	if r.ko.Spec.KMSKeyID != nil {
		res.SetKmsKeyId(*r.ko.Spec.KMSKeyID)
	}
	if r.ko.Spec.LogDeliveryConfigurations != nil {
		f11 := []*svcsdk.LogDeliveryConfigurationRequest{}
		for _, f11iter := range r.ko.Spec.LogDeliveryConfigurations {
			f11elem := &svcsdk.LogDeliveryConfigurationRequest{}
			if f11iter.DestinationDetails != nil {
				f11elemf0 := &svcsdk.DestinationDetails{}
				if f11iter.DestinationDetails.CloudWatchLogsDetails != nil {
					f11elemf0f0 := &svcsdk.CloudWatchLogsDestinationDetails{}
					if f11iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
						f11elemf0f0.SetLogGroup(*f11iter.DestinationDetails.CloudWatchLogsDetails.LogGroup)
					}
					f11elemf0.SetCloudWatchLogsDetails(f11elemf0f0)
				}
				if f11iter.DestinationDetails.KinesisFirehoseDetails != nil {
					f11elemf0f1 := &svcsdk.KinesisFirehoseDestinationDetails{}
					if f11iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
						f11elemf0f1.SetDeliveryStream(*f11iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream)
					}
					f11elemf0.SetKinesisFirehoseDetails(f11elemf0f1)
				}
				f11elem.SetDestinationDetails(f11elemf0)
			}
			if f11iter.DestinationType != nil {
				f11elem.SetDestinationType(*f11iter.DestinationType)
			}
			if f11iter.Enabled != nil {
				f11elem.SetEnabled(*f11iter.Enabled)
			}
			if f11iter.LogFormat != nil {
				f11elem.SetLogFormat(*f11iter.LogFormat)
			}
			if f11iter.LogType != nil {
				f11elem.SetLogType(*f11iter.LogType)
			}
			f11 = append(f11, f11elem)
		}
		res.SetLogDeliveryConfigurations(f11)
	}
	if r.ko.Spec.MultiAZEnabled != nil {
		res.SetMultiAZEnabled(*r.ko.Spec.MultiAZEnabled)
	}
	if r.ko.Spec.NodeGroupConfiguration != nil {
		f13 := []*svcsdk.NodeGroupConfiguration{}
		for _, f13iter := range r.ko.Spec.NodeGroupConfiguration {
			f13elem := &svcsdk.NodeGroupConfiguration{}
			if f13iter.NodeGroupID != nil {
				f13elem.SetNodeGroupId(*f13iter.NodeGroupID)
			}
			if f13iter.PrimaryAvailabilityZone != nil {
				f13elem.SetPrimaryAvailabilityZone(*f13iter.PrimaryAvailabilityZone)
			}
			if f13iter.PrimaryOutpostARN != nil {
				f13elem.SetPrimaryOutpostArn(*f13iter.PrimaryOutpostARN)
			}
			if f13iter.ReplicaAvailabilityZones != nil {
				f13elemf3 := []*string{}
				for _, f13elemf3iter := range f13iter.ReplicaAvailabilityZones {
					var f13elemf3elem string
					f13elemf3elem = *f13elemf3iter
					f13elemf3 = append(f13elemf3, &f13elemf3elem)
				}
				f13elem.SetReplicaAvailabilityZones(f13elemf3)
			}
			if f13iter.ReplicaCount != nil {
				f13elem.SetReplicaCount(*f13iter.ReplicaCount)
			}
			if f13iter.ReplicaOutpostARNs != nil {
				f13elemf5 := []*string{}
				for _, f13elemf5iter := range f13iter.ReplicaOutpostARNs {
					var f13elemf5elem string
					f13elemf5elem = *f13elemf5iter
					f13elemf5 = append(f13elemf5, &f13elemf5elem)
				}
				f13elem.SetReplicaOutpostArns(f13elemf5)
			}
			if f13iter.Slots != nil {
				f13elem.SetSlots(*f13iter.Slots)
			}
			f13 = append(f13, f13elem)
		}
		res.SetNodeGroupConfiguration(f13)
	}
	if r.ko.Spec.NotificationTopicARN != nil {
		res.SetNotificationTopicArn(*r.ko.Spec.NotificationTopicARN)
	}
	if r.ko.Spec.NumCacheClusters != nil {
		res.SetNumCacheClusters(*r.ko.Spec.NumCacheClusters)
	}
	if r.ko.Spec.NumNodeGroups != nil {
		res.SetNumNodeGroups(*r.ko.Spec.NumNodeGroups)
	}
	if r.ko.Spec.Port != nil {
		res.SetPort(*r.ko.Spec.Port)
	}
	if r.ko.Spec.PreferredCacheClusterAZs != nil {
		f18 := []*string{}
		for _, f18iter := range r.ko.Spec.PreferredCacheClusterAZs {
			var f18elem string
			f18elem = *f18iter
			f18 = append(f18, &f18elem)
		}
		res.SetPreferredCacheClusterAZs(f18)
	}
	if r.ko.Spec.PreferredMaintenanceWindow != nil {
		res.SetPreferredMaintenanceWindow(*r.ko.Spec.PreferredMaintenanceWindow)
	}
	if r.ko.Spec.PrimaryClusterID != nil {
		res.SetPrimaryClusterId(*r.ko.Spec.PrimaryClusterID)
	}
	if r.ko.Spec.ReplicasPerNodeGroup != nil {
		res.SetReplicasPerNodeGroup(*r.ko.Spec.ReplicasPerNodeGroup)
	}
	if r.ko.Spec.ReplicationGroupDescription != nil {
		res.SetReplicationGroupDescription(*r.ko.Spec.ReplicationGroupDescription)
	}
	if r.ko.Spec.ReplicationGroupID != nil {
		res.SetReplicationGroupId(*r.ko.Spec.ReplicationGroupID)
	}
	if r.ko.Spec.SecurityGroupIDs != nil {
		f24 := []*string{}
		for _, f24iter := range r.ko.Spec.SecurityGroupIDs {
			var f24elem string
			f24elem = *f24iter
			f24 = append(f24, &f24elem)
		}
		res.SetSecurityGroupIds(f24)
	}
	if r.ko.Spec.SnapshotARNs != nil {
		f25 := []*string{}
		for _, f25iter := range r.ko.Spec.SnapshotARNs {
			var f25elem string
			f25elem = *f25iter
			f25 = append(f25, &f25elem)
		}
		res.SetSnapshotArns(f25)
	}
	if r.ko.Spec.SnapshotName != nil {
		res.SetSnapshotName(*r.ko.Spec.SnapshotName)
	}
	if r.ko.Spec.SnapshotRetentionLimit != nil {
		res.SetSnapshotRetentionLimit(*r.ko.Spec.SnapshotRetentionLimit)
	}
	if r.ko.Spec.SnapshotWindow != nil {
		res.SetSnapshotWindow(*r.ko.Spec.SnapshotWindow)
	}
	if r.ko.Spec.TransitEncryptionEnabled != nil {
		res.SetTransitEncryptionEnabled(*r.ko.Spec.TransitEncryptionEnabled)
	}
	if r.ko.Spec.UserGroupIDs != nil {
		f30 := []*string{}
		for _, f30iter := range r.ko.Spec.UserGroupIDs {
			var f30elem string
			f30elem = *f30iter
			f30 = append(f30, &f30elem)
		}
		res.SetUserGroupIds(f30)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer exit(err)
	updated, err = rm.CustomModifyReplicationGroup(ctx, desired, latest, delta)
	if updated != nil || err != nil {
		return updated, err
	}
	input, err := rm.newUpdateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	if delta.DifferentAt("UserGroupIDs") {
		for _, diff := range delta.Differences {
			if diff.Path.Contains("UserGroupIDs") {
				existingUserGroups := diff.B.([]*string)
				requiredUserGroups := diff.A.([]*string)

				// User groups to add
				{
					var userGroupsToAdd []*string

					for _, requiredUserGroup := range requiredUserGroups {
						found := false
						for _, existingUserGroup := range existingUserGroups {
							if requiredUserGroup == existingUserGroup {
								found = true
								break
							}
						}

						if !found {
							userGroupsToAdd = append(userGroupsToAdd, requiredUserGroup)
						}
					}

					input.SetUserGroupIdsToAdd(userGroupsToAdd)
				}

				// User groups to remove
				{
					var userGroupsToRemove []*string

					for _, existingUserGroup := range existingUserGroups {
						found := false
						for _, requiredUserGroup := range requiredUserGroups {
							if requiredUserGroup == existingUserGroup {
								found = true
								break
							}
						}

						if !found {
							userGroupsToRemove = append(userGroupsToRemove, existingUserGroup)
						}
					}

					input.SetUserGroupIdsToRemove(userGroupsToRemove)
				}
			}
		}
	}

	var resp *svcsdk.ModifyReplicationGroupOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyReplicationGroupWithContext(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyReplicationGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ReplicationGroup.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ReplicationGroup.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ReplicationGroup.AuthTokenEnabled != nil {
		ko.Status.AuthTokenEnabled = resp.ReplicationGroup.AuthTokenEnabled
	} else {
		ko.Status.AuthTokenEnabled = nil
	}
	if resp.ReplicationGroup.AuthTokenLastModifiedDate != nil {
		ko.Status.AuthTokenLastModifiedDate = &metav1.Time{*resp.ReplicationGroup.AuthTokenLastModifiedDate}
	} else {
		ko.Status.AuthTokenLastModifiedDate = nil
	}
	if resp.ReplicationGroup.AutomaticFailover != nil {
		ko.Status.AutomaticFailover = resp.ReplicationGroup.AutomaticFailover
	} else {
		ko.Status.AutomaticFailover = nil
	}
	if resp.ReplicationGroup.ClusterEnabled != nil {
		ko.Status.ClusterEnabled = resp.ReplicationGroup.ClusterEnabled
	} else {
		ko.Status.ClusterEnabled = nil
	}
	if resp.ReplicationGroup.ConfigurationEndpoint != nil {
		f7 := &svcapitypes.Endpoint{}
		if resp.ReplicationGroup.ConfigurationEndpoint.Address != nil {
			f7.Address = resp.ReplicationGroup.ConfigurationEndpoint.Address
		}
		if resp.ReplicationGroup.ConfigurationEndpoint.Port != nil {
			f7.Port = resp.ReplicationGroup.ConfigurationEndpoint.Port
		}
		ko.Status.ConfigurationEndpoint = f7
	} else {
		ko.Status.ConfigurationEndpoint = nil
	}
	if resp.ReplicationGroup.Description != nil {
		ko.Status.Description = resp.ReplicationGroup.Description
	} else {
		ko.Status.Description = nil
	}
	if resp.ReplicationGroup.GlobalReplicationGroupInfo != nil {
		f9 := &svcapitypes.GlobalReplicationGroupInfo{}
		if resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupId != nil {
			f9.GlobalReplicationGroupID = resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupId
		}
		if resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole != nil {
			f9.GlobalReplicationGroupMemberRole = resp.ReplicationGroup.GlobalReplicationGroupInfo.GlobalReplicationGroupMemberRole
		}
		ko.Status.GlobalReplicationGroupInfo = f9
	} else {
		ko.Status.GlobalReplicationGroupInfo = nil
	}
	if resp.ReplicationGroup.MemberClusters != nil {
		f12 := []*string{}
		for _, f12iter := range resp.ReplicationGroup.MemberClusters {
			var f12elem string
			f12elem = *f12iter
			f12 = append(f12, &f12elem)
		}
		ko.Status.MemberClusters = f12
	} else {
		ko.Status.MemberClusters = nil
	}
	if resp.ReplicationGroup.MemberClustersOutpostArns != nil {
		f13 := []*string{}
		for _, f13iter := range resp.ReplicationGroup.MemberClustersOutpostArns {
			var f13elem string
			f13elem = *f13iter
			f13 = append(f13, &f13elem)
		}
		ko.Status.MemberClustersOutpostARNs = f13
	} else {
		ko.Status.MemberClustersOutpostARNs = nil
	}
	if resp.ReplicationGroup.MultiAZ != nil {
		ko.Status.MultiAZ = resp.ReplicationGroup.MultiAZ
	} else {
		ko.Status.MultiAZ = nil
	}
	if resp.ReplicationGroup.NodeGroups != nil {
		f15 := []*svcapitypes.NodeGroup{}
		for _, f15iter := range resp.ReplicationGroup.NodeGroups {
			f15elem := &svcapitypes.NodeGroup{}
			if f15iter.NodeGroupId != nil {
				f15elem.NodeGroupID = f15iter.NodeGroupId
			}
			if f15iter.NodeGroupMembers != nil {
				f15elemf1 := []*svcapitypes.NodeGroupMember{}
				for _, f15elemf1iter := range f15iter.NodeGroupMembers {
					f15elemf1elem := &svcapitypes.NodeGroupMember{}
					if f15elemf1iter.CacheClusterId != nil {
						f15elemf1elem.CacheClusterID = f15elemf1iter.CacheClusterId
					}
					if f15elemf1iter.CacheNodeId != nil {
						f15elemf1elem.CacheNodeID = f15elemf1iter.CacheNodeId
					}
					if f15elemf1iter.CurrentRole != nil {
						f15elemf1elem.CurrentRole = f15elemf1iter.CurrentRole
					}
					if f15elemf1iter.PreferredAvailabilityZone != nil {
						f15elemf1elem.PreferredAvailabilityZone = f15elemf1iter.PreferredAvailabilityZone
					}
					if f15elemf1iter.PreferredOutpostArn != nil {
						f15elemf1elem.PreferredOutpostARN = f15elemf1iter.PreferredOutpostArn
					}
					if f15elemf1iter.ReadEndpoint != nil {
						f15elemf1elemf5 := &svcapitypes.Endpoint{}
						if f15elemf1iter.ReadEndpoint.Address != nil {
							f15elemf1elemf5.Address = f15elemf1iter.ReadEndpoint.Address
						}
						if f15elemf1iter.ReadEndpoint.Port != nil {
							f15elemf1elemf5.Port = f15elemf1iter.ReadEndpoint.Port
						}
						f15elemf1elem.ReadEndpoint = f15elemf1elemf5
					}
					f15elemf1 = append(f15elemf1, f15elemf1elem)
				}
				f15elem.NodeGroupMembers = f15elemf1
			}
			if f15iter.PrimaryEndpoint != nil {
				f15elemf2 := &svcapitypes.Endpoint{}
				if f15iter.PrimaryEndpoint.Address != nil {
					f15elemf2.Address = f15iter.PrimaryEndpoint.Address
				}
				if f15iter.PrimaryEndpoint.Port != nil {
					f15elemf2.Port = f15iter.PrimaryEndpoint.Port
				}
				f15elem.PrimaryEndpoint = f15elemf2
			}
			if f15iter.ReaderEndpoint != nil {
				f15elemf3 := &svcapitypes.Endpoint{}
				if f15iter.ReaderEndpoint.Address != nil {
					f15elemf3.Address = f15iter.ReaderEndpoint.Address
				}
				if f15iter.ReaderEndpoint.Port != nil {
					f15elemf3.Port = f15iter.ReaderEndpoint.Port
				}
				f15elem.ReaderEndpoint = f15elemf3
			}
			if f15iter.Slots != nil {
				f15elem.Slots = f15iter.Slots
			}
			if f15iter.Status != nil {
				f15elem.Status = f15iter.Status
			}
			f15 = append(f15, f15elem)
		}
		ko.Status.NodeGroups = f15
	} else {
		ko.Status.NodeGroups = nil
	}
	if resp.ReplicationGroup.PendingModifiedValues != nil {
		f16 := &svcapitypes.ReplicationGroupPendingModifiedValues{}
		if resp.ReplicationGroup.PendingModifiedValues.AuthTokenStatus != nil {
			f16.AuthTokenStatus = resp.ReplicationGroup.PendingModifiedValues.AuthTokenStatus
		}
		if resp.ReplicationGroup.PendingModifiedValues.AutomaticFailoverStatus != nil {
			f16.AutomaticFailoverStatus = resp.ReplicationGroup.PendingModifiedValues.AutomaticFailoverStatus
		}
		if resp.ReplicationGroup.PendingModifiedValues.LogDeliveryConfigurations != nil {
			f16f2 := []*svcapitypes.PendingLogDeliveryConfiguration{}
			for _, f16f2iter := range resp.ReplicationGroup.PendingModifiedValues.LogDeliveryConfigurations {
				f16f2elem := &svcapitypes.PendingLogDeliveryConfiguration{}
				if f16f2iter.DestinationDetails != nil {
					f16f2elemf0 := &svcapitypes.DestinationDetails{}
					if f16f2iter.DestinationDetails.CloudWatchLogsDetails != nil {
						f16f2elemf0f0 := &svcapitypes.CloudWatchLogsDestinationDetails{}
						if f16f2iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
							f16f2elemf0f0.LogGroup = f16f2iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
						}
						f16f2elemf0.CloudWatchLogsDetails = f16f2elemf0f0
					}
					if f16f2iter.DestinationDetails.KinesisFirehoseDetails != nil {
						f16f2elemf0f1 := &svcapitypes.KinesisFirehoseDestinationDetails{}
						if f16f2iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
							f16f2elemf0f1.DeliveryStream = f16f2iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
						}
						f16f2elemf0.KinesisFirehoseDetails = f16f2elemf0f1
					}
					f16f2elem.DestinationDetails = f16f2elemf0
				}
				if f16f2iter.DestinationType != nil {
					f16f2elem.DestinationType = f16f2iter.DestinationType
				}
				if f16f2iter.LogFormat != nil {
					f16f2elem.LogFormat = f16f2iter.LogFormat
				}
				if f16f2iter.LogType != nil {
					f16f2elem.LogType = f16f2iter.LogType
				}
				f16f2 = append(f16f2, f16f2elem)
			}
			f16.LogDeliveryConfigurations = f16f2
		}
		if resp.ReplicationGroup.PendingModifiedValues.PrimaryClusterId != nil {
			f16.PrimaryClusterID = resp.ReplicationGroup.PendingModifiedValues.PrimaryClusterId
		}
		if resp.ReplicationGroup.PendingModifiedValues.Resharding != nil {
			f16f4 := &svcapitypes.ReshardingStatus{}
			if resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration != nil {
				f16f4f0 := &svcapitypes.SlotMigration{}
				if resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage != nil {
					f16f4f0.ProgressPercentage = resp.ReplicationGroup.PendingModifiedValues.Resharding.SlotMigration.ProgressPercentage
				}
				f16f4.SlotMigration = f16f4f0
			}
			f16.Resharding = f16f4
		}
		if resp.ReplicationGroup.PendingModifiedValues.UserGroups != nil {
			f16f5 := &svcapitypes.UserGroupsUpdateStatus{}
			if resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToAdd != nil {
				f16f5f0 := []*string{}
				for _, f16f5f0iter := range resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToAdd {
					var f16f5f0elem string
					f16f5f0elem = *f16f5f0iter
					f16f5f0 = append(f16f5f0, &f16f5f0elem)
				}
				f16f5.UserGroupIDsToAdd = f16f5f0
			}
			if resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToRemove != nil {
				f16f5f1 := []*string{}
				for _, f16f5f1iter := range resp.ReplicationGroup.PendingModifiedValues.UserGroups.UserGroupIdsToRemove {
					var f16f5f1elem string
					f16f5f1elem = *f16f5f1iter
					f16f5f1 = append(f16f5f1, &f16f5f1elem)
				}
				f16f5.UserGroupIDsToRemove = f16f5f1
			}
			f16.UserGroups = f16f5
		}
		ko.Status.PendingModifiedValues = f16
	} else {
		ko.Status.PendingModifiedValues = nil
	}
	if resp.ReplicationGroup.SnapshottingClusterId != nil {
		ko.Status.SnapshottingClusterID = resp.ReplicationGroup.SnapshottingClusterId
	} else {
		ko.Status.SnapshottingClusterID = nil
	}
	if resp.ReplicationGroup.Status != nil {
		ko.Status.Status = resp.ReplicationGroup.Status
	} else {
		ko.Status.Status = nil
	}

	rm.setStatusDefaults(ko)
	// custom set output from response
	ko, err = rm.CustomModifyReplicationGroupSetOutput(ctx, desired, resp, ko)
	if err != nil {
		return nil, err
	}
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.ModifyReplicationGroupInput, error) {
	res := &svcsdk.ModifyReplicationGroupInput{}

	res.SetApplyImmediately(true)
	if r.ko.Spec.AuthToken != nil {
		tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.AuthToken)
		if err != nil {
			return nil, err
		}
		if tmpSecret != "" {
			res.SetAuthToken(tmpSecret)
		}
	}
	if r.ko.Spec.AutoMinorVersionUpgrade != nil {
		res.SetAutoMinorVersionUpgrade(*r.ko.Spec.AutoMinorVersionUpgrade)
	}
	if r.ko.Spec.AutomaticFailoverEnabled != nil {
		res.SetAutomaticFailoverEnabled(*r.ko.Spec.AutomaticFailoverEnabled)
	}
	if r.ko.Spec.CacheNodeType != nil {
		res.SetCacheNodeType(*r.ko.Spec.CacheNodeType)
	}
	if r.ko.Spec.CacheParameterGroupName != nil {
		res.SetCacheParameterGroupName(*r.ko.Spec.CacheParameterGroupName)
	}
	if r.ko.Spec.CacheSecurityGroupNames != nil {
		f7 := []*string{}
		for _, f7iter := range r.ko.Spec.CacheSecurityGroupNames {
			var f7elem string
			f7elem = *f7iter
			f7 = append(f7, &f7elem)
		}
		res.SetCacheSecurityGroupNames(f7)
	}
	if r.ko.Spec.LogDeliveryConfigurations != nil {
		f8 := []*svcsdk.LogDeliveryConfigurationRequest{}
		for _, f8iter := range r.ko.Spec.LogDeliveryConfigurations {
			f8elem := &svcsdk.LogDeliveryConfigurationRequest{}
			if f8iter.DestinationDetails != nil {
				f8elemf0 := &svcsdk.DestinationDetails{}
				if f8iter.DestinationDetails.CloudWatchLogsDetails != nil {
					f8elemf0f0 := &svcsdk.CloudWatchLogsDestinationDetails{}
					if f8iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
						f8elemf0f0.SetLogGroup(*f8iter.DestinationDetails.CloudWatchLogsDetails.LogGroup)
					}
					f8elemf0.SetCloudWatchLogsDetails(f8elemf0f0)
				}
				if f8iter.DestinationDetails.KinesisFirehoseDetails != nil {
					f8elemf0f1 := &svcsdk.KinesisFirehoseDestinationDetails{}
					if f8iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
						f8elemf0f1.SetDeliveryStream(*f8iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream)
					}
					f8elemf0.SetKinesisFirehoseDetails(f8elemf0f1)
				}
				f8elem.SetDestinationDetails(f8elemf0)
			}
			if f8iter.DestinationType != nil {
				f8elem.SetDestinationType(*f8iter.DestinationType)
			}
			if f8iter.Enabled != nil {
				f8elem.SetEnabled(*f8iter.Enabled)
			}
			if f8iter.LogFormat != nil {
				f8elem.SetLogFormat(*f8iter.LogFormat)
			}
			if f8iter.LogType != nil {
				f8elem.SetLogType(*f8iter.LogType)
			}
			f8 = append(f8, f8elem)
		}
		res.SetLogDeliveryConfigurations(f8)
	}
	if r.ko.Spec.MultiAZEnabled != nil {
		res.SetMultiAZEnabled(*r.ko.Spec.MultiAZEnabled)
	}
	if r.ko.Spec.NotificationTopicARN != nil {
		res.SetNotificationTopicArn(*r.ko.Spec.NotificationTopicARN)
	}
	if r.ko.Spec.PreferredMaintenanceWindow != nil {
		res.SetPreferredMaintenanceWindow(*r.ko.Spec.PreferredMaintenanceWindow)
	}
	if r.ko.Spec.PrimaryClusterID != nil {
		res.SetPrimaryClusterId(*r.ko.Spec.PrimaryClusterID)
	}
	if r.ko.Spec.ReplicationGroupDescription != nil {
		res.SetReplicationGroupDescription(*r.ko.Spec.ReplicationGroupDescription)
	}
	if r.ko.Spec.ReplicationGroupID != nil {
		res.SetReplicationGroupId(*r.ko.Spec.ReplicationGroupID)
	}
	if r.ko.Spec.SnapshotRetentionLimit != nil {
		res.SetSnapshotRetentionLimit(*r.ko.Spec.SnapshotRetentionLimit)
	}
	if r.ko.Spec.SnapshotWindow != nil {
		res.SetSnapshotWindow(*r.ko.Spec.SnapshotWindow)
	}
	if r.ko.Status.SnapshottingClusterID != nil {
		res.SetSnapshottingClusterId(*r.ko.Status.SnapshottingClusterID)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer exit(err)
	if isDeleting(r) {
		return requeueWaitWhileDeleting
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return err
	}
	_, err = rm.sdkapi.DeleteReplicationGroupWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteReplicationGroup", err)
	if err == nil {
		if foundResource, err := rm.sdkFind(ctx, r); err != ackerr.NotFound {
			if isDeleting(foundResource) {
				return requeueWaitWhileDeleting
			}
			return err
		}
	}
	return err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteReplicationGroupInput, error) {
	res := &svcsdk.DeleteReplicationGroupInput{}

	if r.ko.Spec.ReplicationGroupID != nil {
		res.SetReplicationGroupId(*r.ko.Spec.ReplicationGroupID)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ReplicationGroup,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
	}

	if rm.terminalAWSError(err) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		terminalCondition.Status = corev1.ConditionTrue
		awsErr, _ := ackerr.AWSError(err)
		errorMessage := awsErr.Message()
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Message()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// custom update conditions
	customUpdate := rm.CustomUpdateConditions(ko, r, err)
	if terminalCondition != nil || recoverableCondition != nil || customUpdate {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}
	awsErr, ok := ackerr.AWSError(err)
	if !ok {
		return false
	}
	switch awsErr.Code() {
	case "InvalidParameter",
		"InvalidParameterValue",
		"InvalidParameterCombination",
		"InsufficientCacheClusterCapacity",
		"CacheSecurityGroupNotFound",
		"CacheSubnetGroupNotFoundFault",
		"ClusterQuotaForCustomerExceeded",
		"NodeQuotaForClusterExceeded",
		"NodeQuotaForCustomerExceeded",
		"InvalidVPCNetworkStateFault",
		"TagQuotaPerResourceExceeded",
		"NodeGroupsPerReplicationGroupQuotaExceeded",
		"InvalidCacheSecurityGroupState",
		"CacheParameterGroupNotFound",
		"InvalidKMSKeyFault":
		return true
	default:
		return false
	}
}
