// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package cache_cluster

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/elasticache"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/elasticache/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/elasticache-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.CacheCluster{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeCacheClustersOutput
	resp, err = rm.sdkapi.DescribeCacheClusters(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeCacheClusters", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "CacheClusterNotFound" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.CacheClusters {
		if elem.ARN != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ARN)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.AtRestEncryptionEnabled != nil {
			ko.Status.AtRestEncryptionEnabled = elem.AtRestEncryptionEnabled
		} else {
			ko.Status.AtRestEncryptionEnabled = nil
		}
		if elem.AuthTokenEnabled != nil {
			ko.Status.AuthTokenEnabled = elem.AuthTokenEnabled
		} else {
			ko.Status.AuthTokenEnabled = nil
		}
		if elem.AuthTokenLastModifiedDate != nil {
			ko.Status.AuthTokenLastModifiedDate = &metav1.Time{*elem.AuthTokenLastModifiedDate}
		} else {
			ko.Status.AuthTokenLastModifiedDate = nil
		}
		if elem.AutoMinorVersionUpgrade != nil {
			ko.Spec.AutoMinorVersionUpgrade = elem.AutoMinorVersionUpgrade
		} else {
			ko.Spec.AutoMinorVersionUpgrade = nil
		}
		if elem.CacheClusterCreateTime != nil {
			ko.Status.CacheClusterCreateTime = &metav1.Time{*elem.CacheClusterCreateTime}
		} else {
			ko.Status.CacheClusterCreateTime = nil
		}
		if elem.CacheClusterId != nil {
			ko.Spec.CacheClusterID = elem.CacheClusterId
		} else {
			ko.Spec.CacheClusterID = nil
		}
		if elem.CacheClusterStatus != nil {
			ko.Status.CacheClusterStatus = elem.CacheClusterStatus
		} else {
			ko.Status.CacheClusterStatus = nil
		}
		if elem.CacheNodeType != nil {
			ko.Spec.CacheNodeType = elem.CacheNodeType
		} else {
			ko.Spec.CacheNodeType = nil
		}
		if elem.CacheNodes != nil {
			f9 := []*svcapitypes.CacheNode{}
			for _, f9iter := range elem.CacheNodes {
				f9elem := &svcapitypes.CacheNode{}
				if f9iter.CacheNodeCreateTime != nil {
					f9elem.CacheNodeCreateTime = &metav1.Time{*f9iter.CacheNodeCreateTime}
				}
				if f9iter.CacheNodeId != nil {
					f9elem.CacheNodeID = f9iter.CacheNodeId
				}
				if f9iter.CacheNodeStatus != nil {
					f9elem.CacheNodeStatus = f9iter.CacheNodeStatus
				}
				if f9iter.CustomerAvailabilityZone != nil {
					f9elem.CustomerAvailabilityZone = f9iter.CustomerAvailabilityZone
				}
				if f9iter.CustomerOutpostArn != nil {
					f9elem.CustomerOutpostARN = f9iter.CustomerOutpostArn
				}
				if f9iter.Endpoint != nil {
					f9elemf5 := &svcapitypes.Endpoint{}
					if f9iter.Endpoint.Address != nil {
						f9elemf5.Address = f9iter.Endpoint.Address
					}
					if f9iter.Endpoint.Port != nil {
						portCopy := int64(*f9iter.Endpoint.Port)
						f9elemf5.Port = &portCopy
					}
					f9elem.Endpoint = f9elemf5
				}
				if f9iter.ParameterGroupStatus != nil {
					f9elem.ParameterGroupStatus = f9iter.ParameterGroupStatus
				}
				if f9iter.SourceCacheNodeId != nil {
					f9elem.SourceCacheNodeID = f9iter.SourceCacheNodeId
				}
				f9 = append(f9, f9elem)
			}
			ko.Status.CacheNodes = f9
		} else {
			ko.Status.CacheNodes = nil
		}
		if elem.CacheParameterGroup != nil {
			f10 := &svcapitypes.CacheParameterGroupStatus_SDK{}
			if elem.CacheParameterGroup.CacheNodeIdsToReboot != nil {
				f10.CacheNodeIDsToReboot = aws.StringSlice(elem.CacheParameterGroup.CacheNodeIdsToReboot)
			}
			if elem.CacheParameterGroup.CacheParameterGroupName != nil {
				f10.CacheParameterGroupName = elem.CacheParameterGroup.CacheParameterGroupName
			}
			if elem.CacheParameterGroup.ParameterApplyStatus != nil {
				f10.ParameterApplyStatus = elem.CacheParameterGroup.ParameterApplyStatus
			}
			ko.Status.CacheParameterGroup = f10
		} else {
			ko.Status.CacheParameterGroup = nil
		}
		if elem.CacheSecurityGroups != nil {
			f11 := []*svcapitypes.CacheSecurityGroupMembership{}
			for _, f11iter := range elem.CacheSecurityGroups {
				f11elem := &svcapitypes.CacheSecurityGroupMembership{}
				if f11iter.CacheSecurityGroupName != nil {
					f11elem.CacheSecurityGroupName = f11iter.CacheSecurityGroupName
				}
				if f11iter.Status != nil {
					f11elem.Status = f11iter.Status
				}
				f11 = append(f11, f11elem)
			}
			ko.Status.CacheSecurityGroups = f11
		} else {
			ko.Status.CacheSecurityGroups = nil
		}
		if elem.CacheSubnetGroupName != nil {
			ko.Spec.CacheSubnetGroupName = elem.CacheSubnetGroupName
		} else {
			ko.Spec.CacheSubnetGroupName = nil
		}
		if elem.ClientDownloadLandingPage != nil {
			ko.Status.ClientDownloadLandingPage = elem.ClientDownloadLandingPage
		} else {
			ko.Status.ClientDownloadLandingPage = nil
		}
		if elem.ConfigurationEndpoint != nil {
			f14 := &svcapitypes.Endpoint{}
			if elem.ConfigurationEndpoint.Address != nil {
				f14.Address = elem.ConfigurationEndpoint.Address
			}
			if elem.ConfigurationEndpoint.Port != nil {
				portCopy := int64(*elem.ConfigurationEndpoint.Port)
				f14.Port = &portCopy
			}
			ko.Status.ConfigurationEndpoint = f14
		} else {
			ko.Status.ConfigurationEndpoint = nil
		}
		if elem.Engine != nil {
			ko.Spec.Engine = elem.Engine
		} else {
			ko.Spec.Engine = nil
		}
		if elem.EngineVersion != nil {
			ko.Spec.EngineVersion = elem.EngineVersion
		} else {
			ko.Spec.EngineVersion = nil
		}
		if elem.IpDiscovery != "" {
			ko.Spec.IPDiscovery = aws.String(string(elem.IpDiscovery))
		} else {
			ko.Spec.IPDiscovery = nil
		}
		if elem.NetworkType != "" {
			ko.Spec.NetworkType = aws.String(string(elem.NetworkType))
		} else {
			ko.Spec.NetworkType = nil
		}
		if elem.NotificationConfiguration != nil {
			f19 := &svcapitypes.NotificationConfiguration{}
			if elem.NotificationConfiguration.TopicArn != nil {
				f19.TopicARN = elem.NotificationConfiguration.TopicArn
			}
			if elem.NotificationConfiguration.TopicStatus != nil {
				f19.TopicStatus = elem.NotificationConfiguration.TopicStatus
			}
			ko.Status.NotificationConfiguration = f19
		} else {
			ko.Status.NotificationConfiguration = nil
		}
		if elem.NumCacheNodes != nil {
			numCacheNodesCopy := int64(*elem.NumCacheNodes)
			ko.Spec.NumCacheNodes = &numCacheNodesCopy
		} else {
			ko.Spec.NumCacheNodes = nil
		}
		if elem.PendingModifiedValues != nil {
			f21 := &svcapitypes.PendingModifiedValues{}
			if elem.PendingModifiedValues.AuthTokenStatus != "" {
				f21.AuthTokenStatus = aws.String(string(elem.PendingModifiedValues.AuthTokenStatus))
			}
			if elem.PendingModifiedValues.CacheNodeIdsToRemove != nil {
				f21.CacheNodeIDsToRemove = aws.StringSlice(elem.PendingModifiedValues.CacheNodeIdsToRemove)
			}
			if elem.PendingModifiedValues.CacheNodeType != nil {
				f21.CacheNodeType = elem.PendingModifiedValues.CacheNodeType
			}
			if elem.PendingModifiedValues.EngineVersion != nil {
				f21.EngineVersion = elem.PendingModifiedValues.EngineVersion
			}
			if elem.PendingModifiedValues.NumCacheNodes != nil {
				numCacheNodesCopy := int64(*elem.PendingModifiedValues.NumCacheNodes)
				f21.NumCacheNodes = &numCacheNodesCopy
			}
			if elem.PendingModifiedValues.TransitEncryptionEnabled != nil {
				f21.TransitEncryptionEnabled = elem.PendingModifiedValues.TransitEncryptionEnabled
			}
			if elem.PendingModifiedValues.TransitEncryptionMode != "" {
				f21.TransitEncryptionMode = aws.String(string(elem.PendingModifiedValues.TransitEncryptionMode))
			}
			ko.Status.PendingModifiedValues = f21
		} else {
			ko.Status.PendingModifiedValues = nil
		}
		if elem.PreferredAvailabilityZone != nil {
			ko.Spec.PreferredAvailabilityZone = elem.PreferredAvailabilityZone
		} else {
			ko.Spec.PreferredAvailabilityZone = nil
		}
		if elem.PreferredMaintenanceWindow != nil {
			ko.Spec.PreferredMaintenanceWindow = elem.PreferredMaintenanceWindow
		} else {
			ko.Spec.PreferredMaintenanceWindow = nil
		}
		if elem.PreferredOutpostArn != nil {
			ko.Spec.PreferredOutpostARN = elem.PreferredOutpostArn
		} else {
			ko.Spec.PreferredOutpostARN = nil
		}
		if elem.ReplicationGroupId != nil {
			ko.Spec.ReplicationGroupID = elem.ReplicationGroupId
		} else {
			ko.Spec.ReplicationGroupID = nil
		}
		if elem.ReplicationGroupLogDeliveryEnabled != nil {
			ko.Status.ReplicationGroupLogDeliveryEnabled = elem.ReplicationGroupLogDeliveryEnabled
		} else {
			ko.Status.ReplicationGroupLogDeliveryEnabled = nil
		}
		if elem.SecurityGroups != nil {
			f27 := []*svcapitypes.SecurityGroupMembership{}
			for _, f27iter := range elem.SecurityGroups {
				f27elem := &svcapitypes.SecurityGroupMembership{}
				if f27iter.SecurityGroupId != nil {
					f27elem.SecurityGroupID = f27iter.SecurityGroupId
				}
				if f27iter.Status != nil {
					f27elem.Status = f27iter.Status
				}
				f27 = append(f27, f27elem)
			}
			ko.Status.SecurityGroups = f27
		} else {
			ko.Status.SecurityGroups = nil
		}
		if elem.SnapshotRetentionLimit != nil {
			snapshotRetentionLimitCopy := int64(*elem.SnapshotRetentionLimit)
			ko.Spec.SnapshotRetentionLimit = &snapshotRetentionLimitCopy
		} else {
			ko.Spec.SnapshotRetentionLimit = nil
		}
		if elem.SnapshotWindow != nil {
			ko.Spec.SnapshotWindow = elem.SnapshotWindow
		} else {
			ko.Spec.SnapshotWindow = nil
		}
		if elem.TransitEncryptionEnabled != nil {
			ko.Spec.TransitEncryptionEnabled = elem.TransitEncryptionEnabled
		} else {
			ko.Spec.TransitEncryptionEnabled = nil
		}
		if elem.TransitEncryptionMode != "" {
			ko.Status.TransitEncryptionMode = aws.String(string(elem.TransitEncryptionMode))
		} else {
			ko.Status.TransitEncryptionMode = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	if pendingModifications := ko.Status.PendingModifiedValues; pendingModifications != nil {
		if pendingModifications.NumCacheNodes != nil {
			ko.Spec.NumCacheNodes = pendingModifications.NumCacheNodes
		}
		if pendingModifications.CacheNodeType != nil {
			ko.Spec.CacheNodeType = pendingModifications.CacheNodeType
		}
		if pendingModifications.TransitEncryptionEnabled != nil {
			ko.Spec.TransitEncryptionEnabled = pendingModifications.TransitEncryptionEnabled
		}
	}
	if isAvailable(r) {
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionTrue, nil, nil)
	} else {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
		return &resource{ko}, nil
	}
	if ko.Status.ACKResourceMetadata != nil && ko.Status.ACKResourceMetadata.ARN != nil {
		resourceARN := (*string)(ko.Status.ACKResourceMetadata.ARN)
		tags, err := rm.getTags(ctx, *resourceARN)
		if err != nil {
			return nil, err
		}
		ko.Spec.Tags = tags
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Spec.CacheClusterID == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeCacheClustersInput, error) {
	res := &svcsdk.DescribeCacheClustersInput{}

	if r.ko.Spec.CacheClusterID != nil {
		res.CacheClusterId = r.ko.Spec.CacheClusterID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateCacheClusterOutput
	_ = resp
	resp, err = rm.sdkapi.CreateCacheCluster(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateCacheCluster", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.CacheCluster.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.CacheCluster.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CacheCluster.AtRestEncryptionEnabled != nil {
		ko.Status.AtRestEncryptionEnabled = resp.CacheCluster.AtRestEncryptionEnabled
	} else {
		ko.Status.AtRestEncryptionEnabled = nil
	}
	if resp.CacheCluster.AuthTokenEnabled != nil {
		ko.Status.AuthTokenEnabled = resp.CacheCluster.AuthTokenEnabled
	} else {
		ko.Status.AuthTokenEnabled = nil
	}
	if resp.CacheCluster.AuthTokenLastModifiedDate != nil {
		ko.Status.AuthTokenLastModifiedDate = &metav1.Time{*resp.CacheCluster.AuthTokenLastModifiedDate}
	} else {
		ko.Status.AuthTokenLastModifiedDate = nil
	}
	if resp.CacheCluster.AutoMinorVersionUpgrade != nil {
		ko.Spec.AutoMinorVersionUpgrade = resp.CacheCluster.AutoMinorVersionUpgrade
	} else {
		ko.Spec.AutoMinorVersionUpgrade = nil
	}
	if resp.CacheCluster.CacheClusterCreateTime != nil {
		ko.Status.CacheClusterCreateTime = &metav1.Time{*resp.CacheCluster.CacheClusterCreateTime}
	} else {
		ko.Status.CacheClusterCreateTime = nil
	}
	if resp.CacheCluster.CacheClusterId != nil {
		ko.Spec.CacheClusterID = resp.CacheCluster.CacheClusterId
	} else {
		ko.Spec.CacheClusterID = nil
	}
	if resp.CacheCluster.CacheClusterStatus != nil {
		ko.Status.CacheClusterStatus = resp.CacheCluster.CacheClusterStatus
	} else {
		ko.Status.CacheClusterStatus = nil
	}
	if resp.CacheCluster.CacheNodeType != nil {
		ko.Spec.CacheNodeType = resp.CacheCluster.CacheNodeType
	} else {
		ko.Spec.CacheNodeType = nil
	}
	if resp.CacheCluster.CacheNodes != nil {
		f9 := []*svcapitypes.CacheNode{}
		for _, f9iter := range resp.CacheCluster.CacheNodes {
			f9elem := &svcapitypes.CacheNode{}
			if f9iter.CacheNodeCreateTime != nil {
				f9elem.CacheNodeCreateTime = &metav1.Time{*f9iter.CacheNodeCreateTime}
			}
			if f9iter.CacheNodeId != nil {
				f9elem.CacheNodeID = f9iter.CacheNodeId
			}
			if f9iter.CacheNodeStatus != nil {
				f9elem.CacheNodeStatus = f9iter.CacheNodeStatus
			}
			if f9iter.CustomerAvailabilityZone != nil {
				f9elem.CustomerAvailabilityZone = f9iter.CustomerAvailabilityZone
			}
			if f9iter.CustomerOutpostArn != nil {
				f9elem.CustomerOutpostARN = f9iter.CustomerOutpostArn
			}
			if f9iter.Endpoint != nil {
				f9elemf5 := &svcapitypes.Endpoint{}
				if f9iter.Endpoint.Address != nil {
					f9elemf5.Address = f9iter.Endpoint.Address
				}
				if f9iter.Endpoint.Port != nil {
					portCopy := int64(*f9iter.Endpoint.Port)
					f9elemf5.Port = &portCopy
				}
				f9elem.Endpoint = f9elemf5
			}
			if f9iter.ParameterGroupStatus != nil {
				f9elem.ParameterGroupStatus = f9iter.ParameterGroupStatus
			}
			if f9iter.SourceCacheNodeId != nil {
				f9elem.SourceCacheNodeID = f9iter.SourceCacheNodeId
			}
			f9 = append(f9, f9elem)
		}
		ko.Status.CacheNodes = f9
	} else {
		ko.Status.CacheNodes = nil
	}
	if resp.CacheCluster.CacheParameterGroup != nil {
		f10 := &svcapitypes.CacheParameterGroupStatus_SDK{}
		if resp.CacheCluster.CacheParameterGroup.CacheNodeIdsToReboot != nil {
			f10.CacheNodeIDsToReboot = aws.StringSlice(resp.CacheCluster.CacheParameterGroup.CacheNodeIdsToReboot)
		}
		if resp.CacheCluster.CacheParameterGroup.CacheParameterGroupName != nil {
			f10.CacheParameterGroupName = resp.CacheCluster.CacheParameterGroup.CacheParameterGroupName
		}
		if resp.CacheCluster.CacheParameterGroup.ParameterApplyStatus != nil {
			f10.ParameterApplyStatus = resp.CacheCluster.CacheParameterGroup.ParameterApplyStatus
		}
		ko.Status.CacheParameterGroup = f10
	} else {
		ko.Status.CacheParameterGroup = nil
	}
	if resp.CacheCluster.CacheSecurityGroups != nil {
		f11 := []*svcapitypes.CacheSecurityGroupMembership{}
		for _, f11iter := range resp.CacheCluster.CacheSecurityGroups {
			f11elem := &svcapitypes.CacheSecurityGroupMembership{}
			if f11iter.CacheSecurityGroupName != nil {
				f11elem.CacheSecurityGroupName = f11iter.CacheSecurityGroupName
			}
			if f11iter.Status != nil {
				f11elem.Status = f11iter.Status
			}
			f11 = append(f11, f11elem)
		}
		ko.Status.CacheSecurityGroups = f11
	} else {
		ko.Status.CacheSecurityGroups = nil
	}
	if resp.CacheCluster.CacheSubnetGroupName != nil {
		ko.Spec.CacheSubnetGroupName = resp.CacheCluster.CacheSubnetGroupName
	} else {
		ko.Spec.CacheSubnetGroupName = nil
	}
	if resp.CacheCluster.ClientDownloadLandingPage != nil {
		ko.Status.ClientDownloadLandingPage = resp.CacheCluster.ClientDownloadLandingPage
	} else {
		ko.Status.ClientDownloadLandingPage = nil
	}
	if resp.CacheCluster.ConfigurationEndpoint != nil {
		f14 := &svcapitypes.Endpoint{}
		if resp.CacheCluster.ConfigurationEndpoint.Address != nil {
			f14.Address = resp.CacheCluster.ConfigurationEndpoint.Address
		}
		if resp.CacheCluster.ConfigurationEndpoint.Port != nil {
			portCopy := int64(*resp.CacheCluster.ConfigurationEndpoint.Port)
			f14.Port = &portCopy
		}
		ko.Status.ConfigurationEndpoint = f14
	} else {
		ko.Status.ConfigurationEndpoint = nil
	}
	if resp.CacheCluster.Engine != nil {
		ko.Spec.Engine = resp.CacheCluster.Engine
	} else {
		ko.Spec.Engine = nil
	}
	if resp.CacheCluster.EngineVersion != nil {
		ko.Spec.EngineVersion = resp.CacheCluster.EngineVersion
	} else {
		ko.Spec.EngineVersion = nil
	}
	if resp.CacheCluster.IpDiscovery != "" {
		ko.Spec.IPDiscovery = aws.String(string(resp.CacheCluster.IpDiscovery))
	} else {
		ko.Spec.IPDiscovery = nil
	}
	if resp.CacheCluster.NetworkType != "" {
		ko.Spec.NetworkType = aws.String(string(resp.CacheCluster.NetworkType))
	} else {
		ko.Spec.NetworkType = nil
	}
	if resp.CacheCluster.NotificationConfiguration != nil {
		f19 := &svcapitypes.NotificationConfiguration{}
		if resp.CacheCluster.NotificationConfiguration.TopicArn != nil {
			f19.TopicARN = resp.CacheCluster.NotificationConfiguration.TopicArn
		}
		if resp.CacheCluster.NotificationConfiguration.TopicStatus != nil {
			f19.TopicStatus = resp.CacheCluster.NotificationConfiguration.TopicStatus
		}
		ko.Status.NotificationConfiguration = f19
	} else {
		ko.Status.NotificationConfiguration = nil
	}
	if resp.CacheCluster.NumCacheNodes != nil {
		numCacheNodesCopy := int64(*resp.CacheCluster.NumCacheNodes)
		ko.Spec.NumCacheNodes = &numCacheNodesCopy
	} else {
		ko.Spec.NumCacheNodes = nil
	}
	if resp.CacheCluster.PendingModifiedValues != nil {
		f21 := &svcapitypes.PendingModifiedValues{}
		if resp.CacheCluster.PendingModifiedValues.AuthTokenStatus != "" {
			f21.AuthTokenStatus = aws.String(string(resp.CacheCluster.PendingModifiedValues.AuthTokenStatus))
		}
		if resp.CacheCluster.PendingModifiedValues.CacheNodeIdsToRemove != nil {
			f21.CacheNodeIDsToRemove = aws.StringSlice(resp.CacheCluster.PendingModifiedValues.CacheNodeIdsToRemove)
		}
		if resp.CacheCluster.PendingModifiedValues.CacheNodeType != nil {
			f21.CacheNodeType = resp.CacheCluster.PendingModifiedValues.CacheNodeType
		}
		if resp.CacheCluster.PendingModifiedValues.EngineVersion != nil {
			f21.EngineVersion = resp.CacheCluster.PendingModifiedValues.EngineVersion
		}
		if resp.CacheCluster.PendingModifiedValues.NumCacheNodes != nil {
			numCacheNodesCopy := int64(*resp.CacheCluster.PendingModifiedValues.NumCacheNodes)
			f21.NumCacheNodes = &numCacheNodesCopy
		}
		if resp.CacheCluster.PendingModifiedValues.TransitEncryptionEnabled != nil {
			f21.TransitEncryptionEnabled = resp.CacheCluster.PendingModifiedValues.TransitEncryptionEnabled
		}
		if resp.CacheCluster.PendingModifiedValues.TransitEncryptionMode != "" {
			f21.TransitEncryptionMode = aws.String(string(resp.CacheCluster.PendingModifiedValues.TransitEncryptionMode))
		}
		ko.Status.PendingModifiedValues = f21
	} else {
		ko.Status.PendingModifiedValues = nil
	}
	if resp.CacheCluster.PreferredAvailabilityZone != nil {
		ko.Spec.PreferredAvailabilityZone = resp.CacheCluster.PreferredAvailabilityZone
	} else {
		ko.Spec.PreferredAvailabilityZone = nil
	}
	if resp.CacheCluster.PreferredMaintenanceWindow != nil {
		ko.Spec.PreferredMaintenanceWindow = resp.CacheCluster.PreferredMaintenanceWindow
	} else {
		ko.Spec.PreferredMaintenanceWindow = nil
	}
	if resp.CacheCluster.PreferredOutpostArn != nil {
		ko.Spec.PreferredOutpostARN = resp.CacheCluster.PreferredOutpostArn
	} else {
		ko.Spec.PreferredOutpostARN = nil
	}
	if resp.CacheCluster.ReplicationGroupId != nil {
		ko.Spec.ReplicationGroupID = resp.CacheCluster.ReplicationGroupId
	} else {
		ko.Spec.ReplicationGroupID = nil
	}
	if resp.CacheCluster.ReplicationGroupLogDeliveryEnabled != nil {
		ko.Status.ReplicationGroupLogDeliveryEnabled = resp.CacheCluster.ReplicationGroupLogDeliveryEnabled
	} else {
		ko.Status.ReplicationGroupLogDeliveryEnabled = nil
	}
	if resp.CacheCluster.SecurityGroups != nil {
		f27 := []*svcapitypes.SecurityGroupMembership{}
		for _, f27iter := range resp.CacheCluster.SecurityGroups {
			f27elem := &svcapitypes.SecurityGroupMembership{}
			if f27iter.SecurityGroupId != nil {
				f27elem.SecurityGroupID = f27iter.SecurityGroupId
			}
			if f27iter.Status != nil {
				f27elem.Status = f27iter.Status
			}
			f27 = append(f27, f27elem)
		}
		ko.Status.SecurityGroups = f27
	} else {
		ko.Status.SecurityGroups = nil
	}
	if resp.CacheCluster.SnapshotRetentionLimit != nil {
		snapshotRetentionLimitCopy := int64(*resp.CacheCluster.SnapshotRetentionLimit)
		ko.Spec.SnapshotRetentionLimit = &snapshotRetentionLimitCopy
	} else {
		ko.Spec.SnapshotRetentionLimit = nil
	}
	if resp.CacheCluster.SnapshotWindow != nil {
		ko.Spec.SnapshotWindow = resp.CacheCluster.SnapshotWindow
	} else {
		ko.Spec.SnapshotWindow = nil
	}
	if resp.CacheCluster.TransitEncryptionEnabled != nil {
		ko.Spec.TransitEncryptionEnabled = resp.CacheCluster.TransitEncryptionEnabled
	} else {
		ko.Spec.TransitEncryptionEnabled = nil
	}
	if resp.CacheCluster.TransitEncryptionMode != "" {
		ko.Status.TransitEncryptionMode = aws.String(string(resp.CacheCluster.TransitEncryptionMode))
	} else {
		ko.Status.TransitEncryptionMode = nil
	}

	rm.setStatusDefaults(ko)
	// custom set output from response
	ko, err = rm.customCreateCacheClusterSetOutput(ctx, desired, resp, ko)
	if err != nil {
		return nil, err
	}
	if isCreating(&resource{ko}) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
		return &resource{ko}, nil
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateCacheClusterInput, error) {
	res := &svcsdk.CreateCacheClusterInput{}

	if r.ko.Spec.AZMode != nil {
		res.AZMode = svcsdktypes.AZMode(*r.ko.Spec.AZMode)
	}
	if r.ko.Spec.AuthToken != nil {
		tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.AuthToken)
		if err != nil {
			return nil, ackrequeue.Needed(err)
		}
		if tmpSecret != "" {
			res.AuthToken = aws.String(tmpSecret)
		}
	}
	if r.ko.Spec.AutoMinorVersionUpgrade != nil {
		res.AutoMinorVersionUpgrade = r.ko.Spec.AutoMinorVersionUpgrade
	}
	if r.ko.Spec.CacheClusterID != nil {
		res.CacheClusterId = r.ko.Spec.CacheClusterID
	}
	if r.ko.Spec.CacheNodeType != nil {
		res.CacheNodeType = r.ko.Spec.CacheNodeType
	}
	if r.ko.Spec.CacheParameterGroupName != nil {
		res.CacheParameterGroupName = r.ko.Spec.CacheParameterGroupName
	}
	if r.ko.Spec.CacheSecurityGroupNames != nil {
		res.CacheSecurityGroupNames = aws.ToStringSlice(r.ko.Spec.CacheSecurityGroupNames)
	}
	if r.ko.Spec.CacheSubnetGroupName != nil {
		res.CacheSubnetGroupName = r.ko.Spec.CacheSubnetGroupName
	}
	if r.ko.Spec.Engine != nil {
		res.Engine = r.ko.Spec.Engine
	}
	if r.ko.Spec.EngineVersion != nil {
		res.EngineVersion = r.ko.Spec.EngineVersion
	}
	if r.ko.Spec.IPDiscovery != nil {
		res.IpDiscovery = svcsdktypes.IpDiscovery(*r.ko.Spec.IPDiscovery)
	}
	if r.ko.Spec.LogDeliveryConfigurations != nil {
		f11 := []svcsdktypes.LogDeliveryConfigurationRequest{}
		for _, f11iter := range r.ko.Spec.LogDeliveryConfigurations {
			f11elem := &svcsdktypes.LogDeliveryConfigurationRequest{}
			if f11iter.DestinationDetails != nil {
				f11elemf0 := &svcsdktypes.DestinationDetails{}
				if f11iter.DestinationDetails.CloudWatchLogsDetails != nil {
					f11elemf0f0 := &svcsdktypes.CloudWatchLogsDestinationDetails{}
					if f11iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
						f11elemf0f0.LogGroup = f11iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
					}
					f11elemf0.CloudWatchLogsDetails = f11elemf0f0
				}
				if f11iter.DestinationDetails.KinesisFirehoseDetails != nil {
					f11elemf0f1 := &svcsdktypes.KinesisFirehoseDestinationDetails{}
					if f11iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
						f11elemf0f1.DeliveryStream = f11iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
					}
					f11elemf0.KinesisFirehoseDetails = f11elemf0f1
				}
				f11elem.DestinationDetails = f11elemf0
			}
			if f11iter.DestinationType != nil {
				f11elem.DestinationType = svcsdktypes.DestinationType(*f11iter.DestinationType)
			}
			if f11iter.Enabled != nil {
				f11elem.Enabled = f11iter.Enabled
			}
			if f11iter.LogFormat != nil {
				f11elem.LogFormat = svcsdktypes.LogFormat(*f11iter.LogFormat)
			}
			if f11iter.LogType != nil {
				f11elem.LogType = svcsdktypes.LogType(*f11iter.LogType)
			}
			f11 = append(f11, *f11elem)
		}
		res.LogDeliveryConfigurations = f11
	}
	if r.ko.Spec.NetworkType != nil {
		res.NetworkType = svcsdktypes.NetworkType(*r.ko.Spec.NetworkType)
	}
	if r.ko.Spec.NotificationTopicARN != nil {
		res.NotificationTopicArn = r.ko.Spec.NotificationTopicARN
	}
	if r.ko.Spec.NumCacheNodes != nil {
		numCacheNodesCopy0 := *r.ko.Spec.NumCacheNodes
		if numCacheNodesCopy0 > math.MaxInt32 || numCacheNodesCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field NumCacheNodes is of type int32")
		}
		numCacheNodesCopy := int32(numCacheNodesCopy0)
		res.NumCacheNodes = &numCacheNodesCopy
	}
	if r.ko.Spec.OutpostMode != nil {
		res.OutpostMode = svcsdktypes.OutpostMode(*r.ko.Spec.OutpostMode)
	}
	if r.ko.Spec.Port != nil {
		portCopy0 := *r.ko.Spec.Port
		if portCopy0 > math.MaxInt32 || portCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Port is of type int32")
		}
		portCopy := int32(portCopy0)
		res.Port = &portCopy
	}
	if r.ko.Spec.PreferredAvailabilityZone != nil {
		res.PreferredAvailabilityZone = r.ko.Spec.PreferredAvailabilityZone
	}
	if r.ko.Spec.PreferredAvailabilityZones != nil {
		res.PreferredAvailabilityZones = aws.ToStringSlice(r.ko.Spec.PreferredAvailabilityZones)
	}
	if r.ko.Spec.PreferredMaintenanceWindow != nil {
		res.PreferredMaintenanceWindow = r.ko.Spec.PreferredMaintenanceWindow
	}
	if r.ko.Spec.PreferredOutpostARN != nil {
		res.PreferredOutpostArn = r.ko.Spec.PreferredOutpostARN
	}
	if r.ko.Spec.PreferredOutpostARNs != nil {
		res.PreferredOutpostArns = aws.ToStringSlice(r.ko.Spec.PreferredOutpostARNs)
	}
	if r.ko.Spec.ReplicationGroupID != nil {
		res.ReplicationGroupId = r.ko.Spec.ReplicationGroupID
	}
	if r.ko.Spec.SecurityGroupIDs != nil {
		res.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.SecurityGroupIDs)
	}
	if r.ko.Spec.SnapshotARNs != nil {
		res.SnapshotArns = aws.ToStringSlice(r.ko.Spec.SnapshotARNs)
	}
	if r.ko.Spec.SnapshotName != nil {
		res.SnapshotName = r.ko.Spec.SnapshotName
	}
	if r.ko.Spec.SnapshotRetentionLimit != nil {
		snapshotRetentionLimitCopy0 := *r.ko.Spec.SnapshotRetentionLimit
		if snapshotRetentionLimitCopy0 > math.MaxInt32 || snapshotRetentionLimitCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field SnapshotRetentionLimit is of type int32")
		}
		snapshotRetentionLimitCopy := int32(snapshotRetentionLimitCopy0)
		res.SnapshotRetentionLimit = &snapshotRetentionLimitCopy
	}
	if r.ko.Spec.SnapshotWindow != nil {
		res.SnapshotWindow = r.ko.Spec.SnapshotWindow
	}
	if r.ko.Spec.Tags != nil {
		f28 := []svcsdktypes.Tag{}
		for _, f28iter := range r.ko.Spec.Tags {
			f28elem := &svcsdktypes.Tag{}
			if f28iter.Key != nil {
				f28elem.Key = f28iter.Key
			}
			if f28iter.Value != nil {
				f28elem.Value = f28iter.Value
			}
			f28 = append(f28, *f28elem)
		}
		res.Tags = f28
	}
	if r.ko.Spec.TransitEncryptionEnabled != nil {
		res.TransitEncryptionEnabled = r.ko.Spec.TransitEncryptionEnabled
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if immutableFieldChanges := rm.getImmutableFieldChanges(delta); len(immutableFieldChanges) > 0 {
		msg := fmt.Sprintf("Immutable Spec fields have been modified: %s", strings.Join(immutableFieldChanges, ","))
		return nil, ackerr.NewTerminalError(fmt.Errorf(msg))
	}
	if delta.DifferentAt("Spec.Tags") {
		if err = rm.syncTags(ctx, desired, latest); err != nil {
			return nil, err
		}
	} else if !delta.DifferentExcept("Spec.Tags") {
		// If the only difference between the desired and latest is in the
		// Spec.Tags field, we can skip the ModifyCacheCluster call.
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}
	if err := rm.updateCacheClusterPayload(input, desired, latest, delta); err != nil {
		return nil, ackerr.NewTerminalError(err)
	}

	var resp *svcsdk.ModifyCacheClusterOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyCacheCluster(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyCacheCluster", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.CacheCluster.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.CacheCluster.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CacheCluster.AtRestEncryptionEnabled != nil {
		ko.Status.AtRestEncryptionEnabled = resp.CacheCluster.AtRestEncryptionEnabled
	} else {
		ko.Status.AtRestEncryptionEnabled = nil
	}
	if resp.CacheCluster.AuthTokenEnabled != nil {
		ko.Status.AuthTokenEnabled = resp.CacheCluster.AuthTokenEnabled
	} else {
		ko.Status.AuthTokenEnabled = nil
	}
	if resp.CacheCluster.AuthTokenLastModifiedDate != nil {
		ko.Status.AuthTokenLastModifiedDate = &metav1.Time{*resp.CacheCluster.AuthTokenLastModifiedDate}
	} else {
		ko.Status.AuthTokenLastModifiedDate = nil
	}
	if resp.CacheCluster.AutoMinorVersionUpgrade != nil {
		ko.Spec.AutoMinorVersionUpgrade = resp.CacheCluster.AutoMinorVersionUpgrade
	} else {
		ko.Spec.AutoMinorVersionUpgrade = nil
	}
	if resp.CacheCluster.CacheClusterCreateTime != nil {
		ko.Status.CacheClusterCreateTime = &metav1.Time{*resp.CacheCluster.CacheClusterCreateTime}
	} else {
		ko.Status.CacheClusterCreateTime = nil
	}
	if resp.CacheCluster.CacheClusterId != nil {
		ko.Spec.CacheClusterID = resp.CacheCluster.CacheClusterId
	} else {
		ko.Spec.CacheClusterID = nil
	}
	if resp.CacheCluster.CacheClusterStatus != nil {
		ko.Status.CacheClusterStatus = resp.CacheCluster.CacheClusterStatus
	} else {
		ko.Status.CacheClusterStatus = nil
	}
	if resp.CacheCluster.CacheNodeType != nil {
		ko.Spec.CacheNodeType = resp.CacheCluster.CacheNodeType
	} else {
		ko.Spec.CacheNodeType = nil
	}
	if resp.CacheCluster.CacheNodes != nil {
		f9 := []*svcapitypes.CacheNode{}
		for _, f9iter := range resp.CacheCluster.CacheNodes {
			f9elem := &svcapitypes.CacheNode{}
			if f9iter.CacheNodeCreateTime != nil {
				f9elem.CacheNodeCreateTime = &metav1.Time{*f9iter.CacheNodeCreateTime}
			}
			if f9iter.CacheNodeId != nil {
				f9elem.CacheNodeID = f9iter.CacheNodeId
			}
			if f9iter.CacheNodeStatus != nil {
				f9elem.CacheNodeStatus = f9iter.CacheNodeStatus
			}
			if f9iter.CustomerAvailabilityZone != nil {
				f9elem.CustomerAvailabilityZone = f9iter.CustomerAvailabilityZone
			}
			if f9iter.CustomerOutpostArn != nil {
				f9elem.CustomerOutpostARN = f9iter.CustomerOutpostArn
			}
			if f9iter.Endpoint != nil {
				f9elemf5 := &svcapitypes.Endpoint{}
				if f9iter.Endpoint.Address != nil {
					f9elemf5.Address = f9iter.Endpoint.Address
				}
				if f9iter.Endpoint.Port != nil {
					portCopy := int64(*f9iter.Endpoint.Port)
					f9elemf5.Port = &portCopy
				}
				f9elem.Endpoint = f9elemf5
			}
			if f9iter.ParameterGroupStatus != nil {
				f9elem.ParameterGroupStatus = f9iter.ParameterGroupStatus
			}
			if f9iter.SourceCacheNodeId != nil {
				f9elem.SourceCacheNodeID = f9iter.SourceCacheNodeId
			}
			f9 = append(f9, f9elem)
		}
		ko.Status.CacheNodes = f9
	} else {
		ko.Status.CacheNodes = nil
	}
	if resp.CacheCluster.CacheParameterGroup != nil {
		f10 := &svcapitypes.CacheParameterGroupStatus_SDK{}
		if resp.CacheCluster.CacheParameterGroup.CacheNodeIdsToReboot != nil {
			f10.CacheNodeIDsToReboot = aws.StringSlice(resp.CacheCluster.CacheParameterGroup.CacheNodeIdsToReboot)
		}
		if resp.CacheCluster.CacheParameterGroup.CacheParameterGroupName != nil {
			f10.CacheParameterGroupName = resp.CacheCluster.CacheParameterGroup.CacheParameterGroupName
		}
		if resp.CacheCluster.CacheParameterGroup.ParameterApplyStatus != nil {
			f10.ParameterApplyStatus = resp.CacheCluster.CacheParameterGroup.ParameterApplyStatus
		}
		ko.Status.CacheParameterGroup = f10
	} else {
		ko.Status.CacheParameterGroup = nil
	}
	if resp.CacheCluster.CacheSecurityGroups != nil {
		f11 := []*svcapitypes.CacheSecurityGroupMembership{}
		for _, f11iter := range resp.CacheCluster.CacheSecurityGroups {
			f11elem := &svcapitypes.CacheSecurityGroupMembership{}
			if f11iter.CacheSecurityGroupName != nil {
				f11elem.CacheSecurityGroupName = f11iter.CacheSecurityGroupName
			}
			if f11iter.Status != nil {
				f11elem.Status = f11iter.Status
			}
			f11 = append(f11, f11elem)
		}
		ko.Status.CacheSecurityGroups = f11
	} else {
		ko.Status.CacheSecurityGroups = nil
	}
	if resp.CacheCluster.CacheSubnetGroupName != nil {
		ko.Spec.CacheSubnetGroupName = resp.CacheCluster.CacheSubnetGroupName
	} else {
		ko.Spec.CacheSubnetGroupName = nil
	}
	if resp.CacheCluster.ClientDownloadLandingPage != nil {
		ko.Status.ClientDownloadLandingPage = resp.CacheCluster.ClientDownloadLandingPage
	} else {
		ko.Status.ClientDownloadLandingPage = nil
	}
	if resp.CacheCluster.ConfigurationEndpoint != nil {
		f14 := &svcapitypes.Endpoint{}
		if resp.CacheCluster.ConfigurationEndpoint.Address != nil {
			f14.Address = resp.CacheCluster.ConfigurationEndpoint.Address
		}
		if resp.CacheCluster.ConfigurationEndpoint.Port != nil {
			portCopy := int64(*resp.CacheCluster.ConfigurationEndpoint.Port)
			f14.Port = &portCopy
		}
		ko.Status.ConfigurationEndpoint = f14
	} else {
		ko.Status.ConfigurationEndpoint = nil
	}
	if resp.CacheCluster.Engine != nil {
		ko.Spec.Engine = resp.CacheCluster.Engine
	} else {
		ko.Spec.Engine = nil
	}
	if resp.CacheCluster.EngineVersion != nil {
		ko.Spec.EngineVersion = resp.CacheCluster.EngineVersion
	} else {
		ko.Spec.EngineVersion = nil
	}
	if resp.CacheCluster.IpDiscovery != "" {
		ko.Spec.IPDiscovery = aws.String(string(resp.CacheCluster.IpDiscovery))
	} else {
		ko.Spec.IPDiscovery = nil
	}
	if resp.CacheCluster.NetworkType != "" {
		ko.Spec.NetworkType = aws.String(string(resp.CacheCluster.NetworkType))
	} else {
		ko.Spec.NetworkType = nil
	}
	if resp.CacheCluster.NotificationConfiguration != nil {
		f19 := &svcapitypes.NotificationConfiguration{}
		if resp.CacheCluster.NotificationConfiguration.TopicArn != nil {
			f19.TopicARN = resp.CacheCluster.NotificationConfiguration.TopicArn
		}
		if resp.CacheCluster.NotificationConfiguration.TopicStatus != nil {
			f19.TopicStatus = resp.CacheCluster.NotificationConfiguration.TopicStatus
		}
		ko.Status.NotificationConfiguration = f19
	} else {
		ko.Status.NotificationConfiguration = nil
	}
	if resp.CacheCluster.NumCacheNodes != nil {
		numCacheNodesCopy := int64(*resp.CacheCluster.NumCacheNodes)
		ko.Spec.NumCacheNodes = &numCacheNodesCopy
	} else {
		ko.Spec.NumCacheNodes = nil
	}
	if resp.CacheCluster.PendingModifiedValues != nil {
		f21 := &svcapitypes.PendingModifiedValues{}
		if resp.CacheCluster.PendingModifiedValues.AuthTokenStatus != "" {
			f21.AuthTokenStatus = aws.String(string(resp.CacheCluster.PendingModifiedValues.AuthTokenStatus))
		}
		if resp.CacheCluster.PendingModifiedValues.CacheNodeIdsToRemove != nil {
			f21.CacheNodeIDsToRemove = aws.StringSlice(resp.CacheCluster.PendingModifiedValues.CacheNodeIdsToRemove)
		}
		if resp.CacheCluster.PendingModifiedValues.CacheNodeType != nil {
			f21.CacheNodeType = resp.CacheCluster.PendingModifiedValues.CacheNodeType
		}
		if resp.CacheCluster.PendingModifiedValues.EngineVersion != nil {
			f21.EngineVersion = resp.CacheCluster.PendingModifiedValues.EngineVersion
		}
		if resp.CacheCluster.PendingModifiedValues.NumCacheNodes != nil {
			numCacheNodesCopy := int64(*resp.CacheCluster.PendingModifiedValues.NumCacheNodes)
			f21.NumCacheNodes = &numCacheNodesCopy
		}
		if resp.CacheCluster.PendingModifiedValues.TransitEncryptionEnabled != nil {
			f21.TransitEncryptionEnabled = resp.CacheCluster.PendingModifiedValues.TransitEncryptionEnabled
		}
		if resp.CacheCluster.PendingModifiedValues.TransitEncryptionMode != "" {
			f21.TransitEncryptionMode = aws.String(string(resp.CacheCluster.PendingModifiedValues.TransitEncryptionMode))
		}
		ko.Status.PendingModifiedValues = f21
	} else {
		ko.Status.PendingModifiedValues = nil
	}
	if resp.CacheCluster.PreferredAvailabilityZone != nil {
		ko.Spec.PreferredAvailabilityZone = resp.CacheCluster.PreferredAvailabilityZone
	} else {
		ko.Spec.PreferredAvailabilityZone = nil
	}
	if resp.CacheCluster.PreferredMaintenanceWindow != nil {
		ko.Spec.PreferredMaintenanceWindow = resp.CacheCluster.PreferredMaintenanceWindow
	} else {
		ko.Spec.PreferredMaintenanceWindow = nil
	}
	if resp.CacheCluster.PreferredOutpostArn != nil {
		ko.Spec.PreferredOutpostARN = resp.CacheCluster.PreferredOutpostArn
	} else {
		ko.Spec.PreferredOutpostARN = nil
	}
	if resp.CacheCluster.ReplicationGroupId != nil {
		ko.Spec.ReplicationGroupID = resp.CacheCluster.ReplicationGroupId
	} else {
		ko.Spec.ReplicationGroupID = nil
	}
	if resp.CacheCluster.ReplicationGroupLogDeliveryEnabled != nil {
		ko.Status.ReplicationGroupLogDeliveryEnabled = resp.CacheCluster.ReplicationGroupLogDeliveryEnabled
	} else {
		ko.Status.ReplicationGroupLogDeliveryEnabled = nil
	}
	if resp.CacheCluster.SecurityGroups != nil {
		f27 := []*svcapitypes.SecurityGroupMembership{}
		for _, f27iter := range resp.CacheCluster.SecurityGroups {
			f27elem := &svcapitypes.SecurityGroupMembership{}
			if f27iter.SecurityGroupId != nil {
				f27elem.SecurityGroupID = f27iter.SecurityGroupId
			}
			if f27iter.Status != nil {
				f27elem.Status = f27iter.Status
			}
			f27 = append(f27, f27elem)
		}
		ko.Status.SecurityGroups = f27
	} else {
		ko.Status.SecurityGroups = nil
	}
	if resp.CacheCluster.SnapshotRetentionLimit != nil {
		snapshotRetentionLimitCopy := int64(*resp.CacheCluster.SnapshotRetentionLimit)
		ko.Spec.SnapshotRetentionLimit = &snapshotRetentionLimitCopy
	} else {
		ko.Spec.SnapshotRetentionLimit = nil
	}
	if resp.CacheCluster.SnapshotWindow != nil {
		ko.Spec.SnapshotWindow = resp.CacheCluster.SnapshotWindow
	} else {
		ko.Spec.SnapshotWindow = nil
	}
	if resp.CacheCluster.TransitEncryptionEnabled != nil {
		ko.Spec.TransitEncryptionEnabled = resp.CacheCluster.TransitEncryptionEnabled
	} else {
		ko.Spec.TransitEncryptionEnabled = nil
	}
	if resp.CacheCluster.TransitEncryptionMode != "" {
		ko.Status.TransitEncryptionMode = aws.String(string(resp.CacheCluster.TransitEncryptionMode))
	} else {
		ko.Status.TransitEncryptionMode = nil
	}

	rm.setStatusDefaults(ko)
	// custom set output from response
	ko, err = rm.customModifyCacheClusterSetOutput(ctx, desired, resp, ko)
	if err != nil {
		return nil, err
	}
	if pendingModifications := resp.CacheCluster.PendingModifiedValues; pendingModifications != nil {
		if pendingModifications.NumCacheNodes != nil {
			ko.Spec.NumCacheNodes = pendingModifications.NumCacheNodes
		}
		if pendingModifications.CacheNodeType != nil {
			ko.Spec.CacheNodeType = pendingModifications.CacheNodeType
		}
		if pendingModifications.TransitEncryptionEnabled != nil {
			ko.Spec.TransitEncryptionEnabled = pendingModifications.TransitEncryptionEnabled
		}
	}

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.ModifyCacheClusterInput, error) {
	res := &svcsdk.ModifyCacheClusterInput{}

	if r.ko.Spec.AZMode != nil {
		res.AZMode = svcsdktypes.AZMode(*r.ko.Spec.AZMode)
	}
	res.ApplyImmediately = true
	if r.ko.Spec.AuthToken != nil {
		tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.AuthToken)
		if err != nil {
			return nil, ackrequeue.Needed(err)
		}
		if tmpSecret != "" {
			res.AuthToken = aws.String(tmpSecret)
		}
	}
	if r.ko.Spec.AutoMinorVersionUpgrade != nil {
		res.AutoMinorVersionUpgrade = r.ko.Spec.AutoMinorVersionUpgrade
	}
	if r.ko.Spec.CacheClusterID != nil {
		res.CacheClusterId = r.ko.Spec.CacheClusterID
	}
	if r.ko.Spec.CacheNodeType != nil {
		res.CacheNodeType = r.ko.Spec.CacheNodeType
	}
	if r.ko.Spec.CacheParameterGroupName != nil {
		res.CacheParameterGroupName = r.ko.Spec.CacheParameterGroupName
	}
	if r.ko.Spec.CacheSecurityGroupNames != nil {
		res.CacheSecurityGroupNames = aws.ToStringSlice(r.ko.Spec.CacheSecurityGroupNames)
	}
	if r.ko.Spec.Engine != nil {
		res.Engine = r.ko.Spec.Engine
	}
	if r.ko.Spec.EngineVersion != nil {
		res.EngineVersion = r.ko.Spec.EngineVersion
	}
	if r.ko.Spec.IPDiscovery != nil {
		res.IpDiscovery = svcsdktypes.IpDiscovery(*r.ko.Spec.IPDiscovery)
	}
	if r.ko.Spec.LogDeliveryConfigurations != nil {
		f13 := []svcsdktypes.LogDeliveryConfigurationRequest{}
		for _, f13iter := range r.ko.Spec.LogDeliveryConfigurations {
			f13elem := &svcsdktypes.LogDeliveryConfigurationRequest{}
			if f13iter.DestinationDetails != nil {
				f13elemf0 := &svcsdktypes.DestinationDetails{}
				if f13iter.DestinationDetails.CloudWatchLogsDetails != nil {
					f13elemf0f0 := &svcsdktypes.CloudWatchLogsDestinationDetails{}
					if f13iter.DestinationDetails.CloudWatchLogsDetails.LogGroup != nil {
						f13elemf0f0.LogGroup = f13iter.DestinationDetails.CloudWatchLogsDetails.LogGroup
					}
					f13elemf0.CloudWatchLogsDetails = f13elemf0f0
				}
				if f13iter.DestinationDetails.KinesisFirehoseDetails != nil {
					f13elemf0f1 := &svcsdktypes.KinesisFirehoseDestinationDetails{}
					if f13iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream != nil {
						f13elemf0f1.DeliveryStream = f13iter.DestinationDetails.KinesisFirehoseDetails.DeliveryStream
					}
					f13elemf0.KinesisFirehoseDetails = f13elemf0f1
				}
				f13elem.DestinationDetails = f13elemf0
			}
			if f13iter.DestinationType != nil {
				f13elem.DestinationType = svcsdktypes.DestinationType(*f13iter.DestinationType)
			}
			if f13iter.Enabled != nil {
				f13elem.Enabled = f13iter.Enabled
			}
			if f13iter.LogFormat != nil {
				f13elem.LogFormat = svcsdktypes.LogFormat(*f13iter.LogFormat)
			}
			if f13iter.LogType != nil {
				f13elem.LogType = svcsdktypes.LogType(*f13iter.LogType)
			}
			f13 = append(f13, *f13elem)
		}
		res.LogDeliveryConfigurations = f13
	}
	if r.ko.Spec.NotificationTopicARN != nil {
		res.NotificationTopicArn = r.ko.Spec.NotificationTopicARN
	}
	if r.ko.Spec.NumCacheNodes != nil {
		numCacheNodesCopy0 := *r.ko.Spec.NumCacheNodes
		if numCacheNodesCopy0 > math.MaxInt32 || numCacheNodesCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field NumCacheNodes is of type int32")
		}
		numCacheNodesCopy := int32(numCacheNodesCopy0)
		res.NumCacheNodes = &numCacheNodesCopy
	}
	if r.ko.Spec.PreferredMaintenanceWindow != nil {
		res.PreferredMaintenanceWindow = r.ko.Spec.PreferredMaintenanceWindow
	}
	if r.ko.Spec.SecurityGroupIDs != nil {
		res.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.SecurityGroupIDs)
	}
	if r.ko.Spec.SnapshotRetentionLimit != nil {
		snapshotRetentionLimitCopy0 := *r.ko.Spec.SnapshotRetentionLimit
		if snapshotRetentionLimitCopy0 > math.MaxInt32 || snapshotRetentionLimitCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field SnapshotRetentionLimit is of type int32")
		}
		snapshotRetentionLimitCopy := int32(snapshotRetentionLimitCopy0)
		res.SnapshotRetentionLimit = &snapshotRetentionLimitCopy
	}
	if r.ko.Spec.SnapshotWindow != nil {
		res.SnapshotWindow = r.ko.Spec.SnapshotWindow
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	if isDeleting(r) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource.
		ackcondition.SetSynced(
			r,
			corev1.ConditionFalse,
			&condMsgCurrentlyDeleting,
			nil,
		)
		// Need to return a requeue error here, otherwise:
		// - reconciler.deleteResource() marks the resource unmanaged
		// - reconciler.HandleReconcileError() does not update status for unmanaged resource
		// - reconciler.handleRequeues() is not invoked for delete code path.
		// TODO: return err as nil when reconciler is updated.
		return r, requeueWaitWhileDeleting
	}
	if isModifying(r) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource.
		ackcondition.SetSynced(
			r,
			corev1.ConditionFalse,
			&condMsgNoDeleteWhileModifying,
			nil,
		)
		// Need to return a requeue error here, otherwise:
		// - reconciler.deleteResource() marks the resource unmanaged
		// - reconciler.HandleReconcileError() does not update status for unmanaged resource
		// - reconciler.handleRequeues() is not invoked for delete code path.
		// TODO: return err as nil when reconciler is updated.
		return r, requeueWaitWhileModifying
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteCacheClusterOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteCacheCluster(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteCacheCluster", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteCacheClusterInput, error) {
	res := &svcsdk.DeleteCacheClusterInput{}

	if r.ko.Spec.CacheClusterID != nil {
		res.CacheClusterId = r.ko.Spec.CacheClusterID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.CacheCluster,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ReplicationGroupNotFoundFault",
		"InvalidReplicationGroupStateFault",
		"CacheClusterAlreadyExistsFault",
		"InsufficientCacheClusterCapacityFault",
		"CacheSecurityGroupNotFoundFault",
		"CacheSubnetGroupNotFoundFault",
		"ClusterQuotaForCustomerExceededFault",
		"NodeQuotaForClusterExceededFault",
		"NodeQuotaForCustomerExceededFault",
		"CacheParameterGroupNotFoundFault",
		"InvalidVPCNetworkStateFault",
		"TagQuotaPerResource",
		"InvalidParameterValue",
		"InvalidParameterCombination":
		return true
	default:
		return false
	}
}

// getImmutableFieldChanges returns list of immutable fields from the
func (rm *resourceManager) getImmutableFieldChanges(
	delta *ackcompare.Delta,
) []string {
	var fields []string
	if delta.DifferentAt("Spec.CacheParameterGroupName") {
		fields = append(fields, "CacheParameterGroupName")
	}
	if delta.DifferentAt("Spec.ReplicationGroupID") {
		fields = append(fields, "ReplicationGroupID")
	}
	if delta.DifferentAt("Spec.SnapshotName") {
		fields = append(fields, "SnapshotName")
	}

	return fields
}
